/**
 * Well-formedness guard for ALL committed data JSON - autogenerated and
 * hand-edited.
 *
 * oxfmt parses every JSON it formats, but several data-JSON groups are excluded
 * from oxfmt (server/out/*.json, syntaxes/*.tmLanguage.json, themes/*.json) and
 * so bypass that check. A committed corruption - the unescaped-quote class that
 * silently emptied the WeiDU TP2 provider - would otherwise ship undetected.
 * This validates every data JSON with the parser its runtime consumer uses:
 *
 *   strict (JSON.parse): machine-emitted JSON - server/out, the generated
 *     TextMate grammars, and binary data - which is plain RFC-8259 JSON.
 *   JSONC (jsonc-parser, the library VSCode itself loads them with): the VSCode
 *     assets - themes, language configurations, snippets - which legally permit
 *     // comments and trailing commas.
 *
 * server/out is additionally asserted non-empty by
 * server/test/core/generated-data-integrity.test.ts; the parse overlap here is
 * what makes this the single cross-cutting well-formedness gate.
 */

import { execSync } from "node:child_process";
import fs from "node:fs";
import { type ParseError, parse, printParseErrorCode } from "jsonc-parser";
import { describe, expect, it } from "vitest";

function lsFiles(...patterns: string[]): string[] {
    const spec = patterns.map((p) => `'${p}'`).join(" ");
    return execSync(`git ls-files -- ${spec}`, { encoding: "utf8" }).split("\n").filter(Boolean);
}

const strictFiles = lsFiles("server/out/*.json", "syntaxes/*.tmLanguage.json", "binary/data/*.json");
const jsoncFiles = lsFiles("themes/*.json", "language-configurations/*.json", "snippets/*.json");

describe("committed data JSON is well-formed", () => {
    it("discovers data JSON files", () => {
        expect(strictFiles.length + jsoncFiles.length).toBeGreaterThan(0);
    });

    it.each(strictFiles)("%s is valid strict JSON", (file) => {
        expect(() => JSON.parse(fs.readFileSync(file, "utf8"))).not.toThrow();
    });

    it.each(jsoncFiles)("%s is valid JSONC", (file) => {
        const errors: ParseError[] = [];
        parse(fs.readFileSync(file, "utf8"), errors, { allowTrailingComma: true });
        const detail = errors.map((e) => `${printParseErrorCode(e.error)} at offset ${e.offset}`).join("; ");
        expect(errors, detail).toHaveLength(0);
    });
});
