/**
 * Engine function names as written in source, mapped to the opcode they compile to.
 *
 * A call like `display_msg("x")` is not a procedure call: it pushes its arguments and then a single
 * opcode the engine dispatches on. This table is what turns the source spelling into that number, so
 * the front end needs no knowledge of the opcode layout.
 *
 * `popsResult` marks the 27 functions that return a value even when called as a statement; their
 * statement form drops the result rather than leaving it on the stack.
 *
 * Fallout 1 reuses 7 opcode numbers for different functions under different source names (see
 * `opcodes-engine.ts`). Those names are listed separately so that compiling for Fallout 2 does not
 * silently accept a Fallout 1 spelling and emit the wrong function.
 */

import { EngineOp, FALLOUT1_OPCODES, LibOp } from "./opcodes-engine";

export interface EngineFunction {
    opcode: number;
    /** The statement form discards a returned value. */
    popsResult?: boolean;
}

/**
 * Engine functions available when targeting Fallout 2, keyed by LOWERCASED source name. The language
 * matches these case-insensitively - some are declared in upper case and written in lower case in real
 * scripts - so callers must lowercase before looking one up.
 */
export const ENGINE_FUNCTIONS: Readonly<Record<string, EngineFunction>> = {
    reg_anim_func: { opcode: EngineOp.REG_ANIM_FUNC },
    abs: { opcode: EngineOp.TS_ABS },
    action_being_used: { opcode: EngineOp.ACTION_BEING_USED },
    activate_shader: { opcode: EngineOp.TS_ACTIVATE_SHADER },
    activateregion: { opcode: LibOp.ACTIVATEREGION },
    active_hand: { opcode: EngineOp.TS_GET_ACTIVE_HAND },
    add_mult_objs_to_inven: { opcode: EngineOp.ADD_MULT_OBJS_TO_INVEN },
    add_obj_to_inven: { opcode: EngineOp.ADD_OBJ_TO_INVEN },
    add_timer_event: { opcode: EngineOp.ADD_TIMER_EVENT },
    addbutton: { opcode: LibOp.ADDBUTTON },
    addbuttonflag: { opcode: LibOp.ADDBUTTONFLAG },
    addbuttongfx: { opcode: LibOp.ADDBUTTONGFX },
    addbuttonproc: { opcode: LibOp.ADDBUTTONPROC },
    addbuttonrightproc: { opcode: LibOp.ADDBUTTONRIGHTPROC },
    addbuttontext: { opcode: LibOp.ADDBUTTONTEXT },
    addkey: { opcode: LibOp.ADDKEY },
    addnamedevent: { opcode: LibOp.ADDNAMEDEVENT },
    addnamedhandler: { opcode: LibOp.ADDNAMEDHANDLER },
    addregion: { opcode: LibOp.ADDREGION },
    addregionflag: { opcode: LibOp.ADDREGIONFLAG },
    addregionproc: { opcode: LibOp.ADDREGIONPROC },
    addregionrightproc: { opcode: LibOp.ADDREGIONRIGHTPROC },
    anim: { opcode: EngineOp.ANIM },
    anim_action_frame: { opcode: EngineOp.ANIM_ACTION_FRAME },
    anim_busy: { opcode: EngineOp.ANIM_BUSY },
    animate_move_obj_to_tile: { opcode: EngineOp.ANIMATE_MOVE_OBJ_TO_TILE },
    animate_stand_obj: { opcode: EngineOp.ANIMATE_STAND_OBJ },
    animate_stand_reverse_obj: { opcode: EngineOp.ANIMATE_STAND_REVERSE_OBJ },
    apply_heaveho_fix: { opcode: EngineOp.TS_APPLY_HEAVEHO_FIX },
    arctan: { opcode: EngineOp.TS_ATAN },
    array_key: { opcode: EngineOp.TS_GET_ARRAY_KEY },
    arrayexpr: { opcode: EngineOp.TS_STACK_ARRAY },
    art_anim: { opcode: EngineOp.ART_ANIM },
    art_exists: { opcode: EngineOp.TS_ART_EXISTS },
    atof: { opcode: EngineOp.TS_ATOF },
    atoi: { opcode: EngineOp.TS_ATOI },
    attack: { opcode: EngineOp.ATTACK },
    attack_complex: { opcode: EngineOp.ATTACK_COMPLEX },
    attack_setup: { opcode: EngineOp.ATTACK_SETUP },
    available_global_script_types: { opcode: EngineOp.TS_AVAILABLE_GLOBAL_SCRIPT_TYPES },
    block_combat: { opcode: EngineOp.TS_BLOCK_COMBAT },
    call_offset_r0: { opcode: EngineOp.TS_CALL_OFFSET_R0 },
    call_offset_r1: { opcode: EngineOp.TS_CALL_OFFSET_R1 },
    call_offset_r2: { opcode: EngineOp.TS_CALL_OFFSET_R2 },
    call_offset_r3: { opcode: EngineOp.TS_CALL_OFFSET_R3 },
    call_offset_r4: { opcode: EngineOp.TS_CALL_OFFSET_R4 },
    call_offset_v0: { opcode: EngineOp.TS_CALL_OFFSET_V0 },
    call_offset_v1: { opcode: EngineOp.TS_CALL_OFFSET_V1 },
    call_offset_v2: { opcode: EngineOp.TS_CALL_OFFSET_V2 },
    call_offset_v3: { opcode: EngineOp.TS_CALL_OFFSET_V3 },
    call_offset_v4: { opcode: EngineOp.TS_CALL_OFFSET_V4 },
    ceil: { opcode: EngineOp.TS_CEIL },
    charcode: { opcode: EngineOp.TS_ORD },
    checkregion: { opcode: LibOp.CHECKREGION },
    clear_selectable_perks: { opcode: EngineOp.TS_CLEAR_SELECTABLE_PERKS },
    clearnamed: { opcode: LibOp.CLEARNAMED },
    combat_difficulty: { opcode: EngineOp.COMBAT_DIFFICULTY },
    combat_is_initialized: { opcode: EngineOp.COMBAT_IS_INITIALIZED },
    cos: { opcode: EngineOp.TS_COS },
    create_array: { opcode: EngineOp.TS_CREATE_ARRAY },
    create_message_window: { opcode: EngineOp.TS_CREATE_MESSAGE_WINDOW },
    create_object_sid: { opcode: EngineOp.CREATE_OBJECT_SID, popsResult: true },
    create_spatial: { opcode: EngineOp.TS_CREATE_SPATIAL, popsResult: true },
    createwin: { opcode: LibOp.CREATEWIN },
    critter_add_trait: { opcode: EngineOp.CRITTER_ADD_TRAIT, popsResult: true },
    critter_attempt_placement: { opcode: EngineOp.CRITTER_ATTEMPT_PLACEMENT, popsResult: true },
    critter_dmg: { opcode: EngineOp.CRITTER_DMG },
    critter_heal: { opcode: EngineOp.CRITTER_HEAL, popsResult: true },
    critter_injure: { opcode: EngineOp.CRITTER_INJURE },
    critter_inven_obj: { opcode: EngineOp.CRITTER_INVEN_OBJ },
    critter_is_fleeing: { opcode: EngineOp.CRITTER_IS_FLEEING },
    critter_mod_skill: { opcode: EngineOp.CRITTER_MOD_SKILL },
    critter_rm_trait: { opcode: EngineOp.CRITTER_RM_TRAIT, popsResult: true },
    critter_set_flee_state: { opcode: EngineOp.CRITTER_SET_FLEE_STATE },
    critter_state: { opcode: EngineOp.CRITTER_STATE },
    critter_stop_attacking: { opcode: EngineOp.CRITTER_STOP_ATTACKING },
    cur_map_index: { opcode: EngineOp.CUR_MAP_INDEX },
    days_since_visited: { opcode: EngineOp.DAYS_SINCE_VISITED },
    deactivate_shader: { opcode: EngineOp.TS_DEACTIVATE_SHADER },
    debug_msg: { opcode: EngineOp.DEBUG_MSG },
    deletebutton: { opcode: LibOp.DELETEBUTTON },
    deletekey: { opcode: LibOp.DELETEKEY },
    deleteregion: { opcode: LibOp.DELETEREGION },
    deletewin: { opcode: LibOp.DELETEWIN },
    destroy_mult_objs: { opcode: EngineOp.DESTROY_MULT_OBJS },
    destroy_object: { opcode: EngineOp.DESTROY_OBJECT },
    dialogue_reaction: { opcode: EngineOp.DIALOGUE_REACTION },
    dialogue_system_enter: { opcode: EngineOp.DIALOGUE_SYSTEM_ENTER },
    difficulty_level: { opcode: EngineOp.DIFFICULTY_LEVEL },
    disable_aimed_shots: { opcode: EngineOp.TS_DISABLE_AIMED_SHOTS },
    display: { opcode: LibOp.DISPLAY },
    display_msg: { opcode: EngineOp.DISPLAY_MSG },
    displaygfx: { opcode: LibOp.DISPLAYGFX },
    displayraw: { opcode: LibOp.DISPLAYRAW },
    do_check: { opcode: EngineOp.DO_CHECK, popsResult: true },
    drop_obj: { opcode: EngineOp.DROP_OBJ },
    dude_obj: { opcode: EngineOp.DUDE_OBJ },
    eax_available: { opcode: EngineOp.TS_EAX_AVAILABLE },
    elevation: { opcode: EngineOp.ELEVATION },
    end_dialogue: { opcode: EngineOp.END_DIALOGUE },
    endgame_movie: { opcode: EngineOp.ENDGAME_MOVIE },
    endgame_slideshow: { opcode: EngineOp.ENDGAME_SLIDESHOW },
    explosion: { opcode: EngineOp.EXPLOSION },
    exponent: { opcode: EngineOp.TS_EXP },
    fadein: { opcode: LibOp.FADEIN },
    fadeout: { opcode: LibOp.FADEOUT },
    fillrect: { opcode: LibOp.FILLRECT },
    fillwin: { opcode: LibOp.FILLWIN },
    fillwin3x3: { opcode: LibOp.FILLWIN3X3 },
    fix_array: { opcode: EngineOp.TS_FIX_ARRAY },
    fixed_param: { opcode: EngineOp.FIXED_PARAM },
    float_msg: { opcode: EngineOp.FLOAT_MSG },
    force_aimed_shots: { opcode: EngineOp.TS_FORCE_AIMED_SHOTS },
    force_encounter: { opcode: EngineOp.TS_FORCE_ENCOUNTER },
    force_encounter_with_flags: { opcode: EngineOp.TS_FORCE_ENCOUNTER_WITH_FLAGS },
    force_graphics_refresh: { opcode: EngineOp.TS_FORCE_GRAPHICS_REFRESH },
    format: { opcode: LibOp.FORMAT },
    free_array: { opcode: EngineOp.TS_FREE_ARRAY },
    free_shader: { opcode: EngineOp.TS_FREE_SHADER },
    fs_copy: { opcode: EngineOp.TS_FS_COPY },
    fs_create: { opcode: EngineOp.TS_FS_CREATE },
    fs_delete: { opcode: EngineOp.TS_FS_DELETE },
    fs_find: { opcode: EngineOp.TS_FS_FIND },
    fs_pos: { opcode: EngineOp.TS_FS_POS },
    fs_read_byte: { opcode: EngineOp.TS_FS_READ_BYTE },
    fs_read_float: { opcode: EngineOp.TS_FS_READ_FLOAT },
    fs_read_int: { opcode: EngineOp.TS_FS_READ_INT },
    fs_read_short: { opcode: EngineOp.TS_FS_READ_SHORT },
    fs_resize: { opcode: EngineOp.TS_FS_RESIZE },
    fs_seek: { opcode: EngineOp.TS_FS_SEEK },
    fs_size: { opcode: EngineOp.TS_FS_SIZE },
    fs_write_bstring: { opcode: EngineOp.TS_FS_WRITE_BSTRING },
    fs_write_byte: { opcode: EngineOp.TS_FS_WRITE_BYTE },
    fs_write_float: { opcode: EngineOp.TS_FS_WRITE_FLOAT },
    fs_write_int: { opcode: EngineOp.TS_FS_WRITE_INT },
    fs_write_short: { opcode: EngineOp.TS_FS_WRITE_SHORT },
    fs_write_string: { opcode: EngineOp.TS_FS_WRITE_STRING },
    game_loaded: { opcode: EngineOp.TS_GAME_LOADED },
    game_ticks: { opcode: EngineOp.GAME_TICKS },
    game_time: { opcode: EngineOp.GAME_TIME },
    game_time_advance: { opcode: EngineOp.GAME_TIME_ADVANCE },
    game_time_hour: { opcode: EngineOp.GAME_TIME_HOUR },
    game_time_in_seconds: { opcode: EngineOp.GAME_TIME_IN_SECONDS },
    game_ui_disable: { opcode: EngineOp.GAME_UI_DISABLE },
    game_ui_enable: { opcode: EngineOp.GAME_UI_ENABLE },
    game_ui_is_disabled: { opcode: EngineOp.GAME_UI_IS_DISABLED },
    gdialog_get_barter_mod: { opcode: EngineOp.TS_GET_BARTER_MOD },
    gdialog_mod_barter: { opcode: EngineOp.GDIALOG_MOD_BARTER },
    gdialog_set_barter_mod: { opcode: EngineOp.GDIALOG_SET_BARTER_MOD },
    get_array: { opcode: EngineOp.TS_GET_ARRAY },
    get_attack_type: { opcode: EngineOp.TS_GET_ATTACK_TYPE },
    get_available_skill_points: { opcode: EngineOp.TS_GET_AVAILABLE_SKILL_POINTS },
    get_bodypart_hit_modifier: { opcode: EngineOp.TS_GET_BODYPART_HIT_MODIFIER },
    get_critical_table: { opcode: EngineOp.TS_GET_CRITICAL_TABLE },
    get_critter_base_stat: { opcode: EngineOp.TS_GET_CRITTER_BASE_STAT },
    get_critter_current_ap: { opcode: EngineOp.TS_GET_CRITTER_AP },
    get_critter_extra_stat: { opcode: EngineOp.TS_GET_CRITTER_EXTRA_STAT },
    get_critter_skill_points: { opcode: EngineOp.TS_GET_CRITTER_SKILL_POINTS },
    get_critter_stat: { opcode: EngineOp.GET_CRITTER_STAT },
    get_day: { opcode: EngineOp.GET_DAY },
    get_game_mode: { opcode: EngineOp.TS_GET_GAME_MODE },
    get_ini_setting: { opcode: EngineOp.TS_GET_INI_SETTING },
    get_ini_string: { opcode: EngineOp.TS_GET_INI_STRING },
    get_kill_counter: { opcode: EngineOp.TS_GET_KILL_COUNTER },
    get_last_attacker: { opcode: EngineOp.TS_GET_LAST_ATTACKER },
    get_last_target: { opcode: EngineOp.TS_GET_LAST_TARGET },
    get_light_level: { opcode: EngineOp.TS_GET_LIGHT_LEVEL },
    get_month: { opcode: EngineOp.GET_MONTH },
    get_mouse_buttons: { opcode: EngineOp.TS_GET_MOUSE_BUTTONS },
    get_mouse_x: { opcode: EngineOp.TS_GET_MOUSE_X },
    get_mouse_y: { opcode: EngineOp.TS_GET_MOUSE_Y },
    get_npc_level: { opcode: EngineOp.TS_GET_NPC_LEVEL },
    get_pc_base_stat: { opcode: EngineOp.TS_GET_PC_BASE_STAT },
    get_pc_extra_stat: { opcode: EngineOp.TS_GET_PC_EXTRA_STAT },
    get_pc_stat: { opcode: EngineOp.GET_PC_STAT },
    get_perk_available: { opcode: EngineOp.TS_GET_PERK_AVAILABLE },
    get_perk_owed: { opcode: EngineOp.TS_GET_PERK_OWED },
    get_poison: { opcode: EngineOp.GET_POISON },
    get_proto_data: { opcode: EngineOp.TS_GET_PROTO_DATA },
    get_screen_height: { opcode: EngineOp.TS_GET_SCREEN_HEIGHT },
    get_screen_width: { opcode: EngineOp.TS_GET_SCREEN_WIDTH },
    get_script: { opcode: EngineOp.TS_GET_SCRIPT },
    get_sfall_arg: { opcode: EngineOp.TS_GET_SFALL_ARG },
    get_sfall_args: { opcode: EngineOp.TS_GET_SFALL_ARGS },
    get_sfall_global_float: { opcode: EngineOp.TS_GET_SFALL_GLOBAL_FLOAT },
    get_sfall_global_int: { opcode: EngineOp.TS_GET_SFALL_GLOBAL_INT },
    get_shader_texture: { opcode: EngineOp.TS_GET_SHADER_TEXTURE },
    get_shader_version: { opcode: EngineOp.TS_GET_SHADER_VERSION },
    get_tile_fid: { opcode: EngineOp.TS_TILE_PID },
    get_unspent_ap_bonus: { opcode: EngineOp.TS_GET_UNSPENT_AP_BONUS },
    get_unspent_ap_perk_bonus: { opcode: EngineOp.TS_GET_UNSPENT_AP_EBONUS },
    get_uptime: { opcode: EngineOp.TS_GET_UPTIME },
    get_viewport_x: { opcode: EngineOp.TS_GET_VIEWPORT_X },
    get_viewport_y: { opcode: EngineOp.TS_GET_VIEWPORT_Y },
    get_weapon_ammo_count: { opcode: EngineOp.TS_GET_WEAPON_AMMO_COUNT },
    get_weapon_ammo_pid: { opcode: EngineOp.TS_GET_WEAPON_AMMO_PID },
    get_window_under_mouse: { opcode: EngineOp.TS_GET_WINDOW_UNDER_MOUSE },
    get_world_map_x_pos: { opcode: EngineOp.TS_GET_WORLD_MAP_X_POS },
    get_world_map_y_pos: { opcode: EngineOp.TS_GET_WORLD_MAP_Y_POS },
    get_year: { opcode: EngineOp.TS_GET_YEAR },
    gfade_in: { opcode: EngineOp.GFADE_IN },
    gfade_out: { opcode: EngineOp.GFADE_OUT },
    giq_option: { opcode: EngineOp.GIQ_OPTION },
    give_exp_points: { opcode: EngineOp.GIVE_EXP_POINTS },
    global_var: { opcode: EngineOp.GLOBAL_VAR },
    gotoxy: { opcode: LibOp.GOTOXY },
    graphics_funcs_available: { opcode: EngineOp.TS_GRAPHICS_FUNCS_AVAILABLE },
    gsay_end: { opcode: EngineOp.GSAY_END },
    gsay_message: { opcode: EngineOp.GSAY_MESSAGE },
    gsay_option: { opcode: EngineOp.GSAY_OPTION },
    gsay_reply: { opcode: EngineOp.GSAY_REPLY },
    gsay_start: { opcode: EngineOp.GSAY_START },
    has_fake_perk: { opcode: EngineOp.TS_HAS_FAKE_PERK },
    has_fake_trait: { opcode: EngineOp.TS_HAS_FAKE_TRAIT },
    has_skill: { opcode: EngineOp.HAS_SKILL, popsResult: true },
    has_trait: { opcode: EngineOp.HAS_TRAIT },
    hero_select_win: { opcode: EngineOp.TS_HERO_SELECT_WIN },
    hide_iface_tag: { opcode: EngineOp.TS_HIDE_IFACE_TAG },
    hide_real_perks: { opcode: EngineOp.TS_HIDE_REAL_PERKS },
    hidemouse: { opcode: LibOp.HIDEMOUSE },
    how_much: { opcode: EngineOp.HOW_MUCH },
    in_world_map: { opcode: EngineOp.TS_IN_WORLD_MAP },
    inc_npc_level: { opcode: EngineOp.TS_INC_NPC_LEVEL },
    init_hook: { opcode: EngineOp.TS_INIT_HOOK },
    input_funcs_available: { opcode: EngineOp.TS_INPUT_FUNCS_AVAILABLE },
    inven_cmds: { opcode: EngineOp.INVEN_CMDS },
    inven_unwield: { opcode: EngineOp.INVEN_UNWIELD },
    is_critical: { opcode: EngineOp.IS_CRITICAL },
    is_iface_tag_active: { opcode: EngineOp.TS_IS_IFACE_TAG_ACTIVE },
    is_success: { opcode: EngineOp.IS_SUCCESS },
    item_caps_adjust: { opcode: EngineOp.ITEM_CAPS_ADJUST, popsResult: true },
    item_caps_total: { opcode: EngineOp.ITEM_CAPS_TOTAL },
    jam_lock: { opcode: EngineOp.JAM_LOCK },
    key_pressed: { opcode: EngineOp.TS_KEY_PRESSED },
    kill_critter: { opcode: EngineOp.KILL_CRITTER },
    kill_critter_type: { opcode: EngineOp.KILL_CRITTER_TYPE },
    len_array: { opcode: EngineOp.TS_LEN_ARRAY },
    list_as_array: { opcode: EngineOp.TS_LIST_AS_ARRAY },
    list_begin: { opcode: EngineOp.TS_LIST_BEGIN },
    list_end: { opcode: EngineOp.TS_LIST_END },
    list_next: { opcode: EngineOp.TS_LIST_NEXT },
    load_array: { opcode: EngineOp.TS_LOAD_ARRAY },
    load_map: { opcode: EngineOp.LOAD_MAP },
    load_shader: { opcode: EngineOp.TS_LOAD_SHADER },
    loadpalettetable: { opcode: LibOp.LOADPALETTETABLE },
    local_var: { opcode: EngineOp.LOCAL_VAR },
    log: { opcode: EngineOp.TS_LOG },
    make_daytime: { opcode: EngineOp.MAKE_DAYTIME },
    map_var: { opcode: EngineOp.MAP_VAR },
    mark_area_known: { opcode: EngineOp.MARK_AREA_KNOWN },
    mark_movie_played: { opcode: EngineOp.TS_MARK_MOVIE_PLAYED },
    message_str: { opcode: EngineOp.MESSAGE_STR },
    message_str_game: { opcode: EngineOp.TS_MESSAGE_STR_GAME },
    metarule: { opcode: EngineOp.METARULE, popsResult: true },
    metarule2_explosions: { opcode: EngineOp.TS_EXPLOSIONS_METARULE, popsResult: true },
    metarule3: { opcode: EngineOp.METARULE3, popsResult: true },
    mod_kill_counter: { opcode: EngineOp.TS_MOD_KILL_COUNTER },
    mod_skill_points_per_level: { opcode: EngineOp.TS_MOD_SKILL_POINTS_PER_LEVEL },
    modified_ini: { opcode: EngineOp.TS_MODIFIED_INI },
    mouseshape: { opcode: LibOp.MOUSESHAPE },
    move_obj_inven_to_obj: { opcode: EngineOp.MOVE_OBJ_INVEN_TO_OBJ },
    move_to: { opcode: EngineOp.MOVE_TO, popsResult: true },
    movieflags: { opcode: LibOp.MOVIEFLAGS },
    nb_create_char: { opcode: EngineOp.TS_NB_CREATE_CHAR },
    obj_art_fid: { opcode: EngineOp.OBJ_ART_FID },
    obj_being_used_with: { opcode: EngineOp.OBJ_BEING_USED_WITH },
    obj_blocking_line: { opcode: EngineOp.TS_MAKE_STRAIGHT_PATH },
    obj_blocking_tile: { opcode: EngineOp.TS_OBJ_BLOCKING_AT },
    obj_can_hear_obj: { opcode: EngineOp.OBJ_CAN_HEAR_OBJ },
    obj_can_see_obj: { opcode: EngineOp.OBJ_CAN_SEE_OBJ },
    obj_carrying_pid_obj: { opcode: EngineOp.OBJ_CARRYING_PID_OBJ },
    obj_close: { opcode: EngineOp.OBJ_CLOSE },
    obj_is_carrying_obj: { opcode: EngineOp.TS_OBJ_IS_CARRYING_OBJ },
    obj_is_carrying_obj_pid: { opcode: EngineOp.OBJ_IS_CARRYING_OBJ_PID },
    obj_is_locked: { opcode: EngineOp.OBJ_IS_LOCKED },
    obj_is_open: { opcode: EngineOp.OBJ_IS_OPEN },
    obj_item_subtype: { opcode: EngineOp.OBJ_ITEM_SUBTYPE },
    obj_lock: { opcode: EngineOp.OBJ_LOCK },
    obj_name: { opcode: EngineOp.OBJ_NAME },
    obj_on_screen: { opcode: EngineOp.OBJ_ON_SCREEN },
    obj_open: { opcode: EngineOp.OBJ_OPEN },
    obj_pid: { opcode: EngineOp.OBJ_PID },
    obj_set_light_level: { opcode: EngineOp.OBJ_SET_LIGHT_LEVEL },
    obj_type: { opcode: EngineOp.OBJ_TYPE },
    obj_unlock: { opcode: EngineOp.OBJ_UNLOCK },
    override_map_start: { opcode: EngineOp.OVERRIDE_MAP_START },
    party_add: { opcode: EngineOp.PARTY_ADD },
    party_member_list: { opcode: EngineOp.TS_GET_PARTY_MEMBERS },
    party_member_obj: { opcode: EngineOp.PARTY_MEMBER_OBJ },
    party_remove: { opcode: EngineOp.PARTY_REMOVE },
    path_find_to: { opcode: EngineOp.TS_PATH_FIND },
    perk_add_mode: { opcode: EngineOp.TS_PERK_ADD_MODE },
    pickup_obj: { opcode: EngineOp.PICKUP_OBJ },
    play_gmovie: { opcode: EngineOp.PLAY_GMOVIE },
    play_sfall_sound: { opcode: EngineOp.TS_PLAY_SFALL_SOUND },
    play_sfx: { opcode: EngineOp.PLAY_SFX },
    playmovie: { opcode: LibOp.PLAYMOVIE },
    playmoviealpha: { opcode: LibOp.PLAYMOVIEALPHA },
    playmoviealpharect: { opcode: LibOp.PLAYMOVIEALPHARECT },
    playmovierect: { opcode: LibOp.PLAYMOVIERECT },
    poison: { opcode: EngineOp.POISON },
    print: { opcode: LibOp.PRINT },
    printrect: { opcode: LibOp.PRINTRECT },
    proto_data: { opcode: EngineOp.PROTO_DATA },
    radiation_dec: { opcode: EngineOp.RADIATION_DEC },
    radiation_inc: { opcode: EngineOp.RADIATION_INC },
    random: { opcode: EngineOp.RANDOM },
    reaction_influence: { opcode: EngineOp.REACTION_INFLUENCE },
    read_byte: { opcode: EngineOp.TS_READ_BYTE },
    read_int: { opcode: EngineOp.TS_READ_INT },
    read_short: { opcode: EngineOp.TS_READ_SHORT },
    read_string: { opcode: EngineOp.TS_READ_STRING },
    refresh_pc_art: { opcode: EngineOp.TS_REFRESH_PC_ART },
    refreshmouse: { opcode: LibOp.REFRESHMOUSE },
    reg_anim_animate: { opcode: EngineOp.REG_ANIM_ANIMATE },
    reg_anim_animate_and_hide: { opcode: EngineOp.TS_REG_ANIM_ANIMATE_AND_HIDE },
    reg_anim_animate_forever: { opcode: EngineOp.REG_ANIM_ANIMATE_FOREVER },
    reg_anim_animate_reverse: { opcode: EngineOp.REG_ANIM_ANIMATE_REVERSE },
    reg_anim_callback: { opcode: EngineOp.TS_REG_ANIM_CALLBACK },
    reg_anim_change_fid: { opcode: EngineOp.TS_REG_ANIM_CHANGE_FID },
    reg_anim_combat_check: { opcode: EngineOp.TS_REG_ANIM_COMBAT_CHECK },
    reg_anim_destroy: { opcode: EngineOp.TS_REG_ANIM_DESTROY },
    reg_anim_light: { opcode: EngineOp.TS_REG_ANIM_LIGHT },
    reg_anim_obj_move_to_obj: { opcode: EngineOp.REG_ANIM_OBJ_MOVE_TO_OBJ },
    reg_anim_obj_move_to_tile: { opcode: EngineOp.REG_ANIM_OBJ_MOVE_TO_TILE },
    reg_anim_obj_run_to_obj: { opcode: EngineOp.REG_ANIM_OBJ_RUN_TO_OBJ },
    reg_anim_obj_run_to_tile: { opcode: EngineOp.REG_ANIM_OBJ_RUN_TO_TILE },
    reg_anim_play_sfx: { opcode: EngineOp.REG_ANIM_PLAY_SFX },
    reg_anim_take_out: { opcode: EngineOp.TS_REG_ANIM_TAKE_OUT },
    reg_anim_turn_towards: { opcode: EngineOp.TS_REG_ANIM_TURN_TOWARDS },
    register_hook: { opcode: EngineOp.TS_REGISTER_HOOK },
    register_hook_proc: { opcode: EngineOp.TS_REGISTER_HOOK_PROC },
    register_hook_proc_spec: { opcode: EngineOp.TS_REGISTER_HOOK_PROC2 },
    remove_attacker_knockback: { opcode: EngineOp.TS_REMOVE_ATTACKER_KNOCKBACK },
    remove_script: { opcode: EngineOp.TS_REMOVE_SCRIPT },
    remove_target_knockback: { opcode: EngineOp.TS_REMOVE_TARGET_KNOCKBACK },
    remove_trait: { opcode: EngineOp.TS_REMOVE_TRAIT },
    remove_weapon_knockback: { opcode: EngineOp.TS_REMOVE_WEAPON_KNOCKBACK },
    reset_critical_table: { opcode: EngineOp.TS_RESET_CRITICAL_TABLE },
    resize_array: { opcode: EngineOp.TS_RESIZE_ARRAY },
    resizewin: { opcode: LibOp.RESIZEWIN },
    resume_game: { opcode: EngineOp.TS_RESUME_GAME },
    rm_mult_objs_from_inven: { opcode: EngineOp.RM_MULT_OBJS_FROM_INVEN },
    rm_obj_from_inven: { opcode: EngineOp.RM_OBJ_FROM_INVEN },
    rm_timer_event: { opcode: EngineOp.RM_TIMER_EVENT },
    roll_dice: { opcode: EngineOp.ROLL_DICE, popsResult: true },
    roll_vs_skill: { opcode: EngineOp.ROLL_VS_SKILL, popsResult: true },
    rotation_to_tile: { opcode: EngineOp.ROTATION_TO_TILE },
    round: { opcode: EngineOp.TS_ROUND },
    running_burning_guy: { opcode: EngineOp.RUNNING_BURNING_GUY },
    save_array: { opcode: EngineOp.TS_SAVE_ARRAY },
    sayborder: { opcode: LibOp.SAYBORDER },
    sayend: { opcode: LibOp.SAYEND },
    saygetlastpos: { opcode: LibOp.SAYGETLASTPOS },
    saygotoreply: { opcode: LibOp.SAYGOTOREPLY },
    saymessage: { opcode: LibOp.SAYMESSAGE },
    saymessagetimeout: { opcode: LibOp.SAYMESSAGETIMEOUT },
    sayoption: { opcode: LibOp.SAYOPTION },
    sayoptioncolor: { opcode: LibOp.SAYOPTIONCOLOR },
    sayoptionflags: { opcode: LibOp.SAYOPTIONFLAGS },
    sayoptionwindow: { opcode: LibOp.SAYOPTIONWINDOW },
    sayquit: { opcode: LibOp.SAYQUIT },
    sayreply: { opcode: LibOp.SAYREPLY },
    sayreplycolor: { opcode: LibOp.SAYREPLYCOLOR },
    sayreplyflags: { opcode: LibOp.SAYREPLYFLAGS },
    sayreplytitle: { opcode: LibOp.SAYREPLYTITLE },
    sayreplywindow: { opcode: LibOp.SAYREPLYWINDOW },
    sayrestart: { opcode: LibOp.SAYRESTART },
    sayscrolldown: { opcode: LibOp.SAYSCROLLDOWN },
    sayscrollup: { opcode: LibOp.SAYSCROLLUP },
    saysetspacing: { opcode: LibOp.SAYSETSPACING },
    saystart: { opcode: LibOp.SAYSTART },
    saystartpos: { opcode: LibOp.SAYSTARTPOS },
    scalewin: { opcode: LibOp.SCALEWIN },
    scan_array: { opcode: EngineOp.TS_SCAN_ARRAY },
    scr_return: { opcode: EngineOp.SCR_RETURN },
    script_action: { opcode: EngineOp.SCRIPT_ACTION },
    script_overrides: { opcode: EngineOp.SCRIPT_OVERRIDES },
    selectfilelist: { opcode: LibOp.SELECTFILELIST },
    selectwin: { opcode: LibOp.SELECTWIN },
    self_obj: { opcode: EngineOp.SELF_OBJ },
    set_array: { opcode: EngineOp.TS_SET_ARRAY },
    set_attacker_knockback: { opcode: EngineOp.TS_SET_ATTACKER_KNOCKBACK },
    set_available_skill_points: { opcode: EngineOp.TS_SET_AVAILABLE_SKILL_POINTS },
    set_base_hit_chance_mod: { opcode: EngineOp.TS_SET_BASE_HIT_CHANCE_MOD },
    set_base_pickpocket_mod: { opcode: EngineOp.TS_SET_BASE_PICKPOCKET_MOD },
    set_base_skill_mod: { opcode: EngineOp.TS_SET_BASE_SKILL_MOD },
    set_bodypart_hit_modifier: { opcode: EngineOp.TS_SET_BODYPART_HIT_MODIFIER },
    set_car_current_town: { opcode: EngineOp.TS_SET_CAR_CURRENT_TOWN },
    set_critical_table: { opcode: EngineOp.TS_SET_CRITICAL_TABLE },
    set_critter_base_stat: { opcode: EngineOp.TS_SET_CRITTER_BASE_STAT },
    set_critter_burst_disable: { opcode: EngineOp.TS_SET_CRITTER_BURST_DISABLE },
    set_critter_current_ap: { opcode: EngineOp.TS_SET_CRITTER_AP },
    set_critter_extra_stat: { opcode: EngineOp.TS_SET_CRITTER_EXTRA_STAT },
    set_critter_hit_chance_mod: { opcode: EngineOp.TS_SET_CRITTER_HIT_CHANCE_MOD },
    set_critter_pickpocket_mod: { opcode: EngineOp.TS_SET_CRITTER_PICKPOCKET_MOD },
    set_critter_skill_mod: { opcode: EngineOp.TS_SET_CRITTER_SKILL_MOD },
    set_critter_skill_points: { opcode: EngineOp.TS_SET_CRITTER_SKILL_POINTS },
    set_critter_stat: { opcode: EngineOp.SET_CRITTER_STAT, popsResult: true },
    set_df_model: { opcode: EngineOp.TS_SET_DF_MODEL },
    set_dm_model: { opcode: EngineOp.TS_SET_DM_MODEL },
    set_eax_environment: { opcode: EngineOp.TS_SET_EAX_ENVIRONMENT },
    set_exit_grids: { opcode: EngineOp.SET_EXIT_GRIDS },
    set_fake_perk: { opcode: EngineOp.TS_SET_FAKE_PERK },
    set_fake_trait: { opcode: EngineOp.TS_SET_FAKE_TRAIT },
    set_global_script_repeat: { opcode: EngineOp.TS_SET_GLOBAL_SCRIPT_REPEAT },
    set_global_script_type: { opcode: EngineOp.TS_SET_GLOBAL_SCRIPT_TYPE },
    set_global_var: { opcode: EngineOp.SET_GLOBAL_VAR },
    set_hero_race: { opcode: EngineOp.TS_SET_HERO_RACE },
    set_hero_style: { opcode: EngineOp.TS_SET_HERO_STYLE },
    set_hit_chance_max: { opcode: EngineOp.TS_SET_HIT_CHANCE_MAX },
    set_hp_per_level_mod: { opcode: EngineOp.TS_SET_HP_LEVEL_MOD },
    set_inven_ap_cost: { opcode: EngineOp.TS_SET_INVEN_AP_COST },
    set_light_level: { opcode: EngineOp.SET_LIGHT_LEVEL },
    set_local_var: { opcode: EngineOp.SET_LOCAL_VAR },
    set_map_music: { opcode: EngineOp.SET_MAP_MUSIC },
    set_map_start: { opcode: EngineOp.SET_MAP_START },
    set_map_time_multi: { opcode: EngineOp.TS_SET_MAP_TIME_MULTI },
    set_map_var: { opcode: EngineOp.SET_MAP_VAR },
    set_movie_path: { opcode: EngineOp.TS_SET_MOVIE_PATH },
    set_npc_stat_max: { opcode: EngineOp.TS_SET_NPC_STAT_MAX },
    set_npc_stat_min: { opcode: EngineOp.TS_SET_NPC_STAT_MIN },
    set_obj_visibility: { opcode: EngineOp.SET_OBJ_VISIBILITY },
    set_palette: { opcode: EngineOp.TS_SET_PALETTE },
    set_pc_base_stat: { opcode: EngineOp.TS_SET_PC_BASE_STAT },
    set_pc_extra_stat: { opcode: EngineOp.TS_SET_PC_EXTRA_STAT },
    set_pc_stat_max: { opcode: EngineOp.TS_SET_PC_STAT_MAX },
    set_pc_stat_min: { opcode: EngineOp.TS_SET_PC_STAT_MIN },
    set_perk_agl: { opcode: EngineOp.TS_SET_PERK_AGL },
    set_perk_chr: { opcode: EngineOp.TS_SET_PERK_CHR },
    set_perk_desc: { opcode: EngineOp.TS_SET_PERK_DESC },
    set_perk_end: { opcode: EngineOp.TS_SET_PERK_END },
    set_perk_freq: { opcode: EngineOp.TS_SET_PERK_FREQ },
    set_perk_image: { opcode: EngineOp.TS_SET_PERK_IMAGE },
    set_perk_int: { opcode: EngineOp.TS_SET_PERK_INT },
    set_perk_lck: { opcode: EngineOp.TS_SET_PERK_LCK },
    set_perk_level: { opcode: EngineOp.TS_SET_PERK_LEVEL },
    set_perk_level_mod: { opcode: EngineOp.TS_SET_PERK_LEVEL_MOD },
    set_perk_name: { opcode: EngineOp.TS_SET_PERK_NAME },
    set_perk_owed: { opcode: EngineOp.TS_SET_PERK_OWED },
    set_perk_per: { opcode: EngineOp.TS_SET_PERK_PER },
    set_perk_ranks: { opcode: EngineOp.TS_SET_PERK_RANKS },
    set_perk_skill1: { opcode: EngineOp.TS_SET_PERK_SKILL1 },
    set_perk_skill2: { opcode: EngineOp.TS_SET_PERK_SKILL2 },
    set_perk_skill2_mag: { opcode: EngineOp.TS_SET_PERK_SKILL2_MAG },
    set_perk_stat: { opcode: EngineOp.TS_SET_PERK_STAT },
    set_perk_stat_mag: { opcode: EngineOp.TS_SET_PERK_STAT_MAG },
    set_perk_str: { opcode: EngineOp.TS_SET_PERK_STR },
    set_perk_type: { opcode: EngineOp.TS_SET_PERK_TYPE },
    set_perkbox_title: { opcode: EngineOp.TS_SET_PERKBOX_TITLE },
    set_pickpocket_max: { opcode: EngineOp.TS_SET_PICKPOCKET_MAX },
    set_pipboy_available: { opcode: EngineOp.TS_SET_PIPBOY_AVAILABLE },
    set_proto_data: { opcode: EngineOp.TS_SET_PROTO_DATA },
    set_pyromaniac_mod: { opcode: EngineOp.TS_SET_PYROMANIAC_MOD },
    set_script: { opcode: EngineOp.TS_SET_SCRIPT },
    set_selectable_perk: { opcode: EngineOp.TS_SET_SELECTABLE_PERK },
    set_self: { opcode: EngineOp.TS_SET_SELF },
    set_sfall_arg: { opcode: EngineOp.TS_SET_SFALL_ARG },
    set_sfall_global: { opcode: EngineOp.TS_SET_SFALL_GLOBAL },
    set_sfall_return: { opcode: EngineOp.TS_SET_SFALL_RETURN },
    set_shader_float: { opcode: EngineOp.TS_SET_SHADER_FLOAT },
    set_shader_int: { opcode: EngineOp.TS_SET_SHADER_INT },
    set_shader_mode: { opcode: EngineOp.TS_SET_SHADER_MODE },
    set_shader_texture: { opcode: EngineOp.TS_SET_SHADER_TEXTURE },
    set_shader_vector: { opcode: EngineOp.TS_SET_SHADER_VECTOR },
    set_skill_max: { opcode: EngineOp.TS_SET_SKILL_MAX },
    set_stat_max: { opcode: EngineOp.TS_SET_STAT_MAX },
    set_stat_min: { opcode: EngineOp.TS_SET_STAT_MIN },
    set_swiftlearner_mod: { opcode: EngineOp.TS_SET_SWIFTLEARNER_MOD },
    set_target_knockback: { opcode: EngineOp.TS_SET_TARGET_KNOCKBACK },
    set_unspent_ap_bonus: { opcode: EngineOp.TS_SET_UNSPENT_AP_BONUS },
    set_unspent_ap_perk_bonus: { opcode: EngineOp.TS_SET_UNSPENT_AP_EBONUS },
    set_viewport_x: { opcode: EngineOp.TS_SET_VIEWPORT_X },
    set_viewport_y: { opcode: EngineOp.TS_SET_VIEWPORT_Y },
    set_weapon_ammo_count: { opcode: EngineOp.TS_SET_WEAPON_AMMO_COUNT },
    set_weapon_ammo_pid: { opcode: EngineOp.TS_SET_WEAPON_AMMO_PID },
    set_weapon_knockback: { opcode: EngineOp.TS_SET_WEAPON_KNOCKBACK },
    set_world_map_pos: { opcode: EngineOp.TS_SET_WORLD_MAP_POS },
    set_xp_mod: { opcode: EngineOp.TS_SET_XP_MOD },
    setfont: { opcode: LibOp.SETFONT },
    setglobalmousefunc: { opcode: LibOp.SETGLOBALMOUSEFUNC },
    sethighlightcolor: { opcode: LibOp.SETHIGHLIGHTCOLOR },
    setoneoptpause: { opcode: LibOp.SETONEOPTPAUSE },
    settextcolor: { opcode: LibOp.SETTEXTCOLOR },
    settextflags: { opcode: LibOp.SETTEXTFLAGS },
    sfall_func0: { opcode: EngineOp.TS_SFALL_METARULE0, popsResult: true },
    sfall_func1: { opcode: EngineOp.TS_SFALL_METARULE1, popsResult: true },
    sfall_func2: { opcode: EngineOp.TS_SFALL_METARULE2, popsResult: true },
    sfall_func3: { opcode: EngineOp.TS_SFALL_METARULE3, popsResult: true },
    sfall_func4: { opcode: EngineOp.TS_SFALL_METARULE4, popsResult: true },
    sfall_func5: { opcode: EngineOp.TS_SFALL_METARULE5, popsResult: true },
    sfall_func6: { opcode: EngineOp.TS_SFALL_METARULE6, popsResult: true },
    sfall_func7: { opcode: EngineOp.TS_SFALL_METARULE7, popsResult: true },
    sfall_func8: { opcode: EngineOp.TS_SFALL_METARULE8, popsResult: true },
    sfall_ver_build: { opcode: EngineOp.TS_SFALL_VER_BUILD },
    sfall_ver_major: { opcode: EngineOp.TS_SFALL_VER_MAJOR },
    sfall_ver_minor: { opcode: EngineOp.TS_SFALL_VER_MINOR },
    sfx_build_ambient_name: { opcode: EngineOp.SFX_BUILD_AMBIENT_NAME },
    sfx_build_char_name: { opcode: EngineOp.SFX_BUILD_CHAR_NAME },
    sfx_build_interface_name: { opcode: EngineOp.SFX_BUILD_INTERFACE_NAME },
    sfx_build_item_name: { opcode: EngineOp.SFX_BUILD_ITEM_NAME },
    sfx_build_open_name: { opcode: EngineOp.SFX_BUILD_OPEN_NAME },
    sfx_build_scenery_name: { opcode: EngineOp.SFX_BUILD_SCENERY_NAME },
    sfx_build_weapon_name: { opcode: EngineOp.SFX_BUILD_WEAPON_NAME },
    show_iface_tag: { opcode: EngineOp.TS_SHOW_IFACE_TAG },
    show_real_perks: { opcode: EngineOp.TS_SHOW_REAL_PERKS },
    showmouse: { opcode: LibOp.SHOWMOUSE },
    showwin: { opcode: LibOp.SHOWWIN },
    signalnamed: { opcode: LibOp.SIGNALNAMED },
    sin: { opcode: EngineOp.TS_SIN },
    skill_contest: { opcode: EngineOp.SKILL_CONTEST, popsResult: true },
    sneak_success: { opcode: EngineOp.TS_SNEAK_SUCCESS },
    sounddelete: { opcode: LibOp.SOUNDDELETE },
    soundpause: { opcode: LibOp.SOUNDPAUSE },
    soundplay: { opcode: LibOp.SOUNDPLAY },
    soundresume: { opcode: LibOp.SOUNDRESUME },
    soundrewind: { opcode: LibOp.SOUNDREWIND },
    soundstop: { opcode: LibOp.SOUNDSTOP },
    source_obj: { opcode: EngineOp.SOURCE_OBJ },
    sprintf: { opcode: EngineOp.TS_SPRINTF },
    sqrt: { opcode: EngineOp.TS_SQRT },
    start_gdialog: { opcode: EngineOp.START_GDIALOG },
    stop_game: { opcode: EngineOp.TS_STOP_GAME },
    stop_sfall_sound: { opcode: EngineOp.TS_STOP_SFALL_SOUND },
    stopmovie: { opcode: LibOp.STOPMOVIE },
    string_split: { opcode: EngineOp.TS_STRING_SPLIT },
    strlen: { opcode: EngineOp.TS_STRLEN },
    substr: { opcode: EngineOp.TS_SUBSTR },
    tan: { opcode: EngineOp.TS_TAN },
    tap_key: { opcode: EngineOp.TS_TAP_KEY },
    target_obj: { opcode: EngineOp.TARGET_OBJ },
    temp_array: { opcode: EngineOp.TS_TEMP_ARRAY },
    terminate_combat: { opcode: EngineOp.TERMINATE_COMBAT },
    tile_contains_obj_pid: { opcode: EngineOp.TILE_CONTAINS_OBJ_PID },
    tile_contains_pid_obj: { opcode: EngineOp.TILE_CONTAINS_PID_OBJ },
    tile_distance: { opcode: EngineOp.TILE_DISTANCE },
    tile_distance_objs: { opcode: EngineOp.TILE_DISTANCE_OBJS },
    tile_get_objs: { opcode: EngineOp.TS_TILE_GET_OBJECTS },
    tile_in_tile_rect: { opcode: EngineOp.TILE_IN_TILE_RECT },
    tile_is_visible: { opcode: EngineOp.TILE_IS_VISIBLE },
    tile_light: { opcode: EngineOp.TS_TILE_LIGHT },
    tile_num: { opcode: EngineOp.TILE_NUM },
    tile_num_in_direction: { opcode: EngineOp.TILE_NUM_IN_DIRECTION },
    tile_under_cursor: { opcode: EngineOp.TS_TILE_UNDER_CURSOR },
    toggle_active_hand: { opcode: EngineOp.TS_TOGGLE_ACTIVE_HAND },
    tokenize: { opcode: LibOp.TOKENIZE },
    typeof: { opcode: EngineOp.TS_TYPEOF },
    use_obj: { opcode: EngineOp.USE_OBJ },
    use_obj_on_obj: { opcode: EngineOp.USE_OBJ_ON_OBJ },
    using_skill: { opcode: EngineOp.USING_SKILL, popsResult: true },
    wield_obj_critter: { opcode: EngineOp.WIELD_OBJ_CRITTER },
    wm_area_set_pos: { opcode: EngineOp.WM_AREA_SET_POS },
    world_map: { opcode: EngineOp.WORLD_MAP },
    write_string: { opcode: EngineOp.TS_WRITE_STRING },
    write_byte: { opcode: EngineOp.TS_WRITE_BYTE },
    write_int: { opcode: EngineOp.TS_WRITE_INT },
    write_short: { opcode: EngineOp.TS_WRITE_SHORT },
};

/** Fallout 1 spellings for the reused opcode slots, resolved through the one ordered table. */
const FALLOUT1_ONLY: Readonly<Record<string, string>> = {
    animate_jump: "ANIMATE_JUMP",
    barter_asking: "BARTER_ASKING",
    barter_offer: "BARTER_OFFER",
    reaction: "REACTION",
    town_map: "TOWN_MAP",
    turn_off_objs_in_area: "TURN_OFF_OBJS_IN_AREA",
    turn_on_objs_in_area: "TURN_ON_OBJS_IN_AREA",
};

/** Looks up an engine function by its source spelling for the target game. */
export function engineFunction(name: string, game: 1 | 2 = 2): EngineFunction | undefined {
    if (game === 1) {
        const opcodeName = FALLOUT1_ONLY[name];
        const opcode = opcodeName === undefined ? undefined : FALLOUT1_OPCODES[opcodeName];
        if (opcode !== undefined) return { opcode };
    }
    return ENGINE_FUNCTIONS[name];
}
