/**
 * Library and engine opcode tables.
 *
 * The interpreter's opcode space is one contiguous run: the 76 core instructions in `opcodes.ts`,
 * then 85 library opcodes, then 481 engine ("extended") opcodes. Only the core set is instruction
 * semantics; everything here is a named engine function dispatched by number, so a call site pushes its
 * arguments in order and then the opcode.
 *
 * As with the core table, order is the contract and the numbers are derived from position - the numbering
 * is frozen because changing it would invalidate every compiled script in existence.
 *
 * Fallout 1 and Fallout 2 share the numbering exactly: the two builds differ at only 7 positions, and at
 * each of those the slot holds a DIFFERENT FUNCTION under the same number rather than shifting anything
 * after it. So one table plus a small per-position override is the whole difference, and an opcode number
 * decoded without knowing the target game is still unambiguous as a number - just not as a name.
 */

import { O_OPERATOR } from "./opcodes";

/** Count of core opcodes; the library table starts immediately after them. */
const CORE_COUNT = 76;

// Order is the contract. Do not sort, insert, or remove.
const LIB_OPCODES = [
    "SAYQUIT",
    "SAYEND",
    "SAYSTART",
    "SAYSTARTPOS",
    "SAYREPLYTITLE",
    "SAYGOTOREPLY",
    "SAYREPLY",
    "SAYOPTION",
    "SAYMESSAGE",
    "SAYREPLYWINDOW",
    "SAYOPTIONWINDOW",
    "SAYBORDER",
    "SAYSCROLLUP",
    "SAYSCROLLDOWN",
    "SAYSETSPACING",
    "SAYOPTIONCOLOR",
    "SAYREPLYCOLOR",
    "SAYRESTART",
    "SAYGETLASTPOS",
    "SAYREPLYFLAGS",
    "SAYOPTIONFLAGS",
    "SAYMESSAGETIMEOUT",
    "CREATEWIN",
    "DELETEWIN",
    "SELECTWIN",
    "RESIZEWIN",
    "SCALEWIN",
    "SHOWWIN",
    "FILLWIN",
    "FILLRECT",
    "FILLWIN3X3",
    "DISPLAY",
    "DISPLAYGFX",
    "DISPLAYRAW",
    "LOADPALETTETABLE",
    "FADEIN",
    "FADEOUT",
    "GOTOXY",
    "PRINT",
    "FORMAT",
    "PRINTRECT",
    "SETFONT",
    "SETTEXTFLAGS",
    "SETTEXTCOLOR",
    "SETHIGHLIGHTCOLOR",
    "STOPMOVIE",
    "PLAYMOVIE",
    "MOVIEFLAGS",
    "PLAYMOVIERECT",
    "PLAYMOVIEALPHA",
    "PLAYMOVIEALPHARECT",
    "ADDREGION",
    "ADDREGIONFLAG",
    "ADDREGIONPROC",
    "ADDREGIONRIGHTPROC",
    "DELETEREGION",
    "ACTIVATEREGION",
    "CHECKREGION",
    "ADDBUTTON",
    "ADDBUTTONTEXT",
    "ADDBUTTONFLAG",
    "ADDBUTTONGFX",
    "ADDBUTTONPROC",
    "ADDBUTTONRIGHTPROC",
    "DELETEBUTTON",
    "HIDEMOUSE",
    "SHOWMOUSE",
    "MOUSESHAPE",
    "REFRESHMOUSE",
    "SETGLOBALMOUSEFUNC",
    "ADDNAMEDEVENT",
    "ADDNAMEDHANDLER",
    "CLEARNAMED",
    "SIGNALNAMED",
    "ADDKEY",
    "DELETEKEY",
    "SOUNDPLAY",
    "SOUNDPAUSE",
    "SOUNDRESUME",
    "SOUNDSTOP",
    "SOUNDREWIND",
    "SOUNDDELETE",
    "SETONEOPTPAUSE",
    "SELECTFILELIST",
    "TOKENIZE",
] as const;

/** Engine opcodes as Fallout 2 names; see FALLOUT1_OVERRIDES for the positions that differ. */
const ENGINE_OPCODES = [
    "GIVE_EXP_POINTS",
    "SCR_RETURN",
    "PLAY_SFX",
    "OBJ_NAME",
    "SFX_BUILD_OPEN_NAME",
    "GET_PC_STAT",
    "TILE_CONTAINS_PID_OBJ",
    "SET_MAP_START",
    "OVERRIDE_MAP_START",
    "HAS_SKILL",
    "USING_SKILL",
    "ROLL_VS_SKILL",
    "SKILL_CONTEST",
    "DO_CHECK",
    "IS_SUCCESS",
    "IS_CRITICAL",
    "HOW_MUCH",
    "MARK_AREA_KNOWN",
    "REACTION_INFLUENCE",
    "RANDOM",
    "ROLL_DICE",
    "MOVE_TO",
    "CREATE_OBJECT_SID",
    "DISPLAY_MSG",
    "SCRIPT_OVERRIDES",
    "OBJ_IS_CARRYING_OBJ_PID",
    "TILE_CONTAINS_OBJ_PID",
    "SELF_OBJ",
    "SOURCE_OBJ",
    "TARGET_OBJ",
    "DUDE_OBJ",
    "OBJ_BEING_USED_WITH",
    "LOCAL_VAR",
    "SET_LOCAL_VAR",
    "MAP_VAR",
    "SET_MAP_VAR",
    "GLOBAL_VAR",
    "SET_GLOBAL_VAR",
    "SCRIPT_ACTION",
    "OBJ_TYPE",
    "OBJ_ITEM_SUBTYPE",
    "GET_CRITTER_STAT",
    "SET_CRITTER_STAT",
    "ANIMATE_STAND_OBJ",
    "ANIMATE_STAND_REVERSE_OBJ",
    "ANIMATE_MOVE_OBJ_TO_TILE",
    "TILE_IN_TILE_RECT",
    "ATTACK_COMPLEX",
    "MAKE_DAYTIME",
    "TILE_DISTANCE",
    "TILE_DISTANCE_OBJS",
    "TILE_NUM",
    "TILE_NUM_IN_DIRECTION",
    "PICKUP_OBJ",
    "DROP_OBJ",
    "ADD_OBJ_TO_INVEN",
    "RM_OBJ_FROM_INVEN",
    "WIELD_OBJ_CRITTER",
    "USE_OBJ",
    "OBJ_CAN_SEE_OBJ",
    "ATTACK",
    "START_GDIALOG",
    "END_DIALOGUE",
    "DIALOGUE_REACTION",
    "METARULE3",
    "SET_MAP_MUSIC",
    "SET_OBJ_VISIBILITY",
    "LOAD_MAP",
    "WM_AREA_SET_POS",
    "SET_EXIT_GRIDS",
    "ANIM_BUSY",
    "CRITTER_HEAL",
    "SET_LIGHT_LEVEL",
    "GAME_TIME",
    "GAME_TIME_IN_SECONDS",
    "ELEVATION",
    "KILL_CRITTER",
    "KILL_CRITTER_TYPE",
    "CRITTER_DMG",
    "ADD_TIMER_EVENT",
    "RM_TIMER_EVENT",
    "GAME_TICKS",
    "HAS_TRAIT",
    "DESTROY_OBJECT",
    "OBJ_CAN_HEAR_OBJ",
    "GAME_TIME_HOUR",
    "FIXED_PARAM",
    "TILE_IS_VISIBLE",
    "DIALOGUE_SYSTEM_ENTER",
    "ACTION_BEING_USED",
    "CRITTER_STATE",
    "GAME_TIME_ADVANCE",
    "RADIATION_INC",
    "RADIATION_DEC",
    "CRITTER_ATTEMPT_PLACEMENT",
    "OBJ_PID",
    "CUR_MAP_INDEX",
    "CRITTER_ADD_TRAIT",
    "CRITTER_RM_TRAIT",
    "PROTO_DATA",
    "MESSAGE_STR",
    "CRITTER_INVEN_OBJ",
    "OBJ_SET_LIGHT_LEVEL",
    "WORLD_MAP",
    "INVEN_CMDS",
    "FLOAT_MSG",
    "METARULE",
    "ANIM",
    "OBJ_CARRYING_PID_OBJ",
    "REG_ANIM_FUNC",
    "REG_ANIM_ANIMATE",
    "REG_ANIM_ANIMATE_REVERSE",
    "REG_ANIM_OBJ_MOVE_TO_OBJ",
    "REG_ANIM_OBJ_RUN_TO_OBJ",
    "REG_ANIM_OBJ_MOVE_TO_TILE",
    "REG_ANIM_OBJ_RUN_TO_TILE",
    "PLAY_GMOVIE",
    "ADD_MULT_OBJS_TO_INVEN",
    "RM_MULT_OBJS_FROM_INVEN",
    "GET_MONTH",
    "GET_DAY",
    "EXPLOSION",
    "DAYS_SINCE_VISITED",
    "GSAY_START",
    "GSAY_END",
    "GSAY_REPLY",
    "GSAY_OPTION",
    "GSAY_MESSAGE",
    "GIQ_OPTION",
    "POISON",
    "GET_POISON",
    "PARTY_ADD",
    "PARTY_REMOVE",
    "REG_ANIM_ANIMATE_FOREVER",
    "CRITTER_INJURE",
    "COMBAT_IS_INITIALIZED",
    "GDIALOG_MOD_BARTER",
    "DIFFICULTY_LEVEL",
    "RUNNING_BURNING_GUY",
    "INVEN_UNWIELD",
    "OBJ_IS_LOCKED",
    "OBJ_LOCK",
    "OBJ_UNLOCK",
    "OBJ_IS_OPEN",
    "OBJ_OPEN",
    "OBJ_CLOSE",
    "GAME_UI_DISABLE",
    "GAME_UI_ENABLE",
    "GAME_UI_IS_DISABLED",
    "GFADE_OUT",
    "GFADE_IN",
    "ITEM_CAPS_TOTAL",
    "ITEM_CAPS_ADJUST",
    "ANIM_ACTION_FRAME",
    "REG_ANIM_PLAY_SFX",
    "CRITTER_MOD_SKILL",
    "SFX_BUILD_CHAR_NAME",
    "SFX_BUILD_AMBIENT_NAME",
    "SFX_BUILD_INTERFACE_NAME",
    "SFX_BUILD_ITEM_NAME",
    "SFX_BUILD_WEAPON_NAME",
    "SFX_BUILD_SCENERY_NAME",
    "ATTACK_SETUP",
    "DESTROY_MULT_OBJS",
    "USE_OBJ_ON_OBJ",
    "ENDGAME_SLIDESHOW",
    "MOVE_OBJ_INVEN_TO_OBJ",
    "ENDGAME_MOVIE",
    "OBJ_ART_FID",
    "ART_ANIM",
    "PARTY_MEMBER_OBJ",
    "ROTATION_TO_TILE",
    "JAM_LOCK",
    "GDIALOG_SET_BARTER_MOD",
    "COMBAT_DIFFICULTY",
    "OBJ_ON_SCREEN",
    "CRITTER_IS_FLEEING",
    "CRITTER_SET_FLEE_STATE",
    "TERMINATE_COMBAT",
    "DEBUG_MSG",
    "CRITTER_STOP_ATTACKING",
    "TS_READ_BYTE",
    "TS_READ_SHORT",
    "TS_READ_INT",
    "TS_READ_STRING",
    "TS_SET_PC_BASE_STAT",
    "TS_SET_PC_EXTRA_STAT",
    "TS_GET_PC_BASE_STAT",
    "TS_GET_PC_EXTRA_STAT",
    "TS_SET_CRITTER_BASE_STAT",
    "TS_SET_CRITTER_EXTRA_STAT",
    "TS_GET_CRITTER_BASE_STAT",
    "TS_GET_CRITTER_EXTRA_STAT",
    "TS_TAP_KEY",
    "TS_GET_YEAR",
    "TS_GAME_LOADED",
    "TS_GRAPHICS_FUNCS_AVAILABLE",
    "TS_LOAD_SHADER",
    "TS_FREE_SHADER",
    "TS_ACTIVATE_SHADER",
    "TS_DEACTIVATE_SHADER",
    "TS_SET_GLOBAL_SCRIPT_REPEAT",
    "TS_INPUT_FUNCS_AVAILABLE",
    "TS_KEY_PRESSED",
    "TS_SET_SHADER_INT",
    "TS_SET_SHADER_FLOAT",
    "TS_SET_SHADER_VECTOR",
    "TS_IN_WORLD_MAP",
    "TS_FORCE_ENCOUNTER",
    "TS_SET_WORLD_MAP_POS",
    "TS_GET_WORLD_MAP_X_POS",
    "TS_GET_WORLD_MAP_Y_POS",
    "TS_SET_DM_MODEL",
    "TS_SET_DF_MODEL",
    "TS_SET_MOVIE_PATH",
    "TS_SET_PERK_IMAGE",
    "TS_SET_PERK_RANKS",
    "TS_SET_PERK_LEVEL",
    "TS_SET_PERK_STAT",
    "TS_SET_PERK_STAT_MAG",
    "TS_SET_PERK_SKILL1",
    "TS_SET_PERK_SKIL",
    "TS_SET_PERK_TYPE",
    "TS_SET_PERK_SKILL2",
    "TS_SET_PERK_SKILL2_MAG",
    "TS_SET_PERK_STR",
    "TS_SET_PERK_PER",
    "TS_SET_PERK_END",
    "TS_SET_PERK_CHR",
    "TS_SET_PERK_INT",
    "TS_SET_PERK_AGL",
    "TS_SET_PERK_LCK",
    "TS_SET_PERK_NAME",
    "TS_SET_PERK_DESC",
    "TS_SET_PIPBOY_AVAILABLE",
    "TS_GET_KILL_COUNTER",
    "TS_MOD_KILL_COUNTER",
    "TS_GET_PERK_OWED",
    "TS_SET_PERK_OWED",
    "TS_GET_PERK_AVAILABLE",
    "TS_GET_CRITTER_AP",
    "TS_SET_CRITTER_AP",
    "TS_GET_ACTIVE_HAND",
    "TS_TOGGLE_ACTIVE_HAND",
    "TS_SET_WEAPON_KNOCKBACK",
    "TS_SET_TARGET_KNOCKBACK",
    "TS_SET_ATTACKER_KNOCKBACK",
    "TS_REMOVE_WEAPON_KNOCKBACK",
    "TS_REMOVE_TARGET_KNOCKBACK",
    "TS_REMOVE_ATTACKER_KNOCKBACK",
    "TS_SET_GLOBAL_SCRIPT_TYPE",
    "TS_AVAILABLE_GLOBAL_SCRIPT_TYPES",
    "TS_SET_SFALL_GLOBAL",
    "TS_GET_SFALL_GLOBAL_INT",
    "TS_GET_SFALL_GLOBAL_FLOAT",
    "TS_SET_PICKPOCKET_MAX",
    "TS_SET_HIT_CHANCE_MAX",
    "TS_SET_SKILL_MAX",
    "TS_EAX_AVAILABLE",
    "TS_SET_EAX_ENVIRONMENT",
    "TS_INC_NPC_LEVEL",
    "TS_GET_VIEWPORT_X",
    "TS_GET_VIEWPORT_Y",
    "TS_SET_VIEWPORT_X",
    "TS_SET_VIEWPORT_Y",
    "TS_SET_XP_MOD",
    "TS_SET_PERK_LEVEL_MOD",
    "TS_GET_INI_SETTING",
    "TS_GET_SHADER_VERSION",
    "TS_SET_SHADER_MODE",
    "TS_GET_GAME_MODE",
    "TS_FORCE_GRAPHICS_REFRESH",
    "TS_GET_SHADER_TEXTURE",
    "TS_SET_SHADER_TEXTURE",
    "TS_GET_UPTIME",
    "TS_SET_STAT_MAX",
    "TS_SET_STAT_MIN",
    "TS_SET_CAR_CURRENT_TOWN",
    "TS_SET_PC_STAT_MAX",
    "TS_SET_PC_STAT_MIN",
    "TS_SET_NPC_STAT_MAX",
    "TS_SET_NPC_STAT_MIN",
    "TS_SET_FAKE_PERK",
    "TS_SET_FAKE_TRAIT",
    "TS_SET_SELECTABLE_PERK",
    "TS_SET_PERKBOX_TITLE",
    "TS_HIDE_REAL_PERKS",
    "TS_SHOW_REAL_PERKS",
    "TS_HAS_FAKE_PERK",
    "TS_HAS_FAKE_TRAIT",
    "TS_PERK_ADD_MODE",
    "TS_CLEAR_SELECTABLE_PERKS",
    "TS_SET_CRITTER_HIT_CHANCE_MOD",
    "TS_SET_BASE_HIT_CHANCE_MOD",
    "TS_SET_CRITTER_SKILL_MOD",
    "TS_SET_BASE_SKILL_MOD",
    "TS_SET_CRITTER_PICKPOCKET_MOD",
    "TS_SET_BASE_PICKPOCKET_MOD",
    "TS_SET_PYROMANIAC_MOD",
    "TS_APPLY_HEAVEHO_FIX",
    "TS_SET_SWIFTLEARNER_MOD",
    "TS_SET_HP_LEVEL_MOD",
    "TS_WRITE_BYTE",
    "TS_WRITE_SHORT",
    "TS_WRITE_INT",
    "TS_CALL_OFFSET_V0",
    "TS_CALL_OFFSET_V1",
    "TS_CALL_OFFSET_V2",
    "TS_CALL_OFFSET_V3",
    "TS_CALL_OFFSET_V4",
    "TS_CALL_OFFSET_R0",
    "TS_CALL_OFFSET_R1",
    "TS_CALL_OFFSET_R2",
    "TS_CALL_OFFSET_R3",
    "TS_CALL_OFFSET_R4",
    "TS_SHOW_IFACE_TAG",
    "TS_HIDE_IFACE_TAG",
    "TS_IS_IFACE_TAG_ACTIVE",
    "TS_GET_BODYPART_HIT_MODIFIER",
    "TS_SET_BODYPART_HIT_MODIFIER",
    "TS_SET_CRITICAL_TABLE",
    "TS_GET_CRITICAL_TABLE",
    "TS_RESET_CRITICAL_TABLE",
    "TS_GET_SFALL_ARG",
    "TS_SET_SFALL_RETURN",
    "TS_SET_UNSPENT_AP_BONUS",
    "TS_GET_UNSPENT_AP_BONUS",
    "TS_SET_UNSPENT_AP_EBONUS",
    "TS_GET_UNSPENT_AP_EBONUS",
    "TS_INIT_HOOK",
    "TS_GET_INI_STRING",
    "TS_SQRT",
    "TS_ABS",
    "TS_SIN",
    "TS_COS",
    "TS_TAN",
    "TS_ATAN",
    "TS_SET_PALETTE",
    "TS_REMOVE_SCRIPT",
    "TS_SET_SCRIPT",
    "TS_GET_SCRIPT",
    "TS_NB_CREATE_CHAR",
    "TS_FS_CREATE",
    "TS_FS_COPY",
    "TS_FS_FIND",
    "TS_FS_WRITE_BYTE",
    "TS_FS_WRITE_SHORT",
    "TS_FS_WRITE_INT",
    "TS_FS_WRITE_FLOAT",
    "TS_FS_WRITE_STRING",
    "TS_FS_DELETE",
    "TS_FS_SIZE",
    "TS_FS_POS",
    "TS_FS_SEEK",
    "TS_FS_RESIZE",
    "TS_GET_PROTO_DATA",
    "TS_SET_PROTO_DATA",
    "TS_SET_SELF",
    "TS_REGISTER_HOOK",
    "TS_FS_WRITE_BSTRING",
    "TS_FS_READ_BYTE",
    "TS_FS_READ_SHORT",
    "TS_FS_READ_INT",
    "TS_FS_READ_FLOAT",
    "TS_LIST_BEGIN",
    "TS_LIST_NEXT",
    "TS_LIST_END",
    "TS_SFALL_VER_MAJOR",
    "TS_SFALL_VER_MINOR",
    "TS_SFALL_VER_BUILD",
    "TS_HERO_SELECT_WIN",
    "TS_SET_HERO_RACE",
    "TS_SET_HERO_STYLE",
    "TS_SET_CRITTER_BURST_DISABLE",
    "TS_GET_WEAPON_AMMO_PID",
    "TS_SET_WEAPON_AMMO_PID",
    "TS_GET_WEAPON_AMMO_COUNT",
    "TS_SET_WEAPON_AMMO_COUNT",
    "TS_WRITE_STRING",
    "TS_GET_MOUSE_X",
    "TS_GET_MOUSE_Y",
    "TS_GET_MOUSE_BUTTONS",
    "TS_GET_WINDOW_UNDER_MOUSE",
    "TS_GET_SCREEN_WIDTH",
    "TS_GET_SCREEN_HEIGHT",
    "TS_STOP_GAME",
    "TS_RESUME_GAME",
    "TS_CREATE_MESSAGE_WINDOW",
    "TS_REMOVE_TRAIT",
    "TS_GET_LIGHT_LEVEL",
    "TS_REFRESH_PC_ART",
    "TS_GET_ATTACK_TYPE",
    "TS_FORCE_ENCOUNTER_WITH_FLAGS",
    "TS_SET_MAP_TIME_MULTI",
    "TS_PLAY_SFALL_SOUND",
    "TS_STOP_SFALL_SOUND",
    "TS_CREATE_ARRAY",
    "TS_SET_ARRAY",
    "TS_GET_ARRAY",
    "TS_FREE_ARRAY",
    "TS_LEN_ARRAY",
    "TS_RESIZE_ARRAY",
    "TS_TEMP_ARRAY",
    "TS_FIX_ARRAY",
    "TS_STRING_SPLIT",
    "TS_LIST_AS_ARRAY",
    "TS_ATOI",
    "TS_ATOF",
    "TS_SCAN_ARRAY",
    "TS_TILE_PID",
    "TS_MODIFIED_INI",
    "TS_GET_SFALL_ARGS",
    "TS_SET_SFALL_ARG",
    "TS_FORCE_AIMED_SHOTS",
    "TS_DISABLE_AIMED_SHOTS",
    "TS_MARK_MOVIE_PLAYED",
    "TS_GET_NPC_LEVEL",
    "TS_SET_CRITTER_SKILL_POINTS",
    "TS_GET_CRITTER_SKILL_POINTS",
    "TS_SET_AVAILABLE_SKILL_POINTS",
    "TS_GET_AVAILABLE_SKILL_POINTS",
    "TS_MOD_SKILL_POINTS_PER_LEVEL",
    "TS_SET_PERK_FREQ",
    "TS_GET_LAST_ATTACKER",
    "TS_GET_LAST_TARGET",
    "TS_BLOCK_COMBAT",
    "TS_TILE_UNDER_CURSOR",
    "TS_GET_BARTER_MOD",
    "TS_SET_INVEN_AP_COST",
    "TS_SUBSTR",
    "TS_STRLEN",
    "TS_SPRINTF",
    "TS_ORD",
    "TS_RESERVD2",
    "TS_TYPEOF",
    "TS_SAVE_ARRAY",
    "TS_LOAD_ARRAY",
    "TS_GET_ARRAY_KEY",
    "TS_STACK_ARRAY",
    "TS_RESERVD3",
    "TS_RESERVD4",
    "TS_REG_ANIM_DESTROY",
    "TS_REG_ANIM_ANIMATE_AND_HIDE",
    "TS_REG_ANIM_COMBAT_CHECK",
    "TS_REG_ANIM_LIGHT",
    "TS_REG_ANIM_CHANGE_FID",
    "TS_REG_ANIM_TAKE_OUT",
    "TS_REG_ANIM_TURN_TOWARDS",
    "TS_EXPLOSIONS_METARULE",
    "TS_REGISTER_HOOK_PROC",
    "TS_POW",
    "TS_LOG",
    "TS_EXP",
    "TS_CEIL",
    "TS_ROUND",
    "TS_RESERVD5",
    "TS_RESERVD6",
    "TS_RESERVD7",
    "TS_MESSAGE_STR_GAME",
    "TS_SNEAK_SUCCESS",
    "TS_TILE_LIGHT",
    "TS_MAKE_STRAIGHT_PATH",
    "TS_OBJ_BLOCKING_AT",
    "TS_TILE_GET_OBJECTS",
    "TS_GET_PARTY_MEMBERS",
    "TS_PATH_FIND",
    "TS_CREATE_SPATIAL",
    "TS_ART_EXISTS",
    "TS_OBJ_IS_CARRYING_OBJ",
    "TS_SFALL_METARULE0",
    "TS_SFALL_METARULE1",
    "TS_SFALL_METARULE2",
    "TS_SFALL_METARULE3",
    "TS_SFALL_METARULE4",
    "TS_SFALL_METARULE5",
    "TS_SFALL_METARULE6",
    "TS_REGISTER_HOOK_PROC2",
    "TS_REG_ANIM_CALLBACK",
    "TS_DIV",
    "TS_SFALL_METARULE7",
    "TS_SFALL_METARULE8",
] as const;

/**
 * Positions where Fallout 1 gives the same opcode number a different function. Keyed by index into
 * ENGINE_OPCODES rather than by opcode value, so the two stay in step if the base ever moves.
 */
const FALLOUT1_OVERRIDES: Readonly<Record<number, string>> = {
    17: "REACTION", // Fallout 2: MARK_AREA_KNOWN
    46: "ANIMATE_JUMP", // Fallout 2: TILE_IN_TILE_RECT
    64: "TURN_OFF_OBJS_IN_AREA", // Fallout 2: METARULE3
    65: "TURN_ON_OBJS_IN_AREA", // Fallout 2: SET_MAP_MUSIC
    68: "BARTER_OFFER", // Fallout 2: WM_AREA_SET_POS
    69: "BARTER_ASKING", // Fallout 2: SET_EXIT_GRIDS
    104: "TOWN_MAP", // Fallout 2: INVEN_CMDS
};

export type LibOpcodeName = (typeof LIB_OPCODES)[number];
export type EngineOpcodeName = (typeof ENGINE_OPCODES)[number];

const LIB_BASE = O_OPERATOR + CORE_COUNT;
const ENGINE_BASE = LIB_BASE + LIB_OPCODES.length;

function tableOf(names: readonly string[], base: number): Readonly<Record<string, number>> {
    const table: Record<string, number> = {};
    names.forEach((name, index) => {
        table[name] = base + index;
    });
    return table;
}

/** Library opcodes by name, e.g. `LibOp.SAYSTART`. */
export const LibOp = tableOf(LIB_OPCODES, LIB_BASE) as Readonly<Record<LibOpcodeName, number>>;

/** Engine opcodes by name, e.g. `EngineOp.GIVE_EXP_POINTS`. */
export const EngineOp = tableOf(ENGINE_OPCODES, ENGINE_BASE) as Readonly<Record<EngineOpcodeName, number>>;

/** Opcode number one past the last engine opcode, for range checks. */
export const OPCODE_LIMIT = ENGINE_BASE + ENGINE_OPCODES.length;

/**
 * Name for an opcode value, given the target game. Returns undefined for the core range, which
 * `opcodeName` in `opcodes.ts` covers.
 */
export function engineOpcodeName(value: number, game: 1 | 2 = 2): string | undefined {
    if (value >= LIB_BASE && value < ENGINE_BASE) return LIB_OPCODES[value - LIB_BASE];
    if (value >= ENGINE_BASE && value < OPCODE_LIMIT) {
        const index = value - ENGINE_BASE;
        return (game === 1 ? FALLOUT1_OVERRIDES[index] : undefined) ?? ENGINE_OPCODES[index];
    }
    return undefined;
}
