packages:
    - client
    - format
    - server
    - grammars/*
    - cli/format
    - plugins/*
    - transpilers
    - transpilers/common
    - transpilers/tssl
    - transpilers/tbaf
    - transpilers/td
