// Harness helper: parse a real WeiDU D fixture into a DialogModel and emit it as
// real-model.ts for the render harness. Run from the repo root:
//   pnpm exec tsx client/src/dialog-editor/test/harness/gen-real-model.ts
// Not part of any test target; regenerate when the fixture or adapter changes.
import fs from "node:fs";
import path from "node:path";
import { initParser } from "../../../../../shared/parsers/weidu-d";
import { parseDDialog } from "../../../../../server/src/weidu-d/dialog";
import { modelFromD } from "../../../../../shared/dialog-model";
import { parseTra } from "./driver-util";

const here = __dirname;
const repo = path.resolve(here, "../../../../..");
const fixture = path.join(repo, "external/infinity-engine/BG1NPC/bg1npc/phase2/dlg/x#bri.d");
const traFile = path.join(repo, "external/infinity-engine/BG1NPC/bg1npc/tra/english/x#bri.tra");

async function main(): Promise<void> {
    await initParser();
    const text = fs.readFileSync(fixture, "utf8");
    const model = modelFromD(parseDDialog(text));
    // Resolution normally happens in the client (panel.ts) before render; the harness
    // joins the fixture's own .tra so the review sees real dialogue, not @N tokens.
    model.messages = parseTra(fs.readFileSync(traFile, "utf8"));
    const banner = `// Auto-generated by gen-real-model.ts from ${path.relative(repo, fixture)}. Do not hand-edit.\n`;
    const body = `import type { DialogModel } from "../../../../../shared/dialog-model";\n\nexport const REAL_MODEL: DialogModel = ${JSON.stringify(model, null, 4)};\n`;
    fs.writeFileSync(path.join(here, "real-model.ts"), banner + body);
    const roots = model.roots.map((r) => `${r.kind}:${r.label}(${r.states.length})`).join(", ");
    console.log(`wrote real-model.ts: ${model.roots.length} roots [${roots}]`);
}

main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
});
