// Auto-generated by gen-real-model.ts from external/infinity-engine/BG1NPC/bg1npc/phase2/dlg/x#bri.d. Do not hand-edit.
import type { DialogModel } from "../../../../../shared/dialog-model";

export const REAL_MODEL: DialogModel = {
    sourceLang: "d",
    editable: true,
    roots: [
        {
            id: "dialog:%tutu_var%BRIELB",
            label: "%tutu_var%BRIELB",
            kind: "dialog",
            states: [
                {
                    id: "16",
                    speaker: "%tutu_var%BRIELB",
                    text: "@2",
                    trigger: 'Global("HelpBrielbara","GLOBAL",1)',
                    choices: [
                        {
                            id: "16#0",
                            condition:
                                'Global("P#CoranBaby","GLOBAL",2) Global("P#Briel_Stay","GLOBAL",1) InParty("coran")',
                            action: 'SetGlobal("X#BriFinale","GLOBAL",1)',
                            target: {
                                kind: "state",
                                stateId: "returnBriel",
                            },
                        },
                        {
                            id: "16#1",
                            condition:
                                'GlobalLT("P#CoranBaby","GLOBAL",2) Global("P#Briel_Stay","GLOBAL",1) InParty("coran")',
                            action: 'SetGlobal("X#BriFinale","GLOBAL",1)',
                            target: {
                                kind: "state",
                                stateId: "NamaraCor",
                            },
                        },
                        {
                            id: "16#2",
                            condition: 'Global("P#Briel_Stay","GLOBAL",2) InParty("coran")',
                            action: 'SetGlobal("X#BriFinale","GLOBAL",1)',
                            target: {
                                kind: "state",
                                stateId: "BrielCurse",
                            },
                        },
                        {
                            id: "16#3",
                            condition: 'Global("P#Briel_Stay","GLOBAL",3)',
                            action: 'SetGlobal("X#BriFinale","GLOBAL",1)',
                            target: {
                                kind: "state",
                                stateId: "CoranStay",
                            },
                        },
                        {
                            id: "16#4",
                            condition: 'Global("P#Briel_Stay","GLOBAL",1) !InParty("coran")',
                            action: 'SetGlobal("X#BriFinale","GLOBAL",1)',
                            target: {
                                kind: "exit",
                            },
                        },
                        {
                            id: "16#5",
                            condition: '!Global("P#Briel_Stay","GLOBAL",1) !InParty("coran")',
                            action: 'SetGlobal("X#BriFinale","GLOBAL",1)',
                            target: {
                                kind: "exit",
                            },
                        },
                        {
                            id: "16#6",
                            condition: 'GlobalGT("P#Briel_Stay","GLOBAL",1)',
                            action: 'SetGlobal("X#BriFinale","GLOBAL",1)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 374,
                        end: 1278,
                    },
                },
                {
                    id: "returnBriel",
                    speaker: "%tutu_var%BRIELB",
                    text: "@31",
                    trigger:
                        '%BGT_VAR% Global("P#Briel_Stay","GLOBAL",1) InParty("coran") InMyArea("coran") !StateCheck("coran",CD_STATE_NOTVALID)',
                    choices: [
                        {
                            id: "returnBriel#0",
                            target: {
                                kind: "external",
                                label: "~%CORAN_JOINED%~:CBaby_Chain",
                                resolved: false,
                            },
                        },
                    ],
                    sourceRange: {
                        start: 6862,
                        end: 7066,
                    },
                },
                {
                    id: "BRIEL_PC",
                    speaker: "%tutu_var%BRIELB",
                    text: "@32",
                    choices: [
                        {
                            id: "BRIEL_PC#0",
                            text: "@33",
                            action: 'SetGlobal("P#Briel_Stay","GLOBAL",4) GiveItemCreate("X#CBABY","coran",1,0,0) GiveItemCreate("X#CBOOK","coran",1,0,0) GiveItemCreate("X#COBAG","coran",1,0,0) GiveItemCreate("X#CMILK","coran",1,0,0)',
                            target: {
                                kind: "external",
                                label: "~%CORAN_JOINED%~:CoranRun",
                                resolved: false,
                            },
                        },
                        {
                            id: "BRIEL_PC#1",
                            text: "@34",
                            action: 'SetGlobal("P#Briel_Stay","GLOBAL",4) GiveItemCreate("X#CBABY","coran",1,0,0) GiveItemCreate("X#CBOOK","coran",1,0,0) GiveItemCreate("X#COBAG","coran",1,0,0) GiveItemCreate("X#CMILK","coran",1,0,0)',
                            target: {
                                kind: "external",
                                label: "~%CORAN_JOINED%~:CoranRun",
                                resolved: false,
                            },
                        },
                        {
                            id: "BRIEL_PC#2",
                            text: "@35",
                            action: 'SetGlobal("P#Briel_Stay","GLOBAL",4) GiveItemCreate("X#CBABY","coran",1,0,0) GiveItemCreate("X#CBOOK","coran",1,0,0) GiveItemCreate("X#COBAG","coran",1,0,0) GiveItemCreate("X#CMILK","coran",1,0,0)',
                            target: {
                                kind: "external",
                                label: "~%CORAN_JOINED%~:Grumbles",
                                resolved: false,
                            },
                        },
                        {
                            id: "BRIEL_PC#3",
                            text: "@36",
                            condition: 'Global("P#CoranRomancePath","GLOBAL",1)',
                            action: 'SetGlobal("P#Briel_Stay","GLOBAL",4) GiveItemCreate("X#CBABY","coran",1,0,0) GiveItemCreate("X#CBOOK","coran",1,0,0) GiveItemCreate("X#COBAG","coran",1,0,0) GiveItemCreate("X#CMILK","coran",1,0,0)',
                            target: {
                                kind: "external",
                                label: "~%CORAN_JOINED%~:Lover",
                                resolved: false,
                            },
                        },
                        {
                            id: "BRIEL_PC#4",
                            text: "@37",
                            action: "GiveGoldForce(-10000)",
                            target: {
                                kind: "state",
                                stateId: "OhMine",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 7068,
                        end: 8235,
                    },
                },
                {
                    id: "OhMine",
                    speaker: "%tutu_var%BRIELB",
                    text: "@38",
                    choices: [
                        {
                            id: "OhMine#0",
                            action: 'SetGlobal("P#Briel_Stay","GLOBAL",5) EscapeArea()',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 8237,
                        end: 8338,
                    },
                },
                {
                    id: "NamaraCor",
                    speaker: "%tutu_var%BRIELB",
                    text: "@40",
                    choices: [
                        {
                            id: "NamaraCor#0",
                            target: {
                                kind: "external",
                                label: "~%CORAN_JOINED%~:CoranMumbles",
                                resolved: false,
                            },
                        },
                    ],
                    sourceRange: {
                        start: 8340,
                        end: 8426,
                    },
                },
                {
                    id: "BrielCurse",
                    speaker: "%tutu_var%BRIELB",
                    text: "@41",
                    choices: [
                        {
                            id: "BrielCurse#0",
                            target: {
                                kind: "external",
                                label: "~%CORAN_JOINED%~:CoranSigh",
                                resolved: false,
                            },
                        },
                    ],
                    sourceRange: {
                        start: 8428,
                        end: 8512,
                    },
                },
                {
                    id: "CoranStay",
                    speaker: "%tutu_var%BRIELB",
                    text: "@42",
                    choices: [
                        {
                            id: "CoranStay#0",
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 8514,
                        end: 8568,
                    },
                },
            ],
        },
        {
            id: "dialog:%CORAN_JOINED%",
            label: "%CORAN_JOINED%",
            kind: "dialog",
            states: [
                {
                    id: "CNRBabeBack",
                    speaker: "%CORAN_JOINED%",
                    text: "@3",
                    trigger: '%BGT_VAR% Global("P#CNRBabeBack","GLOBAL",1)',
                    weight: -2,
                    choices: [
                        {
                            id: "CNRBabeBack#0",
                            action: 'LeaveParty() SetGlobal("%KICKED_OUT%","LOCALS",1) SetLeavePartyDialogFile() ChangeAIScript("",DEFAULT) SetGlobal("P#CNRBabeBack","GLOBAL",2) SetGlobal("P#CoranMoves","GLOBAL",4) SetGlobalTimer("P#Alimony","GLOBAL",604800)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 1933,
                        end: 2326,
                    },
                },
                {
                    id: "CORANBABY",
                    speaker: "%CORAN_JOINED%",
                    text: "@6",
                    trigger: '%BGT_VAR% Global("P#CoranBaby","GLOBAL",1)',
                    weight: -2,
                    choices: [
                        {
                            id: "CORANBABY#0",
                            text: "@7",
                            action: 'SetGlobal("P#CoranBaby","GLOBAL",2) RealSetGlobalTimer("P#CFriendTalkTime","GLOBAL",1800)',
                            target: {
                                kind: "state",
                                stateId: "CB_1.1",
                            },
                        },
                        {
                            id: "CORANBABY#1",
                            text: "@8",
                            action: 'SetGlobal("P#CoranBaby","GLOBAL",2) SetGlobal("P#CoranRepeat","GLOBAL",1) RealSetGlobalTimer("P#CFriendTalkTime","GLOBAL",1800)',
                            target: {
                                kind: "state",
                                stateId: "CB_1.2",
                            },
                        },
                        {
                            id: "CORANBABY#2",
                            text: "@9",
                            action: 'SetGlobal("P#CoranBaby","GLOBAL",2) RealSetGlobalTimer("P#CFriendTalkTime","GLOBAL",1800)',
                            target: {
                                kind: "state",
                                stateId: "CB_1.3",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 2612,
                        end: 3122,
                    },
                },
                {
                    id: "CB_1.1",
                    speaker: "%CORAN_JOINED%",
                    text: "@10",
                    choices: [
                        {
                            id: "CB_1.1#0",
                            text: "@11",
                            target: {
                                kind: "state",
                                stateId: "CB_1.4",
                            },
                        },
                        {
                            id: "CB_1.1#1",
                            text: "@12",
                            target: {
                                kind: "state",
                                stateId: "CB_1.5",
                            },
                        },
                        {
                            id: "CB_1.1#2",
                            text: "@13",
                            target: {
                                kind: "state",
                                stateId: "CB_1.6",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 3124,
                        end: 3258,
                    },
                },
                {
                    id: "CB_1.3",
                    speaker: "%CORAN_JOINED%",
                    text: "@14",
                    choices: [
                        {
                            id: "CB_1.3#0",
                            text: "@11",
                            target: {
                                kind: "state",
                                stateId: "CB_1.4",
                            },
                        },
                        {
                            id: "CB_1.3#1",
                            text: "@12",
                            target: {
                                kind: "state",
                                stateId: "CB_1.5",
                            },
                        },
                        {
                            id: "CB_1.3#2",
                            text: "@15",
                            target: {
                                kind: "state",
                                stateId: "CB_1.6",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 3260,
                        end: 3394,
                    },
                },
                {
                    id: "CB_1.2",
                    speaker: "%CORAN_JOINED%",
                    text: "@16",
                    choices: [
                        {
                            id: "CB_1.2#0",
                            action: 'SetGlobal("P#CoranRepeat","GLOBAL",1)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 3396,
                        end: 3490,
                    },
                },
                {
                    id: "CB_1.4",
                    speaker: "%CORAN_JOINED%",
                    text: "@17",
                    choices: [
                        {
                            id: "CB_1.4#0",
                            action: 'SetGlobal("P#CoranWillComplain","GLOBAL",1)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 3492,
                        end: 3592,
                    },
                },
                {
                    id: "CB_1.5",
                    speaker: "%CORAN_JOINED%",
                    text: "@18",
                    choices: [
                        {
                            id: "CB_1.5#0",
                            action: 'ReputationInc(-1) ChangeAlignment("coran",CHAOTIC_NEUTRAL) SetGlobal("P#Briel_Stay","GLOBAL",2) SetGlobal("P#Briel_Stay","GLOBAL",2) SetGlobal("P#CoranRomancePath","GLOBAL",3)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 3594,
                        end: 3826,
                    },
                },
                {
                    id: "CB_1.6",
                    speaker: "%CORAN_JOINED%",
                    text: "@19",
                    choices: [
                        {
                            id: "CB_1.6#0",
                            action: 'SetGlobal("P#Briel_Stay","GLOBAL",3) ReputationInc(-1) LeaveParty() SetLeavePartyDialogFile() ChangeAIScript("",DEFAULT) EscapeArea()',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 3828,
                        end: 4018,
                    },
                },
                {
                    id: "CBABY_SECOND",
                    speaker: "%CORAN_JOINED%",
                    text: "@20",
                    trigger: '%BGT_VAR% Global("P#CBABY_AGAIN","GLOBAL",1)',
                    weight: -2,
                    choices: [
                        {
                            id: "CBABY_SECOND#0",
                            text: "@7",
                            action: 'SetGlobal("P#CBABY_AGAIN","GLOBAL",2)',
                            target: {
                                kind: "state",
                                stateId: "DCB_1.1",
                            },
                        },
                        {
                            id: "CBABY_SECOND#1",
                            text: "@9",
                            action: 'SetGlobal("P#CBABY_AGAIN","GLOBAL",2)',
                            target: {
                                kind: "state",
                                stateId: "DCB_1.3",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 4020,
                        end: 4269,
                    },
                },
                {
                    id: "DCB_1.1",
                    speaker: "%CORAN_JOINED%",
                    text: "@10",
                    choices: [
                        {
                            id: "DCB_1.1#0",
                            text: "@11",
                            target: {
                                kind: "state",
                                stateId: "DCB_1.4",
                            },
                        },
                        {
                            id: "DCB_1.1#1",
                            text: "@12",
                            target: {
                                kind: "state",
                                stateId: "DCB_1.5",
                            },
                        },
                        {
                            id: "DCB_1.1#2",
                            text: "@21",
                            target: {
                                kind: "state",
                                stateId: "DCB_1.6",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 4271,
                        end: 4409,
                    },
                },
                {
                    id: "DCB_1.3",
                    speaker: "%CORAN_JOINED%",
                    text: "@14",
                    choices: [
                        {
                            id: "DCB_1.3#0",
                            text: "@11",
                            target: {
                                kind: "state",
                                stateId: "DCB_1.4",
                            },
                        },
                        {
                            id: "DCB_1.3#1",
                            text: "@12",
                            target: {
                                kind: "state",
                                stateId: "DCB_1.5",
                            },
                        },
                        {
                            id: "DCB_1.3#2",
                            text: "@15",
                            target: {
                                kind: "state",
                                stateId: "DCB_1.6",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 4411,
                        end: 4549,
                    },
                },
                {
                    id: "DCB_1.4",
                    speaker: "%CORAN_JOINED%",
                    text: "@17",
                    choices: [
                        {
                            id: "DCB_1.4#0",
                            action: 'SetGlobal("P#CoranWillComplain","GLOBAL",1)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 4551,
                        end: 4652,
                    },
                },
                {
                    id: "DCB_1.5",
                    speaker: "%CORAN_JOINED%",
                    text: "@18",
                    choices: [
                        {
                            id: "DCB_1.5#0",
                            action: 'ReputationInc(-1) ChangeAlignment("coran",CHAOTIC_NEUTRAL) SetGlobal("P#Briel_Stay","GLOBAL",2) SetGlobal("P#CoranRomancePath","GLOBAL",3)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 4654,
                        end: 4850,
                    },
                },
                {
                    id: "DCB_1.6",
                    speaker: "%CORAN_JOINED%",
                    text: "@19",
                    choices: [
                        {
                            id: "DCB_1.6#0",
                            action: 'SetGlobal("P#Briel_Stay","GLOBAL",3) ReputationInc(-1) LeaveParty() SetLeavePartyDialogFile() ChangeAIScript("",DEFAULT) EscapeArea()',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 4852,
                        end: 5043,
                    },
                },
                {
                    id: "CB_COMPLAINT",
                    speaker: "%CORAN_JOINED%",
                    text: "@22",
                    trigger: '%BGT_VAR% Global("P#Briel_Stay","GLOBAL",1) Global("P#CB_COMPLAINS","GLOBAL",1)',
                    weight: -2,
                    choices: [
                        {
                            id: "CB_COMPLAINT#0",
                            text: "@23",
                            action: 'SetGlobal("P#CB_COMPLAINS","GLOBAL",2)',
                            target: {
                                kind: "state",
                                stateId: "CB_2.1",
                            },
                        },
                        {
                            id: "CB_COMPLAINT#1",
                            text: "@24",
                            action: 'SetGlobal("P#CB_COMPLAINS","GLOBAL",2)',
                            target: {
                                kind: "state",
                                stateId: "CB_2.2",
                            },
                        },
                        {
                            id: "CB_COMPLAINT#2",
                            text: "@21",
                            action: 'SetGlobal("P#CB_COMPLAINS","GLOBAL",2)',
                            target: {
                                kind: "state",
                                stateId: "CB_2.3",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 5045,
                        end: 5408,
                    },
                },
                {
                    id: "CB_2.1",
                    speaker: "%CORAN_JOINED%",
                    text: "@17",
                    choices: [
                        {
                            id: "CB_2.1#0",
                            action: 'SetGlobal("P#CoranWillQuit","GLOBAL",1)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 5410,
                        end: 5506,
                    },
                },
                {
                    id: "CB_2.2",
                    speaker: "%CORAN_JOINED%",
                    text: "@18",
                    choices: [
                        {
                            id: "CB_2.2#0",
                            action: 'ReputationInc(-1) ChangeAlignment("coran",CHAOTIC_NEUTRAL) SetGlobal("P#Briel_Stay","GLOBAL",2) SetGlobal("P#Briel_Stay","GLOBAL",2) SetGlobal("P#CoranRomancePath","GLOBAL",3)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 5508,
                        end: 5740,
                    },
                },
                {
                    id: "CB_2.3",
                    speaker: "%CORAN_JOINED%",
                    text: "@21",
                    choices: [
                        {
                            id: "CB_2.3#0",
                            action: 'SetGlobal("P#Briel_Stay","GLOBAL",3) ReputationInc(-1) LeaveParty() SetLeavePartyDialogFile() ChangeAIScript("",DEFAULT) EscapeArea()',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 5742,
                        end: 5932,
                    },
                },
                {
                    id: "CB_QUITS",
                    speaker: "%CORAN_JOINED%",
                    text: "@25",
                    trigger: '%BGT_VAR% Global("P#CB_QUITS","GLOBAL",1)',
                    weight: -2,
                    choices: [
                        {
                            id: "CB_QUITS#0",
                            action: 'SetGlobal("P#CB_QUITS","GLOBAL",2) SetGlobal("P#Briel_Stay","GLOBAL",3) LeaveParty() SetLeavePartyDialogFile() ChangeAIScript("",DEFAULT) EscapeArea()',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 5934,
                        end: 6196,
                    },
                },
                {
                    id: "CoranRun",
                    speaker: "%CORAN_JOINED%",
                    text: "@26",
                    choices: [
                        {
                            id: "CoranRun#0",
                            action: 'SetGlobal("P#CoranHasBaby","GLOBAL",1) SetGlobalTimer("P#ReturnNamara","GLOBAL",151500)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 6198,
                        end: 6344,
                    },
                },
                {
                    id: "Grumbles",
                    speaker: "%CORAN_JOINED%",
                    text: "@27",
                    choices: [
                        {
                            id: "Grumbles#0",
                            action: 'SetGlobal("P#CoranHasBaby","GLOBAL",1) SetGlobalTimer("P#ReturnNamara","GLOBAL",151500)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 6346,
                        end: 6492,
                    },
                },
                {
                    id: "Lover",
                    speaker: "%CORAN_JOINED%",
                    text: "@28",
                    choices: [
                        {
                            id: "Lover#0",
                            action: 'SetGlobal("P#CoranHasBaby","GLOBAL",1) SetGlobalTimer("P#ReturnNamara","GLOBAL",151500)',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 6494,
                        end: 6637,
                    },
                },
                {
                    id: "CoranMumbles",
                    speaker: "%CORAN_JOINED%",
                    text: "@29",
                    choices: [
                        {
                            id: "CoranMumbles#0",
                            action: 'SetGlobal("P#CoranPrompted","GLOBAL",1)',
                            target: {
                                kind: "external",
                                label: "~%tutu_var%BRIELB~:BrielCurse",
                                resolved: false,
                            },
                        },
                    ],
                    sourceRange: {
                        start: 6639,
                        end: 6773,
                    },
                },
                {
                    id: "CoranSigh",
                    speaker: "%CORAN_JOINED%",
                    text: "@30",
                    choices: [
                        {
                            id: "CoranSigh#0",
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 6775,
                        end: 6829,
                    },
                },
                {
                    id: "CBaby_Chain",
                    speaker: "%CORAN_JOINED%",
                    text: "@43",
                    choices: [
                        {
                            id: "CBaby_Chain#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_1",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_1",
                    speaker: "%tutu_var%BRIELB",
                    text: "@44",
                    choices: [
                        {
                            id: "CBaby_Chain_1#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_2",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_2",
                    speaker: "%CORAN_JOINED%",
                    text: "@45",
                    choices: [
                        {
                            id: "CBaby_Chain_2#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_3",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_3",
                    speaker: "%tutu_var%BRIELB",
                    text: "@46",
                    choices: [
                        {
                            id: "CBaby_Chain_3#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_4",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_4",
                    speaker: "%CORAN_JOINED%",
                    text: "@47",
                    choices: [
                        {
                            id: "CBaby_Chain_4#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_5",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_5",
                    speaker: "%tutu_var%BRIELB",
                    text: "@48",
                    choices: [
                        {
                            id: "CBaby_Chain_5#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_6",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_6",
                    speaker: "%CORAN_JOINED%",
                    text: "@49",
                    choices: [
                        {
                            id: "CBaby_Chain_6#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_7",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_7",
                    speaker: "%tutu_var%BRIELB",
                    text: "@50",
                    choices: [
                        {
                            id: "CBaby_Chain_7#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_8",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_8",
                    speaker: "%CORAN_JOINED%",
                    text: "@51",
                    choices: [
                        {
                            id: "CBaby_Chain_8#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_9",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_9",
                    speaker: "%tutu_var%BRIELB",
                    text: "@52",
                    choices: [
                        {
                            id: "CBaby_Chain_9#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_10",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_10",
                    speaker: "%CORAN_JOINED%",
                    text: "@53",
                    choices: [
                        {
                            id: "CBaby_Chain_10#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_11",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_11",
                    speaker: "%tutu_var%BRIELB",
                    text: "@54",
                    choices: [
                        {
                            id: "CBaby_Chain_11#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_12",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_12",
                    speaker: "%CORAN_JOINED%",
                    text: "@55",
                    choices: [
                        {
                            id: "CBaby_Chain_12#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_13",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_13",
                    speaker: "%tutu_var%BRIELB",
                    text: "@56",
                    choices: [
                        {
                            id: "CBaby_Chain_13#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_14",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_14",
                    speaker: "%CORAN_JOINED%",
                    text: "@57",
                    choices: [
                        {
                            id: "CBaby_Chain_14#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_15",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_15",
                    speaker: "%tutu_var%BRIELB",
                    text: "@58",
                    choices: [
                        {
                            id: "CBaby_Chain_15#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_16",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_16",
                    speaker: "%CORAN_JOINED%",
                    text: "@59",
                    choices: [
                        {
                            id: "CBaby_Chain_16#0",
                            target: {
                                kind: "state",
                                stateId: "CBaby_Chain_17",
                            },
                        },
                    ],
                    derivedFrom: "CHAIN",
                },
                {
                    id: "CBaby_Chain_17",
                    speaker: "%tutu_var%BRIELB",
                    text: "@60",
                    choices: [],
                    derivedFrom: "CHAIN",
                },
            ],
        },
        {
            id: "dialog:%CORAN_POST%",
            label: "%CORAN_POST%",
            kind: "dialog",
            states: [
                {
                    id: "CNRBack",
                    speaker: "%CORAN_POST%",
                    text: "@5",
                    trigger: '%BGT_VAR% Global("P#CoranMoves","GLOBAL",6)',
                    weight: -100,
                    choices: [
                        {
                            id: "CNRBack#0",
                            action: 'SetGlobal("P#CoranMoves","GLOBAL",7) JoinParty()',
                            target: {
                                kind: "exit",
                            },
                        },
                    ],
                    sourceRange: {
                        start: 2420,
                        end: 2581,
                    },
                },
            ],
        },
        {
            id: "patch#0",
            label: "REPLACE_SAY %CORAN_JOINED%",
            kind: "patch",
            states: [],
        },
        {
            id: "patch#1",
            label: "REPLACE_SAY %tutu_var%BRIELB",
            kind: "patch",
            states: [],
        },
        {
            id: "patch#2",
            label: "PATCH %tutu_var%BRIELB",
            kind: "patch",
            states: [],
        },
    ],
    messages: {
        "0": "I'm sorry, Briel, but we... we have been over this already... and you have said, that...",
        "1": "That you are an idiot. Go, if you want, but maybe someday you'll figure out what is it you really want, elf.",
        "2": "I must thank you again for the service you have done.",
        "3": "<CHARNAME>, it's becoming too dangerous to keep Namara around. Not to mention all the bad habits she picks up from our rag-tag band... I'll go talk to Briel.",
        "4": 'I hope that I still have some influence over her... *grins* so it should not take me long to persuade her to take money and visits instead of me babysitting Namara on battlefields. Meet me back in the "Sturgeon", <CHARNAME>.',
        "5": "Ah, here you are. Back to adventure!",
        "6": "May I have a word with you, <CHARNAME>?",
        "7": "Of course, Coran, what is it?",
        "8": "Yes, but not now.",
        "9": "Coran... frankly, I have no desire to talk to you, after what you have done...",
        "10": "I... I would like very much to go back and talk to Briel again. The girl might need help, and I feel that I have wronged her... Can we go meet with her?",
        "11": "Coran, I am glad that you have decided to sort it out. All this made me feel awkward. We should go visit Briel as soon as we are able.",
        "12": "Coran, are you kidding? The girl is blackmailing you! I mean, you never wanted a child, did you? Why do you need to waste your time? She wanted it, so she can take care of the whelp herself!",
        "13": "Well, I am afraid that in this case we should part our company.",
        "14": "I understand that, <CHARNAME>. I am unhappy with what I have said to Briel myself. The girl might need help, and I feel that I have wronged her... I... I would like very much to go back and talk to Briel again. Can we go meet with her?",
        "15": "Well, I am afraid that in this case we should part our company.",
        "16": "We will talk later then.",
        "17": "Thank you, <CHARNAME>. I feel much better now.",
        "18": "Indeed... I have never wanted a child, and a half-breed, at that. Half-bloods are always raised by their mothers. Besides, I just don't have the time or inclination to care for my... I mean, Briel's child.",
        "19": "*sighs* You are right. See you in 20 years or so...",
        "20": "I'd like to talk about Briel, <CHARNAME>.",
        "21": "Well, I am afraid that in this case we should part our company. See you in 20 years or so...",
        "22": "Ahem, <CHARNAME>, I know we are rather busy, but I really need to talk to Briel... Can we go see her now?",
        "23": "We should go visit Briel as soon as we are able.",
        "24": "Coran, I like this idea less and less. The girl is just blackmailing you! I mean you never wanted a child, did you? Why do you need to waste your time? She wanted it, so she can take care of the whelp herself.",
        "25": "Briel is not going to wait forever! It is apparent that you have things more important to attend to than the fate of my daughter. I do not. See you in 20 years or so...",
        "26": "Thank you, <CHARNAME>. I am no coward, but when a baby's life is at stake... I will run for it.",
        "27": "Erm... <CHARNAME>. It cannot be that bad, can it?",
        "28": "I... I am glad that you see it that way. It is a bastard child, after all.",
        "29": "I... I... Briel... I do not know.",
        "30": "*sighs* I am sorry, beautiful, but there is really nothing I can do for you or your child.",
        "31": "Coran?",
        "32": "Thank you, again, <CHARNAME>.",
        "33": "Brielbara, I promise you, that if it gets hot, Coran will run and save the child.",
        "34": "You are a mad woman, Brielbara, but we'll try to keep Namara safe and well.",
        "35": "Great, just great. That's *just* what we need.",
        "36": "You have done well, my love.",
        "37": "That would not do at all. Brielbara, Coran is my sworn sword, and as his liege <PRO_LADYLORD>, I accept the responsibility for his past misdeeds. As he has no inclination to marry you, and I do not wish to force him in this matter, I would like to pay you 10,000 gold as a compensation for his dishonoring you. I trust that it is enough for you to live comfortably until you've arranged your affairs.",
        "38": "I... I am... This is very generous, my <PRO_LADYLORD>....",
        "39": "Coran, I wish... I wish it could have been different, but I can't make you love me, not without my sorcery. *smiles softly* And who needs love instigated by magic?",
        "40": "Coran? Do not you even want to see Namara? She has your eyes... elven eyes.",
        "41": "I curse the day I laid my eyes on you, Coran.",
        "42": "And... thank you for sending that no good thief my way. *sighs dreamily* He is not *that* bad, actually.",
        "43": "Ahem, Briel... I did a lot of thinking and... I've come to apologize, Briel...",
        "44": "Apologize? What do I need an apology for? Would it put food on Namara's plate and clothes on her back? Or should I sing your apology as a lullaby for her, when she will not stop crying for her father?",
        "45": "Eh, Briel, slow down! I came to offer my help as well. I know, that we disagree about my... hmm... lifestyle, and that you are too noble to be a thief's mate...",
        "46": "Coran, why must you be so incredibly stubborn about it? You are going to end up in prison or hanged for a bandit, silly Elf. I know you have a better heart than that... why would not you...",
        "47": "Briel, Briel... Please, let us spare <CHARNAME> the further details of our favorite argument. The City of Baldur's Gate needs something newer than that to listen to. I am not cut out to become a merchant or some other respectable member of society.",
        "48": "A pity...",
        "49": "Maybe. Briel, I promise you that every time I come into money, Namara and you will have...",
        "50": "I see. Coran, I feel that you are sincere, and that you do want to help. However, I am afraid that will not be enough, not with your peculiar notion on what responsibility is. I have an idea, though, on how you can help.",
        "51": "What would you have me do, Briel? I agree to anything, except for settling down, of course.",
        "52": "It has been rough going for us lately with Namara sick and my husband plotting against us... He took it all, Coran! House, money, everything. I can hardly get by, and I am so tired... Would you take Namara with you and take care of her for a while to give me some time to get back on my feet?",
        "53": "Huh, Briel... are you sure? I lack knowledge on baby care. I doubt that I can... you know... feed the baby and... and do whatever else you have to do. Actually, I know nothing of babies at all.",
        "54": "Then it is past time that you learnt. She is now at an age when she does not require breast feeding, and I have here a book of helpful hints...",
        "55": "Briel! Not that I refuse, but won't it be dangerous for a child to travel with me? We are constantly fighting for our lives and...",
        "56": "It is no more dangerous for her in your company than in that place in the bowels of this city I keep her now... I never know that she won't be sold to some slavers or killed out of spite by some lowlife while I am away... Coran, desperate people cannot be choosy.",
        "57": "Would you want to travel with me then? I am sure <CHARNAME>...",
        "58": "No, Coran, I will not be a part of a mercenary group, and I would not go about robbing people with you. My reputation is ruined as is. If you want to help - take care of Namara for a bit...",
        "59": "Well, if that's what you want me to do, I will do it.",
        "60": "Good. Thank you, Coran. And do not look so sour, you might come to enjoy it, after all. Here is the book, and I will bring Namara in a moment.",
    },
};
