// Auto-generated from IESDP _opcodes/opNNN.html. Do not hand-edit.

export interface OpcodeRelationship {
    param1?: { label?: string; enum?: Readonly<Record<number, string>> };
    param2?: { label?: string; enum?: Readonly<Record<number, string>> };
    availability?: Readonly<Record<string, boolean>>;
}

export const OpcodeRelationships: Readonly<Record<number, OpcodeRelationship>> = {
    0: { param1: { label: "AC Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    1: { param1: { label: "Key Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    2: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    3: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: true, pstee: true } },
    4: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    5: { param1: { label: "General Type" }, param2: { label: "Charm Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    6: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    7: { param1: { label: "Gradient Number" }, param2: { label: "Location" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: true, pstee: true } },
    8: { param1: { label: "RGB colour" }, param2: { label: "Location" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    9: { param1: { label: "RGB Colour" }, param2: { label: "Location and Speed" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    10: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    11: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    12: { param1: { label: "Damage Amount" }, param2: { label: "Type" }, availability: { bg1: true, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    13: { param1: { label: "Text Notification" }, param2: { label: "Death Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    15: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    16: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    17: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: false, bgee: false, iwd1: true, iwd2: false, pst: true, pstee: false } },
    18: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    19: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    20: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    21: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    22: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    23: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: false, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    24: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: true, pstee: true } },
    25: { param1: { label: "Damage Amount" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    26: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    27: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    28: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    29: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    30: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    31: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    32: { param1: { label: "Irrelevant" }, param2: { label: "Restore creature animation?" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    33: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    34: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    35: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    36: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    37: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    38: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    39: { param1: { label: "Irrelevant" }, param2: { label: "Wake on Damage?" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    40: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    41: { param1: { label: "Colour" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: false } },
    42: { param1: { label: "Slot Amount Modifier" }, param2: { label: "Spell Level" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: false, iwd2: true, pst: true, pstee: false } },
    43: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    44: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    45: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: true, pstee: true } },
    46: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    47: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    48: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    49: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    50: { param1: { label: "RGB Colour" }, param2: { label: "Location and Speed" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    51: { param1: { label: "RGB Colour" }, param2: { label: "Location" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    52: { param1: { label: "RGB Colour" }, param2: { label: "Location" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    53: { param1: { label: "Animation ID" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    54: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    55: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    56: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    57: { param1: { label: "Irrelevant" }, param2: { label: "Alignment" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    58: { param1: { label: "Level" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    59: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    60: { param1: { label: "Percent Chance" }, param2: { label: "Type" }, availability: { bg1: true, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: true, pstee: false } },
    61: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: false, pst: true, pstee: false } },
    62: { param1: { label: "Slot Amount Modifier" }, param2: { label: "Spell Level" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: true, pstee: true } },
    63: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    64: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    65: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    66: { param1: { label: "Fade Amount" }, param2: { label: "Visual Effect" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    67: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    68: { param1: { label: "Text Notification" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    69: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    70: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    71: { param1: { label: "Gender Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    72: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    73: { param1: { label: "Damage Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    74: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    75: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    76: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    77: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    79: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    80: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    81: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    82: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    83: { param1: { label: "Irrelevant" }, param2: { label: "Projectile Index" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    84: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: true, pstee: true } },
    85: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: true, pstee: true } },
    86: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    87: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    88: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    89: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    90: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    91: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    92: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    93: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    94: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    95: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    96: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    97: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    98: { param1: { label: "Regeneration Amount" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    99: { param1: { label: "Duration Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    100: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    101: { param1: { label: "Irrelevant" }, param2: { label: "Opcode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    102: { param1: { label: "Spell Level" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    103: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    104: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    105: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    106: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    107: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    108: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    109: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: true, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    110: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    111: { param1: { label: "Amount" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    112: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    113: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    114: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: true, pstee: true } },
    115: { param1: { label: "Irrelevant" }, param2: { label: "Alignment Mask" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    116: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    117: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    118: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    119: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: true, pstee: true } },
    120: { param1: { label: "Enchantment" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    121: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    122: { param1: { label: "Charges" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    123: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    124: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    125: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    126: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    127: { param1: { label: "Number" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    128: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    129: { param1: { label: "Statistic Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    130: { param1: { label: "Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    131: { param1: { label: "Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    132: { param1: { label: "Statistic Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    133: { param1: { label: "Statistic Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    134: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    135: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    136: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    137: { param1: { label: "Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    138: { param1: { label: "Irrelevant" }, param2: { label: "Animation Sequence" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    139: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    140: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: false, pst: false, pstee: false } },
    141: { param1: { label: "Target" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: false, pst: true, pstee: false } },
    142: { param1: { label: "Irrelevant" }, param2: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    143: { param1: { label: "Slot" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    144: { param1: { label: "Irrelevant" }, param2: { label: "Button" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    145: { param1: { label: "Irrelevant" }, param2: { label: "Spell Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    146: { param1: { label: "Casting Level" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    147: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: false, bgee: false, iwd1: true, iwd2: false, pst: false, pstee: false } },
    148: { param1: { label: "Casting Level" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    149: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    150: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    151: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    152: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    153: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    154: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    155: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: false, pst: true, pstee: false } },
    156: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: false, pst: true, pstee: false } },
    157: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    158: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    159: { param1: { label: "Amount" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    160: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    161: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    162: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    163: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    164: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    165: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    166: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    167: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    168: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    169: { param1: { label: "Irrelevant" }, param2: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    170: { param1: { label: "Irrelevant" }, param2: { label: "Animation" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    171: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    172: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: true, pstee: true } },
    173: { param1: { label: "Statistic Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    174: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    175: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: false, pst: true, pstee: false } },
    176: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    178: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: true, bg2: false, bgee: false, iwd1: true, iwd2: false, pst: false, pstee: false } },
    179: { param1: { label: "Reference Value" }, param2: { label: "Reference IDS" }, availability: { bg1: true, bg2: false, bgee: false, iwd1: true, iwd2: false, pst: false, pstee: false } },
    180: { param1: { label: "String Reference" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    182: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: true, bg2: true, bgee: false, iwd1: true, iwd2: true, pst: true, pstee: false } },
    183: { param1: { label: "Undetermined" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    184: { param1: { label: "Undefined" }, param2: { label: "Jump" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    186: { param1: { label: "Delay" }, param2: { label: "Orientation" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    187: { param1: { label: "Value" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    188: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    189: { param1: { label: "Speed Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    190: { param1: { label: "Speed Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    192: { param1: { label: "Irrelevant" }, param2: { label: "Upgrade Marker" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    193: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    194: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    195: { param1: { label: "Max HP Modifier" }, param2: { label: "Unused" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    196: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    197: { param1: { label: "Irrelevant" }, param2: { label: "Impact Projectile" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    198: { param1: { label: "Irrelevant" }, param2: { label: "Opcode" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    199: { param1: { label: "Power Level" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    200: { param1: { label: "Total Amount" }, param2: { label: "Power Level" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    201: { param1: { label: "Total Amount" }, param2: { label: "Power Level" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    202: { param1: { label: "Irrelevant" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    203: { param1: { label: "Irrelevant" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    204: { param1: { label: "Irrelevant" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    205: { param1: { label: "Irrelevant" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    206: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    207: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    208: { param1: { label: "Minimum Value" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    209: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    210: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: false, pstee: true } },
    211: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    212: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    213: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    214: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    215: { param1: { label: "Undetermined" }, param2: { label: "Play where?" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    216: { param1: { label: "Amount" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    217: { param1: { label: "Irrelevant" }, param2: { label: "Wake on damage" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    220: { param1: { label: "Maximum Level" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    221: { param1: { label: "Maximum Level" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    222: { param1: { label: "Max Range" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    223: { param1: { label: "Total Amount" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    224: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    225: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    226: { param1: { label: "Total Amount" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    227: { param1: { label: "Total Amount" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    228: { param1: { label: "Total Amount" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    229: { param1: { label: "Max Level" }, param2: { label: "School Type" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    230: { param1: { label: "Max Level" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    231: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    233: { param1: { label: "Amount" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    234: { param1: { label: "Maximum Level Usable" }, param2: { label: "Amount/Type" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    235: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    236: { param1: { label: "Undetermined" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    237: { param1: { label: "Master ID" }, param2: { label: "Image Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    238: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    239: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    240: { param1: { label: "Irrelevant" }, param2: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    241: { param1: { label: "Damage" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    242: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    244: { param1: { label: "Number to Drain" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    245: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    246: { param1: { label: "Undetermined" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    247: { param1: { label: "Irrelevant" }, param2: { label: "Constant Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    248: { param1: { label: "Irrelevant" }, param2: { label: "Fist only" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    249: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    250: { param1: { label: "Damage Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    251: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    252: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    253: { param1: { label: "String Reference" }, param2: { label: "Marker Color" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    254: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    255: { param1: { label: "Charges" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    256: { param1: { label: "Duration" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    257: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: false, pst: false, pstee: false } },
    258: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    259: { param1: { label: "Total Amount" }, param2: { label: "Power Level" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    261: { param1: { label: "Irrelevant" }, param2: { label: "Opcode" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    262: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    263: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    264: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    265: { param1: { label: "Value" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    266: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    267: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    268: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    269: { param1: { label: "Strength" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    270: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    271: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    272: { param1: { label: "Frequency" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    273: { param1: { label: "Undetermined" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    274: { param1: { label: "Undetermined" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    275: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    276: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    277: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    278: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    279: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    280: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    281: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    282: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    283: { param1: { label: "Strref" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    284: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    285: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    286: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    287: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    288: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    289: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    290: { param1: { label: "String Reference" }, param2: { label: "Position" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    292: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    293: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    294: { param1: { label: "Undefined" }, param2: { label: "Constant Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    295: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    296: { param1: { label: "Value" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: true, iwd2: true, pst: false, pstee: false } },
    297: { param1: { label: "Undefined" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    298: { param1: { label: "Irrelevant" }, param2: { label: "Constant Value" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    299: { param1: { label: "Shield Amount" }, param2: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    300: { param1: { label: "Unknown" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    302: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    303: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    304: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    305: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    306: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    307: { param1: { label: "Range" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    308: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    309: { param1: { label: "Value" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    310: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    311: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    312: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: false, bg2: true, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: false } },
    313: { param1: { label: "Undetermined" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    314: { param1: { label: "Amount" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    315: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    316: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    317: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
};
