// Auto-generated from IESDP _opcodes/opNNN.html. Do not hand-edit.

/**
 * Effect / EFF body opcode -> display name. Sourced from IESDP `_opcodes/op<NNN>.html` frontmatter
 * `opname` fields, falling back to the engine-variant pages for the opcodes that have no canonical
 * page - the EE and IWD2 ranges among them.
 */
export const Opcodes: Readonly<Record<number, string>> = {
    0: "Stat: AC vs. Damage Type Modifier",
    1: "Stat: Attacks Per Round Modifier",
    2: "Cure: Sleep",
    3: "State: Berserking",
    4: "Cure: Berserking",
    5: "Charm: Charm Specific Creature",
    6: "Stat: Charisma Modifier",
    7: "Colour: Set Character colours by Palette",
    8: "Colour: Change by RGB",
    9: "Colour: Glow Pulse",
    10: "Stat: Constitution Modifier",
    11: "Cure: Poison",
    12: "HP: Damage",
    13: "Death: Instant Death",
    14: "Graphics: Defrost",
    15: "Stat: Dexterity Modifier",
    16: "State: Haste",
    17: "HP: Current HP Modifier",
    18: "HP: Maximum HP Modifier",
    19: "Stat: Intelligence Modifier",
    20: "State: Invisibility",
    21: "Stat: Lore Modifier",
    22: "Stat: Cumulative Luck Bonus",
    23: "Stat: Morale Modifier",
    24: "State: Horror",
    25: "State: Poison",
    26: "Item: Remove Curse",
    27: "Stat: Acid Resistance Modifier",
    28: "Stat: Cold Resistance Modifier",
    29: "Stat: Electricity Resistance Modifier",
    30: "Stat: Fire Resistance Modifier",
    31: "Stat: Magic Damage Resistance Modifier",
    32: "Cure: Death (Raise Dead)",
    33: "Stat: Save vs. Death Modifier",
    34: "Stat: Save vs. Wands Modifier",
    35: "Stat: Save vs. Petrification/Polymorph Modifier",
    36: "Stat: Save vs. Breath Weapons Modifier",
    37: "Stat: Save vs. Spells Modifier",
    38: "State: Silence",
    39: "State: Unconsciousness",
    40: "State: Slow",
    41: "Graphics: Sparkle",
    42: "Spell: Wizard Spell Slots Modifier",
    43: "Cure: Stone to Flesh",
    44: "Stat: Strength Modifier",
    45: "State: Stun",
    46: "Cure: Stun (Unstun)",
    47: "Cure: Invisibility",
    48: "Cure: Silence (Vocalize)",
    49: "Stat: Wisdom Modifier",
    50: "Colour: Glow by RGB (Brief)",
    51: "Colour: Strong/Dark by RGB",
    52: "Colour: Very Bright by RGB",
    53: "Graphics: Animation Change",
    54: "Stat: THAC0 Modifier",
    55: "Death: Kill Creature Type",
    56: "Alignment: Invert",
    57: "Alignment: Change",
    58: "Cure: Dispellable Effects (Dispel Magic)",
    59: "Stat: Stealth Modifier",
    60: "Stat: Miscast Magic",
    61: "Crash",
    62: "Spell: Priest Spell Slots Modifier",
    63: "State: Infravision",
    64: "State: Remove Infravision",
    65: "Overlay: Blur",
    66: "Graphics: Transparency Fade",
    67: "Summon: Creature Summoning",
    68: "Summon: Unsummon Creature",
    69: "Protection: From Detection (Non-Detection)",
    70: "Cure: Non-Detection",
    71: "IDS: Sex Change",
    72: "IDS: Set IDS State",
    73: "Damage Mod",
    74: "State: Blindness",
    75: "Cure: Blindness",
    76: "State: Feeblemindedness",
    77: "Cure: Feeblemindedness",
    78: "State: Disease",
    79: "Cure: Disease",
    80: "State: Deafness",
    81: "Cure: Deafness",
    82: "Set AI Script",
    83: "Protection: From Projectile",
    84: "Stat: Magical Fire Resistance Modifier",
    85: "Stat: Magical Cold Resistance Modifier",
    86: "Stat: Slashing Resistance Modifier",
    87: "Stat: Crushing Resistance Modifier",
    88: "Stat: Piercing Resistance Modifier",
    89: "Stat: Missiles Resistance Modifier",
    90: "Stat: Open Locks Modifier",
    91: "Stat: Find Traps Modifier",
    92: "Stat: Pick Pockets Modifier",
    93: "Stat: Fatigue Modifier",
    94: "Stat: Drunkenness Modifier",
    95: "Stat: Tracking Skill Modifier",
    96: "Stat: Level Change",
    97: "Stat: Exceptional Strength Modifier",
    98: "HP: Regeneration",
    99: "Spell Effect: Duration Modifier",
    100: "Protection: from Creature Type",
    101: "Protection: from Opcode",
    102: "Spell: Immunity (by Power Level)",
    103: "Text: Change Name",
    104: "Stat: Experience Points",
    105: "Stat: Gold",
    106: "Stat: Morale Break Modifier",
    107: "Portrait Change",
    108: "Stat: Reputation",
    109: "State: Hold",
    110: "Empty:",
    111: "Item: Create Magical Weapon",
    112: "Item: Remove Item",
    113: "Empty:",
    114: "Graphics: Dither",
    115: "Detect: Alignment",
    116: "State: Cure Invisibility",
    117: "Spell Effect: Reveal Area",
    118: "Empty:",
    119: "Spell Effect: Mirror Image",
    120: "Protection: from Weapons",
    121: "Empty:",
    122: "Item: Create Inventory Item",
    123: "Item: Remove Inventory Item",
    124: "Spell Effect: Teleport (Dimension Door)",
    125: "Spell Effect: Unlock (Knock)",
    126: "Stat: Movement Modifier",
    127: "Summon: Monster Summoning",
    128: "State: Confusion",
    129: "State: Aid",
    130: "State: Bless",
    131: "State: Positive Chant",
    132: "State: Raise Strength, Constitution, & Dexterity Non-Cumulative",
    133: "Spell Effect: Luck Non-Cumulative",
    134: "State: Petrification",
    135: "Graphics: Polymorph into Specific",
    136: "State: Force Visible",
    137: "State: Negative Chant",
    138: "Graphics: Character Animation Change",
    139: "Text: Display String",
    140: "Graphics: Casting Glow",
    141: "Graphics: Lighting Effects",
    142: "Graphics: Display Special Effect Icon",
    143: "Item: Create Item in Slot",
    144: "Button: Disable Button",
    145: "Spell: Disable Spell Casting Abilities",
    146: "Spell: Cast Spell (at Creature)",
    147: "Spell: Learn Spell",
    148: "Spell: Cast Spell (at Point)",
    149: "(Identify)",
    150: "Spell Effect: Find Traps",
    151: "Summon: Replace Creature",
    152: "Spell Effect: Play Movie",
    153: "Overlay: Sanctuary",
    154: "Overlay: Entangle",
    155: "Overlay: Minor Globe",
    156: "Overlay: Protection from Normal Missiles Cylinder",
    157: "State: Web Effect",
    158: "Overlay: Grease",
    159: "Spell Effect: Mirror Image (Exact Number)",
    160: "Remove Sanctuary",
    161: "Cure: Horror",
    162: "Cure: Hold",
    163: "Protection: Free Action",
    164: "Cure: Drunkeness",
    165: "Spell Effect: Pause Target",
    166: "Stat: Magic Resistance Modifier",
    167: "Stat: THAC0 Modifier with Missile Weapons",
    168: "Summon: Remove Creature",
    169: "Graphics: Prevent Special Effect Icon",
    170: "Graphics: Play Damage Animation",
    171: "Spell: Give Ability",
    172: "Spell: Remove Spell",
    173: "Stat: Poison Resistance Modifier",
    174: "Spell Effect: Play Sound Effect",
    175: "State: Hold",
    176: "Stat: Movement Modifier (II)",
    177: "Use EFF File",
    178: "Spell Effect: THAC0 vs. Creature Type Modifier",
    179: "Spell Effect: Damage vs. Creature Type Modifier",
    180: "Item: Can't Use Item",
    181: "Item: Can't Use Itemtype",
    182: "Item: Apply Effect Item",
    183: "Item: Apply Effect Itemtype",
    184: "Graphics: Passwall (Don't Jump)",
    185: "State: Hold (II)",
    186: "Script: MoveToArea",
    187: "Script: Store Local Variable",
    188: "Spell Effect: Aura Cleansing",
    189: "Stat: Casting Time Modifier",
    190: "Stat: Attack Speed Factor",
    191: "Spell: Casting Level Modifier",
    192: "Spell Effect: Find Familiar",
    193: "Spell Effect: Invisible Detection by Script",
    194: "Ignore Dialog Pause",
    195: "Spell Effect: Death Dependent Constitution Loss (Familiar Bond)",
    196: "Spell Effect: Familiar Block",
    197: "Spell: Bounce (by Impact Projectile)",
    198: "Spell: Bounce (by Opcode)",
    199: "Spell: Bounce (by Power Level)",
    200: "Spell: Bounce (by Power level, decrementing)",
    201: "Spell: Immunity (by Power Level, decrementing)",
    202: "Spell: Bounce (by School)",
    203: "Spell: Bounce (by Secondary Type)",
    204: "Spell: Protection (by School)",
    205: "Spell: Protection (by Secondary Type)",
    206: "Spell: Protection from Spell",
    207: "Spell: Bounce (by Resource)",
    208: "HP: Minimum Limit",
    209: "Death: Kill 60HP",
    210: "Spell Effect: Stun 90HP",
    211: "Spell Effect: Imprisonment",
    212: "Protection: Freedom",
    213: "Spell Effect: Maze",
    214: "Spell Effect: Select Spell",
    215: "Graphics: Play 3D Effect",
    216: "Spell Effect: Level Drain",
    217: "Spell Effect: Unconsciousness 20HP",
    218: "Protection: Stoneskin",
    219: "Stat: AC vs. Creature Type Modifier",
    220: "Removal: Remove School",
    221: "Removal: Remove Secondary Type",
    222: "Spell Effect: Teleport Field",
    223: "Spell: Immunity (by School, decrementing)",
    224: "Cure: Level Drain (Restoration)",
    225: "Spell: Reveal Magic",
    226: "Spell: Immunity (by Secondary Type, decrementing)",
    227: "Spell: Bounce (by School, decrementing)",
    228: "Spell: Bounce (by Secondary Type, decrementing)",
    229: "Removal: Remove One School",
    230: "Removal: Remove One Secondary Type",
    231: "Spell Effect: Time Stop",
    232: "Spell Effect: Cast Spell on Condition",
    233: "Stat: Proficiency Modifier",
    234: "Spell Effect: Contingency Creation",
    235: "Graphics: Icewind Casting Glow",
    236: "Spell Effect: Image Projection",
    237: "Spell Effect: Puppet ID",
    238: "Stat: Save vs. all",
    239: "Spell Effect: Farsight",
    240: "Graphics: Remove Special Effect Icon",
    241: "HP: Vampiric Touch",
    242: "Cure: Confusion",
    243: "Item: Drain Item Charges",
    244: "Spell: Drain Wizard Spell",
    245: "Check For Berserk",
    246: "Spell Effect: Berserking",
    247: "Spell Effect: Attack Nearest Creature",
    248: "Item: Set Melee Effect",
    249: "Item: Set Ranged Effect",
    250: "Spell Effect: Damage Modifier",
    251: "Spell Effect: Change Bard Song Effect",
    252: "Spell Effect: Set Trap",
    253: "Spell Effect: Add Map Marker",
    254: "Spell Effect: Remove Map Marker",
    255: "Item: Create Inventory Item (days)",
    256: "Spell Effect: Umber Hulk Gaze",
    257: "(Zombie Lord Aura)",
    258: "Spell: Spell Sequencer Activation",
    259: "Protection: Spell Trap (by Power Level, decrementing)",
    260: "Spell: Spell Sequencer Activation",
    261: "Protection: Immunity Effect and Resource",
    262: "Stat: Visual Range",
    263: "Stat: Backstab",
    264: "Spell Effect: Drop Weapons in Panic",
    265: "Script: Modify Global Variable",
    266: "Spell: Remove Protection from Spell",
    267: "Text: Protection from Display Specific String",
    268: "Spell Effect: Clear Fog of War (Wizard Eye)",
    269: "Spell Effect: Shake Window",
    270: "Cure: Unpause Target",
    271: "Graphics: Avatar Removal",
    272: "Spell: Apply Repeating EFF",
    273: "Remove: Specific Area Effect(Zone of Sweet Air)",
    274: "Spell Effect: Teleport to Target",
    275: "Spell Effect: Remove Seven Eyes",
    276: "Stat: Detect Illusion Modifier",
    277: "Stat: Set Traps Modifier",
    278: "Spell Effect: Shroud of Flame",
    279: "Spell Effect: Animal Rage",
    280: "Spell Effect: Turn Undead",
    281: "Stat: Wild Magic",
    282: "HP: Suppress HP Info",
    283: "Text: Float Text",
    284: "Stat: Melee THAC0 Modifier",
    285: "Stat: Melee Weapon Damage Modifier",
    286: "Stat: Missile Weapon Damage Modifier",
    287: "Graphics: Selection Circle Removal",
    288: "Stat: Fist THAC0 Modifier",
    289: "Stat: Fist Damage Modifier",
    290: "Text: Change Title",
    291: "Graphics: Disable Visual Effect",
    292: "Protection: Backstab",
    293: "Spell Effect: Beholder Dispel Magic",
    294: "Spell Effect: Existance Delay Override",
    295: "Spell Effect: Jackalwere Gaze",
    296: "Script: Set Global Variable",
    297: "Spell Effect: Immunity to Turn Undead",
    298: "Spell Effect: Execute Script cut250a",
    299: "Spell Effect: Chaos Shield",
    300: "Spell Effect: NPCBump",
    301: "Stat: Critical Hit Modifier",
    302: "Item: Can Use Any Item",
    303: "Spell Effect: Backstab Every Hit",
    304: "Mass Raise Dead",
    305: "Stat: THAC0 Modifier (Off-Hand)",
    306: "Stat: THAC0 Modifier (On-Hand)",
    307: "Ranger Tracking Ability",
    308: "Protection: From Tracking",
    309: "Script: Modify Local Variable",
    310: "Protection: from Timestop",
    311: "Spell: Random Wish Spell",
    312: "Crash",
    313: "High-Level Ability Denotation",
    314: "Spell: Golem Stoneskin",
    315: "Graphics: Animation Removal",
    316: "Spell: Magical Rest",
    317: "State: Haste 2",
    318: "Protection from Resource",
    319: "Usability: Item Usability",
    320: "Change Weather",
    321: "Removal: Effects specified by Resource",
    322: "Evade Area of Effect",
    323: "Stat: Turn Undead Level",
    324: "Protection: Immunity to Resource and Message",
    325: "Stat: Save vs. all",
    326: "Apply Effects List",
    327: "Graphics: Icewind Visual Spell Hit (plays sound)",
    328: "State: Set Extended or Spell State",
    329: "Spell Effect: Slow Poison",
    330: "Text: Float Text",
    331: "Summon: Random Monster Summoning",
    332: "Stat: Specific Damage Modifier",
    333: "Spell Effect: Static Charge",
    334: "Spell Effect: Turn Undead",
    335: "Spell Effect: Seven Eyes",
    336: "Graphics: Display Eyes Overlay",
    337: "Remove: Opcode",
    338: "Disable Rest",
    339: "Alter Animation",
    340: "Spell Effect: Change Backstab Effect",
    341: "Spell Effect: Change Critical Hit Effect",
    342: "Animation: Override Data",
    343: "HP Swap",
    344: "Enchantment vs. creature type",
    345: "Enchantment bonus",
    346: "Save vs. school bonus",
    347: "Unused",
    348: "Unused",
    349: "Unused",
    350: "Unused",
    351: "Unused",
    352: "Unused",
    353: "Unused",
    354: "Unused",
    355: "Unused",
    356: "Unused",
    357: "Unused",
    358: "Unused",
    359: "Unused",
    360: "Stat: Ignore Reputation Breaking Point",
    361: "Cast spell on critical miss",
    362: "Critical miss bonus",
    363: "Modal state check",
    364: "Empty",
    365: "Make unselectable",
    366: "Spell: Apply Spell On Move",
    367: "Minimum base stats",
    368: "Play BAM with expiration effect",
    369: "Play BAM File Blended and Sticky",
    370: "Play BAM file",
    371: "Play BAM file",
    372: "Play BAM file",
    373: "Play BAM file",
    374: "Special spell hit",
    375: "Play BAM with effects",
    376: "Spell Effect: Detect Evil",
    377: "Speak with Dead",
    378: "Prayer (Non-cumulative)",
    379: "Curse (Non-cumulative)",
    380: "Embalm (Non-cumulative)",
    381: "Induce Hiccups",
    382: "Fist of Iron",
    383: "Hit Point Transfer",
    400: "State: Hopelessness",
    401: "State: Protection from Evil",
    402: "Add Effects List",
    403: "State: Armor of Faith",
    404: "State: Nausea",
    405: "State: Enfeeblement",
    406: "State: Fireshield",
    407: "State: Death Ward",
    408: "State: Holy Power",
    409: "State: Righteous Wrath of the Faithful",
    410: "Summon (as ally)",
    411: "Summon (as enemy)",
    412: "State: Control",
    413: "Icewind Visual Effect",
    414: "State: Otiluke's Resilient Sphere",
    415: "State: Barkskin",
    416: "State: Bleeding Wounds",
    417: "Area Effect Using Effects List",
    418: "State: Free Action",
    419: "State: Unconsciousness",
    420: "Spell Effect: Death Magic",
    421: "State: Entropy Shield",
    422: "State: Storm Shell",
    423: "State: Protection from the Elements",
    424: "State: Hold Undead",
    425: "State: Control Undead",
    426: "State: Aegis",
    427: "State: Executioner's Eyes",
    428: "Banish",
    429: "When Struck Using Effects List",
    430: "Projectile Type Using Effects List",
    431: "State: Energy Drain",
    432: "State: Tortoise Shell",
    433: "State: Blink",
    434: "Persistant Using Effects List",
    435: "Spell Effect: Day Blindness",
    436: "Spell Effect: Damage Reduction",
    437: "Disguise",
    438: "Spell Effect: Heroic Inspiration",
    439: "Script: Prevent AI Slow Down 439]",
    440: "Spell Effect: Babarian Rage",
    441: "Stat: Movement Modifier",
    442: "Feat: Cleave",
    443: "State: Protection from Arrows",
    444: "State: Tenser's Transformation",
    445: "Charm: Slippery Mind",
    446: "Spell Effect: Smite Evil",
    447: "Cure: Restoration",
    448: "Spell Effect: Alicorn Lance Glow",
    449: "Spell Effect: Call Lightning",
    450: "State: Globe of Invulnerability",
    451: "State: Lower Resistance",
    452: "State: Bane",
    453: "Spell Effect: Power Attack",
    454: "Spell Effect: Expertise",
    455: "Spell Effect: Arterial Strike",
    456: "Spell Effect: Hamstring",
    457: "Spell Effect: Rapid Shot",
};
