// Auto-generated from IESDP _opcodes/opNNN.html. Do not hand-edit.

/**
 * Effect / EFF body opcode -> display name. Sourced from IESDP `_opcodes/op<NNN>.html`
 * frontmatter `opname` fields (canonical files only, not engine-variant overrides).
 */
export const Opcodes: Readonly<Record<number, string>> = {
    0: "Stat: AC vs. Damage Type Modifier",
    1: "Stat: Attacks Per Round Modifier",
    2: "Cure: Sleep",
    3: "State: Berserking",
    4: "Cure: Berserking",
    5: "Charm: Charm Specific Creature",
    6: "Stat: Charisma Modifier",
    7: "Colour: Set Character colours by Palette",
    8: "Colour: Change by RGB",
    9: "Colour: Glow Pulse",
    10: "Stat: Constitution Modifier",
    11: "Cure: Poison",
    12: "HP: Damage",
    13: "Death: Instant Death",
    15: "Stat: Dexterity Modifier",
    16: "State: Haste",
    17: "HP: Current HP Modifier",
    18: "HP: Maximum HP Modifier",
    19: "Stat: Intelligence Modifier",
    20: "State: Invisibility",
    21: "Stat: Lore Modifier",
    22: "Stat: Cumulative Luck Bonus",
    23: "Stat: Morale Modifier",
    24: "State: Horror",
    25: "State: Poison",
    26: "Item: Remove Curse",
    27: "Stat: Acid Resistance Modifier",
    28: "Stat: Cold Resistance Modifier",
    29: "Stat: Electricity Resistance Modifier",
    30: "Stat: Fire Resistance Modifier",
    31: "Stat: Magic Damage Resistance Modifier",
    32: "Cure: Death (Raise Dead)",
    33: "Stat: Save vs. Death Modifier",
    34: "Stat: Save vs. Wands Modifier",
    35: "Stat: Save vs. Petrification/Polymorph Modifier",
    36: "Stat: Save vs. Breath Weapons Modifier",
    37: "Stat: Save vs. Spells Modifier",
    38: "State: Silence",
    39: "State: Unconsciousness",
    40: "State: Slow",
    41: "Graphics: Sparkle",
    42: "Spell: Wizard Spell Slots Modifier",
    43: "Cure: Stone to Flesh",
    44: "Stat: Strength Modifier",
    45: "State: Stun",
    46: "Cure: Stun (Unstun)",
    47: "Cure: Invisibility",
    48: "Cure: Silence (Vocalize)",
    49: "Stat: Wisdom Modifier",
    50: "Colour: Glow by RGB (Brief)",
    51: "Colour: Strong/Dark by RGB",
    52: "Colour: Very Bright by RGB",
    53: "Graphics: Animation Change",
    54: "Stat: THAC0 Modifier",
    55: "Death: Kill Creature Type",
    56: "Alignment: Invert",
    57: "Alignment: Change",
    58: "Cure: Dispellable Effects (Dispel Magic)",
    59: "Stat: Stealth Modifier",
    60: "Stat: Miscast Magic",
    61: "Crash",
    62: "Spell: Priest Spell Slots Modifier",
    63: "State: Infravision",
    64: "State: Remove Infravision",
    65: "Overlay: Blur",
    66: "Graphics: Transparency Fade",
    67: "Summon: Creature Summoning",
    68: "Summon: Unsummon Creature",
    69: "Protection: From Detection (Non-Detection)",
    70: "Cure: Non-Detection",
    71: "IDS: Sex Change",
    72: "IDS: Set IDS State",
    73: "Damage Mod",
    74: "State: Blindness",
    75: "Cure: Blindness",
    76: "State: Feeblemindedness",
    77: "Cure: Feeblemindedness",
    79: "Cure: Disease",
    80: "State: Deafness",
    81: "Cure: Deafness",
    82: "Set AI Script",
    83: "Protection: From Projectile",
    84: "Stat: Magical Fire Resistance Modifier",
    85: "Stat: Magical Cold Resistance Modifier",
    86: "Stat: Slashing Resistance Modifier",
    87: "Stat: Crushing Resistance Modifier",
    88: "Stat: Piercing Resistance Modifier",
    89: "Stat: Missiles Resistance Modifier",
    90: "Stat: Open Locks Modifier",
    91: "Stat: Find Traps Modifier",
    92: "Stat: Pick Pockets Modifier",
    93: "Stat: Fatigue Modifier",
    94: "Stat: Drunkenness Modifier",
    95: "Stat: Tracking Skill Modifier",
    96: "Stat: Level Change",
    97: "Stat: Exceptional Strength Modifier",
    98: "HP: Regeneration",
    99: "Spell Effect: Duration Modifier",
    100: "Protection: from Creature Type",
    101: "Protection: from Opcode",
    102: "Spell: Immunity (by Power Level)",
    103: "Text: Change Name",
    104: "Stat: Experience Points",
    105: "Stat: Gold",
    106: "Stat: Morale Break Modifier",
    107: "Portrait Change",
    108: "Stat: Reputation",
    109: "State: Hold",
    110: "Empty:",
    111: "Item: Create Magical Weapon",
    112: "Item: Remove Item",
    113: "Empty:",
    114: "Graphics: Dither",
    115: "Detect: Alignment",
    116: "State: Cure Invisibility",
    117: "Spell Effect: Reveal Area",
    118: "Empty:",
    119: "Spell Effect: Mirror Image",
    120: "Protection: from Weapons",
    121: "Empty:",
    122: "Item: Create Inventory Item",
    123: "Item: Remove Inventory Item",
    124: "Spell Effect: Teleport (Dimension Door)",
    125: "Spell Effect: Unlock (Knock)",
    126: "Stat: Movement Modifier",
    127: "Summon: Monster Summoning",
    128: "State: Confusion",
    129: "State: Aid",
    130: "State: Bless",
    131: "State: Positive Chant",
    132: "State: Raise Strength, Constitution, & Dexterity Non-Cumulative",
    133: "Spell Effect: Luck Non-Cumulative",
    134: "State: Petrification",
    135: "Graphics: Polymorph into Specific",
    136: "State: Force Visible",
    137: "State: Negative Chant",
    138: "Graphics: Character Animation Change",
    139: "Text: Display String",
    140: "Graphics: Casting Glow",
    141: "Graphics: Lighting Effects",
    142: "Graphics: Display Special Effect Icon",
    143: "Item: Create Item in Slot",
    144: "Button: Disable Button",
    145: "Spell: Disable Spell Casting Abilities",
    146: "Spell: Cast Spell (at Creature)",
    147: "Spell: Learn Spell",
    148: "Spell: Cast Spell (at Point)",
    149: "(Identify)",
    150: "Spell Effect: Find Traps",
    151: "Summon: Replace Creature",
    152: "Spell Effect: Play Movie",
    153: "Overlay: Sanctuary",
    154: "Overlay: Entangle",
    155: "Overlay: Minor Globe",
    156: "Overlay: Protection from Normal Missiles Cylinder",
    157: "State: Web Effect",
    158: "Overlay: Grease",
    159: "Spell Effect: Mirror Image (Exact Number)",
    160: "Remove Sanctuary",
    161: "Cure: Horror",
    162: "Cure: Hold",
    163: "Protection: Free Action",
    164: "Cure: Drunkeness",
    165: "Spell Effect: Pause Target",
    166: "Stat: Magic Resistance Modifier",
    167: "Stat: THAC0 Modifier with Missile Weapons",
    168: "Summon: Remove Creature",
    169: "Graphics: Prevent Special Effect Icon",
    170: "Graphics: Play Damage Animation",
    171: "Spell: Give Ability",
    172: "Spell: Remove Spell",
    173: "Stat: Poison Resistance Modifier",
    174: "Spell Effect: Play Sound Effect",
    175: "State: Hold",
    176: "Stat: Movement Modifier (II)",
    178: "Spell Effect: THAC0 vs. Creature Type Modifier",
    179: "Spell Effect: Damage vs. Creature Type Modifier",
    180: "Item: Can't Use Item",
    182: "Item: Apply Effect Item",
    183: "Item: Apply Effect Itemtype",
    184: "Graphics: Passwall (Don't Jump)",
    186: "Script: MoveToArea",
    187: "Script: Store Local Variable",
    188: "Spell Effect: Aura Cleansing",
    189: "Stat: Casting Time Modifier",
    190: "Stat: Attack Speed Factor",
    192: "Spell Effect: Find Familiar",
    193: "Spell Effect: Invisible Detection by Script",
    194: "Ignore Dialog Pause",
    195: "Spell Effect: Death Dependent Constitution Loss (Familiar Bond)",
    196: "Spell Effect: Familiar Block",
    197: "Spell: Bounce (by Impact Projectile)",
    198: "Spell: Bounce (by Opcode)",
    199: "Spell: Bounce (by Power Level)",
    200: "Spell: Bounce (by Power level, decrementing)",
    201: "Spell: Immunity (by Power Level, decrementing)",
    202: "Spell: Bounce (by School)",
    203: "Spell: Bounce (by Secondary Type)",
    204: "Spell: Protection (by School)",
    205: "Spell: Protection (by Secondary Type)",
    206: "Spell: Protection from Spell",
    207: "Spell: Bounce (by Resource)",
    208: "HP: Minimum Limit",
    209: "Death: Kill 60HP",
    210: "Spell Effect: Stun 90HP",
    211: "Spell Effect: Imprisonment",
    212: "Protection: Freedom",
    213: "Spell Effect: Maze",
    214: "Spell Effect: Select Spell",
    215: "Graphics: Play 3D Effect",
    216: "Spell Effect: Level Drain",
    217: "Spell Effect: Unconsciousness 20HP",
    220: "Removal: Remove School",
    221: "Removal: Remove Secondary Type",
    222: "Spell Effect: Teleport Field",
    223: "Spell: Immunity (by School, decrementing)",
    224: "Cure: Level Drain (Restoration)",
    225: "Spell: Reveal Magic",
    226: "Spell: Immunity (by Secondary Type, decrementing)",
    227: "Spell: Bounce (by School, decrementing)",
    228: "Spell: Bounce (by Secondary Type, decrementing)",
    229: "Removal: Remove One School",
    230: "Removal: Remove One Secondary Type",
    231: "Spell Effect: Time Stop",
    233: "Stat: Proficiency Modifier",
    234: "Spell Effect: Contingency Creation",
    235: "Graphics: Icewind Casting Glow",
    236: "Spell Effect: Image Projection",
    237: "Spell Effect: Puppet ID",
    238: "Stat: Save vs. all",
    239: "Spell Effect: Farsight",
    240: "Graphics: Remove Special Effect Icon",
    241: "HP: Vampiric Touch",
    242: "Cure: Confusion",
    244: "Spell: Drain Wizard Spell",
    245: "Check For Berserk",
    246: "Spell Effect: Berserking",
    247: "Spell Effect: Attack Nearest Creature",
    248: "Item: Set Melee Effect",
    249: "Item: Set Ranged Effect",
    250: "Spell Effect: Damage Modifier",
    251: "Spell Effect: Change Bard Song Effect",
    252: "Spell Effect: Set Trap",
    253: "Spell Effect: Add Map Marker",
    254: "Spell Effect: Remove Map Marker",
    255: "Item: Create Inventory Item (days)",
    256: "Spell Effect: Umber Hulk Gaze",
    257: "(Zombie Lord Aura)",
    258: "Spell: Spell Sequencer Activation",
    259: "Protection: Spell Trap (by Power Level, decrementing)",
    261: "Protection: Immunity Effect and Resource",
    262: "Stat: Visual Range",
    263: "Stat: Backstab",
    264: "Spell Effect: Drop Weapons in Panic",
    265: "Script: Modify Global Variable",
    266: "Spell: Remove Protection from Spell",
    267: "Text: Protection from Display Specific String",
    268: "Spell Effect: Clear Fog of War (Wizard Eye)",
    269: "Spell Effect: Shake Window",
    270: "Cure: Unpause Target",
    271: "Graphics: Avatar Removal",
    272: "Spell: Apply Repeating EFF",
    273: "Remove: Specific Area Effect(Zone of Sweet Air)",
    274: "Spell Effect: Teleport to Target",
    275: "Spell Effect: Remove Seven Eyes",
    276: "Stat: Detect Illusion Modifier",
    277: "Stat: Set Traps Modifier",
    278: "Spell Effect: Shroud of Flame",
    279: "Spell Effect: Animal Rage",
    280: "Spell Effect: Turn Undead",
    281: "Stat: Wild Magic",
    282: "HP: Suppress HP Info",
    283: "Text: Float Text",
    284: "Stat: Melee THAC0 Modifier",
    285: "Stat: Melee Weapon Damage Modifier",
    286: "Stat: Missile Weapon Damage Modifier",
    287: "Graphics: Selection Circle Removal",
    288: "Stat: Fist THAC0 Modifier",
    289: "Stat: Fist Damage Modifier",
    290: "Text: Change Title",
    292: "Protection: Backstab",
    293: "Spell Effect: Beholder Dispel Magic",
    294: "Spell Effect: Existance Delay Override",
    295: "Spell Effect: Jackalwere Gaze",
    296: "Script: Set Global Variable",
    297: "Spell Effect: Immunity to Turn Undead",
    298: "Spell Effect: Execute Script cut250a",
    299: "Spell Effect: Chaos Shield",
    300: "Spell Effect: NPCBump",
    302: "Item: Can Use Any Item",
    303: "Spell Effect: Backstab Every Hit",
    304: "Mass Raise Dead",
    305: "Stat: THAC0 Modifier (Off-Hand)",
    306: "Stat: THAC0 Modifier (On-Hand)",
    307: "Ranger Tracking Ability",
    308: "Protection: From Tracking",
    309: "Script: Modify Local Variable",
    310: "Protection: from Timestop",
    311: "Spell: Random Wish Spell",
    312: "Crash",
    313: "High-Level Ability Denotation",
    314: "Spell: Golem Stoneskin",
    315: "Graphics: Animation Removal",
    316: "Spell: Magical Rest",
    317: "State: Haste 2",
};
