// Auto-generated from IESDP _opcodes/opNNN.html. Do not hand-edit.

/** One opcode-dependent field's display data: what to call it, and the values it is known to take. */
export interface OpcodeSlot {
    label?: string;
    enum?: Readonly<Record<number, string>>;
}

export interface OpcodeRelationship {
    param1?: OpcodeSlot;
    param2?: OpcodeSlot;
    /** EE-era extra parameters; present only for the minority of opcodes that read them. */
    param3?: OpcodeSlot;
    param4?: OpcodeSlot;
    param5?: OpcodeSlot;
    /** The dword the spec calls a TobEx stacking id, which these opcodes read as their own field. */
    special?: OpcodeSlot;
    savingthrow?: OpcodeSlot;
    power?: OpcodeSlot;
    availability?: Readonly<Record<string, boolean>>;
    /**
     * For the opcodes that read parameter1 as an entry in an IDS file parameter2 SELECTS: parameter2's
     * stored value -> the candidate tables it names, most preferred first (every present one contributes
     * and the earlier wins a shared key, since editions disagree - ALIGN vs ALIGNMEN). The mapping is per
     * opcode, not shared: 72 is 0-based where 55/100/175 are 2-based, and 178's slot 2 is OBJECT not EA.
     */
    idsFileByParam2?: Readonly<Record<number, readonly string[]>>;
    /**
     * What the effect's `resource` resref points at, as a resource-type extension. Declared only where
     * every IESDP page for the opcode agrees; where engines disagree about the target the field stays
     * unresolved rather than resolving against the wrong type.
     */
    resourceType?: string;
}

export const OpcodeRelationships: Readonly<Record<number, OpcodeRelationship>> = {
    0: { param1: { label: "AC Modifier" }, param2: { label: "Type", enum: { 0: "All", 1: "Crushing", 2: "Missile", 4: "Piercing", 8: "Slashing", 16: "Base AC Setting" } }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    1: { param1: { label: "Key Modifier" }, param2: { label: "Type", enum: { 0: "Cumulative Modifier", 1: "Flat Value Modifier", 2: "Percentage Modifier", 3: "Cumulative Modifier" } }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    2: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    3: { param1: { label: "Irrelevant" }, param2: { label: "Type", enum: { 0: "Default/In Combat", 1: "Constant", 2: "Blood Rage" } }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    4: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    5: { param1: { label: "General Type" }, param2: { label: "Charm Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    6: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    7: { param1: { label: "Gradient Number" }, param2: { label: "Location" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    8: { param1: { label: "RGB colour" }, param2: { label: "Location" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    9: { param1: { label: "RGB Colour" }, param2: { label: "Location and Speed" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    10: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    11: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    12: { param1: { label: "Damage Amount" }, param2: { label: "Mode & Damage Type" }, special: { label: "Flags" }, savingthrow: { label: "Save Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    13: { param1: { label: "Text Notification" }, param2: { label: "Death Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    14: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    15: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    16: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    17: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    18: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, special: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    19: { param1: { label: "Statistic Modifier" }, param2: { label: "Type", enum: { 0: "Cumulative Modifier", 1: "Flat Value Modifier", 2: "Percentage Modifier" } }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    20: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    21: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    22: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    23: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, special: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    24: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    25: { param1: { label: "Amount_1" }, param2: { label: "Type", enum: { 0: "1 HP per second (nonzero amount)", 1: "1 HP per second (amount > 1)", 2: "Damage Amount per second", 3: "1 HP every Damage Amount seconds" } }, param3: { label: "Amount_2" }, param4: { label: "Frequency Multiplier" }, special: { label: "Icon" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    26: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    27: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    28: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    29: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    30: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    31: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    32: { param1: { label: "Irrelevant" }, param2: { label: "Restore creature animation?" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    33: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    34: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    35: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    36: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    37: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    38: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    39: { param1: { label: "Irrelevant" }, param2: { label: "Wake on Damage?", enum: { 0: "Yes", 1: "No" } }, special: { label: "Icon" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    40: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    41: { param1: { label: "Colour" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    42: { param1: { label: "Slot Amount Modifier" }, param2: { label: "Spell Level" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    43: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    44: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    45: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    46: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    47: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    48: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    49: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    50: { param1: { label: "RGB Colour" }, param2: { label: "Location and Speed" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    51: { param1: { label: "RGB Colour" }, param2: { label: "Location" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    52: { param1: { label: "RGB Colour" }, param2: { label: "Location" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    53: { param1: { label: "Animation ID" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    54: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    55: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    56: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    57: { param1: { label: "Irrelevant" }, param2: { label: "Alignment" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    58: { param1: { label: "Level" }, param2: { label: "Dispel Type & Magic Weapon Dispel Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    59: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    60: { param1: { label: "Percent Chance" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    61: { param1: { label: "RGB Colour" }, param2: { label: "Location and Fade Speed" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    62: { param1: { label: "Slot Amount Modifier" }, param2: { label: "Spell Level" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    63: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    64: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    65: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    66: { param1: { label: "Fade Amount" }, param2: { label: "Visual Effect" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    67: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "CRE" },
    68: { param1: { label: "Text Notification" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    69: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    70: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    71: { param1: { label: "Gender Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    72: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, idsFileByParam2: { 0: ["EA"], 1: ["GENERAL"], 2: ["RACE"], 3: ["CLASS"], 4: ["SPECIFIC"], 5: ["GENDER"], 6: ["ALIGN", "ALIGNMEN"] } },
    73: { param1: { label: "Statistic Modifier" }, param2: { label: "Modifier Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    74: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    75: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    76: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    77: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    78: { param1: { label: "Amount" }, param2: { label: "Type" }, param4: { label: "Frequency Multiplier" }, special: { label: "Icon" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    79: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    80: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    81: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    82: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "BCS" },
    83: { param1: { label: "Irrelevant" }, param2: { label: "Projectile Index" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    84: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    85: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    86: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    87: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    88: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    89: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    90: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    91: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    92: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    93: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    94: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    95: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    96: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    97: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    98: { param1: { label: "Amount_1" }, param2: { label: "Type" }, param3: { label: "Amount_2" }, param4: { label: "Frequency Multiplier" }, special: { label: "Icon" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    99: { param1: { label: "Duration Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    100: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    101: { param1: { label: "Irrelevant" }, param2: { label: "Opcode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    102: { param1: { label: "Spell Level" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    103: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    104: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    105: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    106: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    107: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "BMP" },
    108: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    109: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, special: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    110: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    111: { param1: { label: "Amount" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "ITM" },
    112: { param1: { label: "Sound" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "ITM" },
    113: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    114: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    115: { param1: { label: "Irrelevant" }, param2: { label: "Alignment Mask" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    116: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    117: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    118: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    119: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    120: { param1: { label: "Enchantment" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    121: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    122: { param1: { label: "Charges" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "ITM" },
    123: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "ITM" },
    124: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    125: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    126: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    127: { param1: { label: "Number" }, param2: { label: "Type" }, special: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    128: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    129: { param1: { label: "Statistic Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    130: { param1: { label: "Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    131: { param1: { label: "Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    132: { param1: { label: "Statistic Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    133: { param1: { label: "Statistic Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    134: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    135: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "CRE" },
    136: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    137: { param1: { label: "Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    138: { param1: { label: "Irrelevant" }, param2: { label: "Animation Sequence" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    139: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    140: { param1: { label: "Projectile Index" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    141: { param1: { label: "Target" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    142: { param1: { label: "Irrelevant" }, param2: { label: "Icon" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    143: { param1: { label: "Slot" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "ITM" },
    144: { param1: { label: "Irrelevant" }, param2: { label: "Button" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    145: { param1: { label: "Irrelevant" }, param2: { label: "Spell Type" }, special: { label: "Show message?" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    146: { param1: { label: "Casting Level" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    147: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    148: { param1: { label: "Casting Level" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    149: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    150: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    151: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "CRE" },
    152: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    153: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    154: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    155: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    156: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    157: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    158: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    159: { param1: { label: "Amount" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    160: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    161: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    162: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    163: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    164: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    165: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    166: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    167: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    168: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    169: { param1: { label: "Irrelevant" }, param2: { label: "Icon" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    170: { param1: { label: "Irrelevant" }, param2: { label: "Animation" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    171: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    172: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    173: { param1: { label: "Statistic Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    174: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "WAV" },
    175: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"] } },
    176: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    177: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, param3: { label: "Bypass probability / immunities / saving throws" }, param5: { label: "Bypass probability / immunities / saving throws" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] }, resourceType: "EFF" },
    178: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, special: { label: "Statistic Modifier" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true }, idsFileByParam2: { 2: ["OBJECT"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"] } },
    179: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, special: { label: "Statistic Modifier" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    180: { param1: { label: "String Reference" }, param2: { label: "Undefined" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "ITM" },
    181: { param1: { label: "Item Type" }, param2: { label: "Restriction" }, special: { label: "Description note" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    182: { param1: { label: "Unused" }, param2: { label: "Unused" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    183: { param1: { label: "Undetermined" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "EFF" },
    184: { param1: { label: "Undefined" }, param2: { label: "Jump" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    185: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    186: { param1: { label: "Delay" }, param2: { label: "Orientation" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "ARE" },
    187: { param1: { label: "Value" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    188: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    189: { param1: { label: "Speed Modifier" }, param2: { label: "Type" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    190: { param1: { label: "Speed Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: true, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    191: { param1: { label: "Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    192: { param1: { label: "Irrelevant" }, param2: { label: "Upgrade Marker" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    193: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    194: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    195: { param1: { label: "Max HP Modifier" }, param2: { label: "Unused" }, param3: { label: "Master ID (owner)" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    196: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: false, pst: true, pstee: true } },
    197: { param1: { label: "Irrelevant" }, param2: { label: "Impact Projectile" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    198: { param1: { label: "Irrelevant" }, param2: { label: "Opcode" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    199: { param1: { label: "Power Level" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    200: { param1: { label: "Total Amount" }, param2: { label: "Power Level" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    201: { param1: { label: "Total Amount" }, param2: { label: "Power Level" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    202: { param1: { label: "Irrelevant" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    203: { param1: { label: "Irrelevant" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    204: { param1: { label: "Irrelevant" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    205: { param1: { label: "Irrelevant" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    206: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    207: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true }, resourceType: "SPL" },
    208: { param1: { label: "Minimum Value" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    209: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    210: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    211: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    212: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: true, pstee: true } },
    213: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, special: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    214: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "2DA" },
    215: { param1: { label: "Undetermined" }, param2: { label: "Play where?" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    216: { param1: { label: "Amount" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    217: { param1: { label: "Irrelevant" }, param2: { label: "Wake on damage" }, special: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    218: { param1: { label: "Amount" }, param2: { label: "Use Dice?" }, special: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    219: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    220: { param1: { label: "Maximum Level" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    221: { param1: { label: "Maximum Level" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    222: { param1: { label: "Max Range" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    223: { param1: { label: "Total Amount" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    224: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    225: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    226: { param1: { label: "Total Amount" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    227: { param1: { label: "Total Amount" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    228: { param1: { label: "Total Amount" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    229: { param1: { label: "Max Level" }, param2: { label: "School" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    230: { param1: { label: "Max Level" }, param2: { label: "Secondary Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    231: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    232: { param1: { label: "Target" }, param2: { label: "Condition" }, special: { label: "Extra" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    233: { param1: { label: "Amount" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    234: { param1: { label: "Maximum Level Usable" }, param2: { label: "Amount/Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    235: { param1: { label: "Speed" }, param2: { label: "Direction" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    236: { param1: { label: "Undetermined" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    237: { param1: { label: "Master ID" }, param2: { label: "Image Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    238: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    239: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    240: { param1: { label: "Irrelevant" }, param2: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    241: { param1: { label: "Creature ID" }, param2: { label: "Charm Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    242: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    243: { param1: { label: "Amount to Drain" }, param2: { label: "Unused" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "ITM" },
    244: { param1: { label: "Number to Drain" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    245: { param1: { label: "Undefined" }, param2: { label: "Undefined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    246: { param1: { label: "Undetermined" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    247: { param1: { label: "Irrelevant" }, param2: { label: "Constant Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    248: { param1: { label: "Irrelevant" }, param2: { label: "Fist only" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "EFF" },
    249: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "EFF" },
    250: { param1: { label: "Damage Modifier" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    251: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    252: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    253: { param1: { label: "String Reference" }, param2: { label: "Marker Color" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    254: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    255: { param1: { label: "Charges" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "ITM" },
    256: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    257: { param1: { label: "Maximum Level Usable" }, param2: { label: "Amount" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    258: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    259: { param1: { label: "Total Amount" }, param2: { label: "Power Level" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    260: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    261: { param1: { label: "Spell Level" }, param2: { label: "Spell Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    262: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    263: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    264: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    265: { param1: { label: "Value" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    266: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "SPL" },
    267: { param1: { label: "String Reference" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    268: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    269: { param1: { label: "Strength" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    270: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    271: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    272: { param1: { label: "Amount_1" }, param2: { label: "Type" }, param3: { label: "Amount_2" }, param4: { label: "Frequency Multiplier" }, special: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "EFF" },
    273: { param1: { label: "Undetermined" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, resourceType: "2DA" },
    274: { param1: { label: "Undetermined" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    275: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    276: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    277: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    278: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    279: { param1: { label: "Irrelevant" }, param2: { label: "Button" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    280: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    281: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    282: { param1: { label: "Value" }, param2: { label: "Scripting State" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    283: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    284: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    285: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    286: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    287: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    288: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    289: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    290: { param1: { label: "String Reference" }, param2: { label: "Position" }, special: { label: "Class" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    291: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    292: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    293: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    294: { param1: { label: "Undefined" }, param2: { label: "Constant Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    295: { param1: { label: "Undefined" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    296: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: true, iwd2: true, pst: false, pstee: true } },
    297: { param1: { label: "Undefined" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    298: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: true, pst: false, pstee: true } },
    299: { param1: { label: "Shield Amount" }, param2: { label: "Icon" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    300: { param1: { label: "Unknown" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    301: { param1: { label: "Statistic Modifier" }, param2: { label: "Condition" }, param3: { label: "Weapon Category" }, special: { label: "Attack Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    302: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    303: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    304: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    305: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    306: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    307: { param1: { label: "Range" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    308: { param1: { label: "Radius" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    309: { param1: { label: "Value" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    310: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    311: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    312: { param1: { label: "Undefined" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    313: { param1: { label: "Undetermined" }, param2: { label: "Undetermined" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "SPL" },
    314: { param1: { label: "Amount" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    315: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    316: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    317: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    318: { param1: { label: "Value" }, param2: { label: "Stat Type" }, availability: { bg1: false, bg2: true, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    319: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, special: { label: "Description note" }, power: { label: "Usability behavior" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    320: { param1: { label: "Weather" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    321: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    322: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    323: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, special: { label: "Mode" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    324: { param1: { label: "Value" }, param2: { label: "Stat Type" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    325: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    326: { param1: { label: "Value" }, param2: { label: "Stat Type" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "SPL" },
    327: { param1: { label: "Target" }, param2: { label: "Projectile Index" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    328: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, special: { label: "Mode" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    329: { param1: { label: "Slow Factor" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    330: { param1: { label: "Strref" }, param2: { label: "Type" }, param3: { label: "Starting strref" }, special: { label: "Count" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    331: { param1: { label: "Count" }, param2: { label: "Type" }, special: { label: "Mode" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "2DA" },
    332: { param1: { label: "Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    333: { param1: { label: "Number" }, param2: { label: "Level" }, special: { label: "Delay" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "SPL" },
    334: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    335: { param1: { label: "Spellstate" }, param2: { label: "Row#" }, special: { label: "Eye Group" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "SPL" },
    336: { param1: { label: "Sequence" }, param2: { label: "Eye Group" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "BAM" },
    337: { param1: { label: "Param" }, param2: { label: "Opcode" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    338: { param1: { label: "StrRef" }, param2: { label: "Mode" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    339: { param1: { label: "Value and Modifier" }, param2: { label: "Projectile Type" }, special: { label: "Range" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    340: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "SPL" },
    341: { param1: { label: "Irrelevant" }, param2: { label: "Condition" }, param3: { label: "Weapon Category" }, special: { label: "Attack Type" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "SPL" },
    342: { param1: { label: "Value" }, param2: { label: "Field" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    343: { param1: { label: "Irrelevant" }, param2: { label: "Mode" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    344: { param1: { label: "IDS Entry" }, param2: { label: "IDS File" }, param3: { label: "Weapon Slot" }, param4: { label: "Weapon Category" }, special: { label: "Enchantment Level" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, idsFileByParam2: { 2: ["EA"], 3: ["GENERAL"], 4: ["RACE"], 5: ["CLASS"], 6: ["SPECIFIC"], 7: ["GENDER"], 8: ["ALIGN", "ALIGNMEN"], 9: ["KIT"] } },
    345: { param1: { label: "Enchantment Level" }, param2: { label: "Type" }, special: { label: "Weapon Slot" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    346: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, special: { label: "Primary Type" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    347: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    348: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    349: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    350: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    351: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    352: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    353: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    354: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    355: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    356: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    357: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    358: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    359: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    360: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    361: { param1: { label: "Unused" }, param2: { label: "Current Weapon Only?" }, param3: { label: "Weapon Category" }, special: { label: "Attack Type" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "SPL" },
    362: { param1: { label: "Statistic Modifier" }, param2: { label: "Current Weapon Only?" }, param3: { label: "Weapon Category" }, special: { label: "Attack Type" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    363: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, special: { label: "Modal State" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    364: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    365: { param1: { label: "Dialogue enabled" }, param2: { label: "AI enabled" }, special: { label: "Selection circle color" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    366: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true }, resourceType: "SPL" },
    367: { param1: { label: "Irrelevant" }, param2: { label: "Stat Value" }, availability: { bg1: false, bg2: false, bgee: true, iwd1: false, iwd2: false, pst: false, pstee: true } },
    368: { param1: { label: "Irrelevant" }, param2: { label: "Flags" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    369: { param1: { label: "RGB" }, param2: { label: "Method" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    370: { param1: { label: "RGB" }, param2: { label: "Method" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    371: { param1: { label: "RGB" }, param2: { label: "Method" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    372: { param1: { label: "RGB" }, param2: { label: "Method" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    373: { param1: { label: "RGB" }, param2: { label: "Method" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    374: { param1: { label: "Irrelevant" }, param2: { label: "Effect" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    375: { param1: { label: "Irrelevant" }, param2: { label: "Effect" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    376: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    377: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    378: { param1: { label: "Value" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    379: { param1: { label: "Value" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    380: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    381: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    382: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    383: { param1: { label: "Drain Amount" }, param2: { label: "Drain Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: false, pst: false, pstee: true } },
    400: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    401: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    402: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    403: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    404: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    405: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    406: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    407: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    408: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    409: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    410: { param1: { label: "Number" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    411: { param1: { label: "Number" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    412: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    413: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    414: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    415: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    416: { param1: { label: "Amount" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    417: { param1: { label: "Radius" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    418: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    419: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    420: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    421: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    422: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    423: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    424: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    425: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    426: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    427: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    428: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    429: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    430: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    431: { param1: { label: "Value" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    432: { param1: { label: "Value" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    433: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    434: { param1: { label: "Value" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    435: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    436: { param1: { label: "Damage" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    437: { param1: { label: "Value" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    438: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    439: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    440: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    441: { param1: { label: "Statistic Modifier" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    442: { param1: { label: "Unknown" }, param2: { label: "Unknown" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    443: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    444: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    445: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    446: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    447: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    448: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    449: { param1: { label: "Amount" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    450: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    451: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    452: { param1: { label: "Irrelevant" }, param2: { label: "Type" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    453: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    454: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    455: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    456: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
    457: { param1: { label: "Irrelevant" }, param2: { label: "Irrelevant" }, availability: { bg1: false, bg2: false, bgee: false, iwd1: false, iwd2: true, pst: false, pstee: false } },
};
