/**
 * Engine function names as written in source, mapped to the opcode they compile to.
 *
 * A call like `display_msg("x")` is not a procedure call: it pushes its arguments and then a single
 * opcode the engine dispatches on. This table is what turns the source spelling into that number, so
 * the front end needs no knowledge of the opcode layout.
 *
 * `popsResult` marks the 27 functions that return a value even when called as a statement; their
 * statement form drops the result rather than leaving it on the stack.
 *
 * Fallout 1 reuses 7 opcode numbers for different functions under different source names (see
 * `opcodes-engine.ts`). Those names are listed separately so that compiling for Fallout 2 does not
 * silently accept a Fallout 1 spelling and emit the wrong function.
 */

import { EngineOp, FALLOUT1_OPCODES, LibOp } from "./opcodes-engine";

export interface EngineFunction {
    opcode: number;
    /**
     * How many stack values the opcode consumes. The compiler does not need this - the source supplies
     * the arguments - but the decompiler cannot recover a call without it, since an opcode alone says
     * nothing about its operand count. Absent for the four functions the signature data does not
     * describe, which the decompiler reports rather than guessing at.
     *
     * Maintained by `scripts/utils/src/update-ssl-engine-arity.ts`; edit the signatures in
     * `server/data/fallout-ssl-*.yml` and re-run it rather than editing these numbers.
     */
    args?: number;
    /**
     * The opcode leaves a value on the stack. Distinct from `popsResult`, which records what the
     * reference emits in statement position and is verified against its output; this records what the
     * documented signature says the call yields, and the decompiler needs it to know whether an opcode
     * contributes an operand to the enclosing expression.
     */
    returns?: boolean;
    /** The statement form discards a returned value. */
    popsResult?: boolean;
    /**
     * Bitmask of argument positions that take a PROCEDURE rather than a value: bit N marks argument N.
     * A procedure named in such a position is passed by reference; naming it anywhere else calls it.
     */
    procArgs?: number;
}

/**
 * Engine functions available when targeting Fallout 2, keyed by LOWERCASED source name. The language
 * matches these case-insensitively - some are declared in upper case and written in lower case in real
 * scripts - so callers must lowercase before looking one up.
 */
export const ENGINE_FUNCTIONS: Readonly<Record<string, EngineFunction>> = {
    reg_anim_func: { opcode: EngineOp.REG_ANIM_FUNC, args: 2 },
    abs: { opcode: EngineOp.TS_ABS, args: 1, returns: true },
    action_being_used: { opcode: EngineOp.ACTION_BEING_USED, args: 0, returns: true },
    activate_shader: { opcode: EngineOp.TS_ACTIVATE_SHADER, args: 1 },
    activateregion: { opcode: LibOp.ACTIVATEREGION, args: 2 },
    active_hand: { opcode: EngineOp.TS_GET_ACTIVE_HAND, args: 0, returns: true },
    add_mult_objs_to_inven: { opcode: EngineOp.ADD_MULT_OBJS_TO_INVEN, args: 3 },
    add_obj_to_inven: { opcode: EngineOp.ADD_OBJ_TO_INVEN, args: 2 },
    add_timer_event: { opcode: EngineOp.ADD_TIMER_EVENT, args: 3 },
    addbutton: { opcode: LibOp.ADDBUTTON, args: 5 },
    addbuttonflag: { opcode: LibOp.ADDBUTTONFLAG, args: 2 },
    addbuttongfx: { opcode: LibOp.ADDBUTTONGFX, args: 4 },
    addbuttonproc: { opcode: LibOp.ADDBUTTONPROC, args: 5, procArgs: 30 },
    addbuttonrightproc: { opcode: LibOp.ADDBUTTONRIGHTPROC, args: 3, procArgs: 6 },
    addbuttontext: { opcode: LibOp.ADDBUTTONTEXT, args: 2 },
    addkey: { opcode: LibOp.ADDKEY, args: 2, procArgs: 2 },
    addnamedevent: { opcode: LibOp.ADDNAMEDEVENT, args: 2, procArgs: 2 },
    addnamedhandler: { opcode: LibOp.ADDNAMEDHANDLER, args: 2, procArgs: 2 },
    addregion: { opcode: LibOp.ADDREGION, args: 2 },
    addregionflag: { opcode: LibOp.ADDREGIONFLAG, args: 2 },
    addregionproc: { opcode: LibOp.ADDREGIONPROC, args: 5, procArgs: 30 },
    addregionrightproc: { opcode: LibOp.ADDREGIONRIGHTPROC, args: 3, procArgs: 6 },
    anim: { opcode: EngineOp.ANIM, args: 3 },
    anim_action_frame: { opcode: EngineOp.ANIM_ACTION_FRAME, args: 2, returns: true },
    anim_busy: { opcode: EngineOp.ANIM_BUSY, args: 1, returns: true },
    animate_move_obj_to_tile: { opcode: EngineOp.ANIMATE_MOVE_OBJ_TO_TILE, args: 3 },
    animate_stand_obj: { opcode: EngineOp.ANIMATE_STAND_OBJ, args: 1 },
    animate_stand_reverse_obj: { opcode: EngineOp.ANIMATE_STAND_REVERSE_OBJ, args: 1 },
    apply_heaveho_fix: { opcode: EngineOp.TS_APPLY_HEAVEHO_FIX, args: 0 },
    arctan: { opcode: EngineOp.TS_ATAN, args: 2, returns: true },
    array_key: { opcode: EngineOp.TS_GET_ARRAY_KEY, args: 2, returns: true },
    arrayexpr: { opcode: EngineOp.TS_STACK_ARRAY, args: 2, returns: true },
    art_anim: { opcode: EngineOp.ART_ANIM, args: 1, returns: true },
    art_exists: { opcode: EngineOp.TS_ART_EXISTS, args: 1, returns: true },
    atof: { opcode: EngineOp.TS_ATOF, args: 1, returns: true },
    atoi: { opcode: EngineOp.TS_ATOI, args: 1, returns: true },
    attack: { opcode: EngineOp.ATTACK, args: 1 },
    attack_complex: { opcode: EngineOp.ATTACK_COMPLEX, args: 8 },
    attack_setup: { opcode: EngineOp.ATTACK_SETUP, args: 2 },
    available_global_script_types: { opcode: EngineOp.TS_AVAILABLE_GLOBAL_SCRIPT_TYPES, args: 0, returns: true },
    block_combat: { opcode: EngineOp.TS_BLOCK_COMBAT, args: 1 },
    call_offset_r0: { opcode: EngineOp.TS_CALL_OFFSET_R0, args: 1, returns: true },
    call_offset_r1: { opcode: EngineOp.TS_CALL_OFFSET_R1, args: 2, returns: true },
    call_offset_r2: { opcode: EngineOp.TS_CALL_OFFSET_R2, args: 3, returns: true },
    call_offset_r3: { opcode: EngineOp.TS_CALL_OFFSET_R3, args: 4, returns: true },
    call_offset_r4: { opcode: EngineOp.TS_CALL_OFFSET_R4, args: 5, returns: true },
    call_offset_v0: { opcode: EngineOp.TS_CALL_OFFSET_V0, args: 1 },
    call_offset_v1: { opcode: EngineOp.TS_CALL_OFFSET_V1, args: 2 },
    call_offset_v2: { opcode: EngineOp.TS_CALL_OFFSET_V2, args: 3 },
    call_offset_v3: { opcode: EngineOp.TS_CALL_OFFSET_V3, args: 4 },
    call_offset_v4: { opcode: EngineOp.TS_CALL_OFFSET_V4, args: 5 },
    ceil: { opcode: EngineOp.TS_CEIL, args: 1, returns: true },
    charcode: { opcode: EngineOp.TS_ORD, args: 1, returns: true },
    checkregion: { opcode: LibOp.CHECKREGION, args: 1, returns: true },
    clear_selectable_perks: { opcode: EngineOp.TS_CLEAR_SELECTABLE_PERKS, args: 0 },
    clearnamed: { opcode: LibOp.CLEARNAMED, args: 1 },
    combat_difficulty: { opcode: EngineOp.COMBAT_DIFFICULTY, args: 0, returns: true },
    combat_is_initialized: { opcode: EngineOp.COMBAT_IS_INITIALIZED, args: 0, returns: true },
    cos: { opcode: EngineOp.TS_COS, args: 1, returns: true },
    create_array: { opcode: EngineOp.TS_CREATE_ARRAY, args: 2, returns: true },
    create_message_window: { opcode: EngineOp.TS_CREATE_MESSAGE_WINDOW, args: 1 },
    create_object_sid: { opcode: EngineOp.CREATE_OBJECT_SID, args: 4, returns: true, popsResult: true },
    create_spatial: { opcode: EngineOp.TS_CREATE_SPATIAL, args: 4, returns: true, popsResult: true },
    createwin: { opcode: LibOp.CREATEWIN, args: 5 },
    critter_add_trait: { opcode: EngineOp.CRITTER_ADD_TRAIT, args: 4, returns: true, popsResult: true },
    critter_attempt_placement: { opcode: EngineOp.CRITTER_ATTEMPT_PLACEMENT, args: 3, returns: true, popsResult: true },
    critter_dmg: { opcode: EngineOp.CRITTER_DMG, args: 3 },
    critter_heal: { opcode: EngineOp.CRITTER_HEAL, args: 2, returns: true, popsResult: true },
    critter_injure: { opcode: EngineOp.CRITTER_INJURE, args: 2, returns: true },
    critter_inven_obj: { opcode: EngineOp.CRITTER_INVEN_OBJ, args: 2, returns: true },
    critter_is_fleeing: { opcode: EngineOp.CRITTER_IS_FLEEING, args: 1, returns: true },
    critter_mod_skill: { opcode: EngineOp.CRITTER_MOD_SKILL, args: 3, returns: true },
    critter_rm_trait: { opcode: EngineOp.CRITTER_RM_TRAIT, args: 4, returns: true, popsResult: true },
    critter_set_flee_state: { opcode: EngineOp.CRITTER_SET_FLEE_STATE, args: 2, returns: true },
    critter_state: { opcode: EngineOp.CRITTER_STATE, args: 1, returns: true },
    critter_stop_attacking: { opcode: EngineOp.CRITTER_STOP_ATTACKING, args: 1, returns: true },
    cur_map_index: { opcode: EngineOp.CUR_MAP_INDEX, args: 0, returns: true },
    days_since_visited: { opcode: EngineOp.DAYS_SINCE_VISITED, args: 0, returns: true },
    deactivate_shader: { opcode: EngineOp.TS_DEACTIVATE_SHADER, args: 1 },
    debug_msg: { opcode: EngineOp.DEBUG_MSG, args: 1 },
    deletebutton: { opcode: LibOp.DELETEBUTTON, args: 1 },
    deletekey: { opcode: LibOp.DELETEKEY, args: 1 },
    deleteregion: { opcode: LibOp.DELETEREGION, args: 1 },
    deletewin: { opcode: LibOp.DELETEWIN, args: 1 },
    destroy_mult_objs: { opcode: EngineOp.DESTROY_MULT_OBJS, args: 2, returns: true },
    destroy_object: { opcode: EngineOp.DESTROY_OBJECT, args: 1, returns: true },
    dialogue_reaction: { opcode: EngineOp.DIALOGUE_REACTION, args: 1 },
    dialogue_system_enter: { opcode: EngineOp.DIALOGUE_SYSTEM_ENTER, args: 0 },
    difficulty_level: { opcode: EngineOp.DIFFICULTY_LEVEL, args: 0, returns: true },
    disable_aimed_shots: { opcode: EngineOp.TS_DISABLE_AIMED_SHOTS, args: 1 },
    display: { opcode: LibOp.DISPLAY, args: 1 },
    display_msg: { opcode: EngineOp.DISPLAY_MSG, args: 1 },
    displaygfx: { opcode: LibOp.DISPLAYGFX, args: 5 },
    displayraw: { opcode: LibOp.DISPLAYRAW, args: 1 },
    do_check: { opcode: EngineOp.DO_CHECK, args: 3, returns: true, popsResult: true },
    drop_obj: { opcode: EngineOp.DROP_OBJ, args: 1, returns: true },
    dude_obj: { opcode: EngineOp.DUDE_OBJ, args: 0, returns: true },
    eax_available: { opcode: EngineOp.TS_EAX_AVAILABLE, args: 0, returns: true },
    elevation: { opcode: EngineOp.ELEVATION, args: 1, returns: true },
    end_dialogue: { opcode: EngineOp.END_DIALOGUE, args: 0 },
    endgame_movie: { opcode: EngineOp.ENDGAME_MOVIE, args: 0 },
    endgame_slideshow: { opcode: EngineOp.ENDGAME_SLIDESHOW, args: 0 },
    explosion: { opcode: EngineOp.EXPLOSION, args: 3, returns: true },
    exponent: { opcode: EngineOp.TS_EXP, args: 1, returns: true },
    fadein: { opcode: LibOp.FADEIN, args: 1 },
    fadeout: { opcode: LibOp.FADEOUT, args: 1 },
    fillrect: { opcode: LibOp.FILLRECT, args: 7 },
    fillwin: { opcode: LibOp.FILLWIN, args: 3 },
    fillwin3x3: { opcode: LibOp.FILLWIN3X3, args: 1 },
    fix_array: { opcode: EngineOp.TS_FIX_ARRAY, args: 1 },
    fixed_param: { opcode: EngineOp.FIXED_PARAM, args: 0, returns: true },
    float_msg: { opcode: EngineOp.FLOAT_MSG, args: 3 },
    force_aimed_shots: { opcode: EngineOp.TS_FORCE_AIMED_SHOTS, args: 1 },
    force_encounter: { opcode: EngineOp.TS_FORCE_ENCOUNTER, args: 1 },
    force_encounter_with_flags: { opcode: EngineOp.TS_FORCE_ENCOUNTER_WITH_FLAGS, args: 2 },
    force_graphics_refresh: { opcode: EngineOp.TS_FORCE_GRAPHICS_REFRESH, args: 1 },
    format: { opcode: LibOp.FORMAT, args: 6 },
    free_array: { opcode: EngineOp.TS_FREE_ARRAY, args: 1 },
    free_shader: { opcode: EngineOp.TS_FREE_SHADER, args: 1 },
    fs_copy: { opcode: EngineOp.TS_FS_COPY, args: 2, returns: true },
    fs_create: { opcode: EngineOp.TS_FS_CREATE, args: 2, returns: true },
    fs_delete: { opcode: EngineOp.TS_FS_DELETE, args: 1 },
    fs_find: { opcode: EngineOp.TS_FS_FIND, args: 1, returns: true },
    fs_pos: { opcode: EngineOp.TS_FS_POS, args: 1, returns: true },
    fs_read_byte: { opcode: EngineOp.TS_FS_READ_BYTE, args: 1, returns: true },
    fs_read_float: { opcode: EngineOp.TS_FS_READ_FLOAT, args: 1, returns: true },
    fs_read_int: { opcode: EngineOp.TS_FS_READ_INT, args: 1, returns: true },
    fs_read_short: { opcode: EngineOp.TS_FS_READ_SHORT, args: 1, returns: true },
    fs_resize: { opcode: EngineOp.TS_FS_RESIZE, args: 2 },
    fs_seek: { opcode: EngineOp.TS_FS_SEEK, args: 2 },
    fs_size: { opcode: EngineOp.TS_FS_SIZE, args: 1, returns: true },
    fs_write_bstring: { opcode: EngineOp.TS_FS_WRITE_BSTRING, args: 2 },
    fs_write_byte: { opcode: EngineOp.TS_FS_WRITE_BYTE, args: 2 },
    fs_write_float: { opcode: EngineOp.TS_FS_WRITE_FLOAT, args: 2 },
    fs_write_int: { opcode: EngineOp.TS_FS_WRITE_INT, args: 2 },
    fs_write_short: { opcode: EngineOp.TS_FS_WRITE_SHORT, args: 2 },
    fs_write_string: { opcode: EngineOp.TS_FS_WRITE_STRING, args: 2 },
    game_loaded: { opcode: EngineOp.TS_GAME_LOADED, args: 0, returns: true },
    game_ticks: { opcode: EngineOp.GAME_TICKS, args: 1, returns: true },
    game_time: { opcode: EngineOp.GAME_TIME, args: 0, returns: true },
    game_time_advance: { opcode: EngineOp.GAME_TIME_ADVANCE, args: 1 },
    game_time_hour: { opcode: EngineOp.GAME_TIME_HOUR, args: 0, returns: true },
    game_time_in_seconds: { opcode: EngineOp.GAME_TIME_IN_SECONDS, args: 0, returns: true },
    game_ui_disable: { opcode: EngineOp.GAME_UI_DISABLE, args: 0 },
    game_ui_enable: { opcode: EngineOp.GAME_UI_ENABLE, args: 0 },
    game_ui_is_disabled: { opcode: EngineOp.GAME_UI_IS_DISABLED, args: 0, returns: true },
    gdialog_get_barter_mod: { opcode: EngineOp.TS_GET_BARTER_MOD, args: 0, returns: true },
    gdialog_mod_barter: { opcode: EngineOp.GDIALOG_MOD_BARTER, args: 1, returns: true },
    gdialog_set_barter_mod: { opcode: EngineOp.GDIALOG_SET_BARTER_MOD, args: 1 },
    get_array: { opcode: EngineOp.TS_GET_ARRAY, args: 2, returns: true },
    get_attack_type: { opcode: EngineOp.TS_GET_ATTACK_TYPE, args: 0, returns: true },
    get_available_skill_points: { opcode: EngineOp.TS_GET_AVAILABLE_SKILL_POINTS, args: 0, returns: true },
    get_bodypart_hit_modifier: { opcode: EngineOp.TS_GET_BODYPART_HIT_MODIFIER, args: 1, returns: true },
    get_critical_table: { opcode: EngineOp.TS_GET_CRITICAL_TABLE, args: 4, returns: true },
    get_critter_base_stat: { opcode: EngineOp.TS_GET_CRITTER_BASE_STAT, args: 2, returns: true },
    get_critter_current_ap: { opcode: EngineOp.TS_GET_CRITTER_AP, args: 1, returns: true },
    get_critter_extra_stat: { opcode: EngineOp.TS_GET_CRITTER_EXTRA_STAT, args: 2, returns: true },
    get_critter_skill_points: { opcode: EngineOp.TS_GET_CRITTER_SKILL_POINTS, args: 2, returns: true },
    get_critter_stat: { opcode: EngineOp.GET_CRITTER_STAT, args: 2, returns: true },
    get_day: { opcode: EngineOp.GET_DAY, args: 0, returns: true },
    get_game_mode: { opcode: EngineOp.TS_GET_GAME_MODE, args: 0, returns: true },
    get_ini_setting: { opcode: EngineOp.TS_GET_INI_SETTING, args: 1, returns: true },
    get_ini_string: { opcode: EngineOp.TS_GET_INI_STRING, args: 1, returns: true },
    get_kill_counter: { opcode: EngineOp.TS_GET_KILL_COUNTER, args: 1, returns: true },
    get_last_attacker: { opcode: EngineOp.TS_GET_LAST_ATTACKER, args: 1, returns: true },
    get_last_target: { opcode: EngineOp.TS_GET_LAST_TARGET, args: 1, returns: true },
    get_light_level: { opcode: EngineOp.TS_GET_LIGHT_LEVEL, args: 0, returns: true },
    get_month: { opcode: EngineOp.GET_MONTH, args: 0, returns: true },
    get_mouse_buttons: { opcode: EngineOp.TS_GET_MOUSE_BUTTONS, args: 0, returns: true },
    get_mouse_x: { opcode: EngineOp.TS_GET_MOUSE_X, args: 0, returns: true },
    get_mouse_y: { opcode: EngineOp.TS_GET_MOUSE_Y, args: 0, returns: true },
    get_npc_level: { opcode: EngineOp.TS_GET_NPC_LEVEL, args: 1, returns: true },
    get_pc_base_stat: { opcode: EngineOp.TS_GET_PC_BASE_STAT, args: 1, returns: true },
    get_pc_extra_stat: { opcode: EngineOp.TS_GET_PC_EXTRA_STAT, args: 1, returns: true },
    get_pc_stat: { opcode: EngineOp.GET_PC_STAT, args: 1, returns: true },
    get_perk_available: { opcode: EngineOp.TS_GET_PERK_AVAILABLE, args: 1, returns: true },
    get_perk_owed: { opcode: EngineOp.TS_GET_PERK_OWED, args: 0, returns: true },
    get_poison: { opcode: EngineOp.GET_POISON, args: 1, returns: true },
    get_proto_data: { opcode: EngineOp.TS_GET_PROTO_DATA, args: 2, returns: true },
    get_screen_height: { opcode: EngineOp.TS_GET_SCREEN_HEIGHT, args: 0, returns: true },
    get_screen_width: { opcode: EngineOp.TS_GET_SCREEN_WIDTH, args: 0, returns: true },
    get_script: { opcode: EngineOp.TS_GET_SCRIPT, args: 1, returns: true },
    get_sfall_arg: { opcode: EngineOp.TS_GET_SFALL_ARG, args: 0, returns: true },
    get_sfall_args: { opcode: EngineOp.TS_GET_SFALL_ARGS, args: 0, returns: true },
    get_sfall_global_float: { opcode: EngineOp.TS_GET_SFALL_GLOBAL_FLOAT, args: 1, returns: true },
    get_sfall_global_int: { opcode: EngineOp.TS_GET_SFALL_GLOBAL_INT, args: 1, returns: true },
    get_shader_texture: { opcode: EngineOp.TS_GET_SHADER_TEXTURE, args: 2, returns: true },
    get_shader_version: { opcode: EngineOp.TS_GET_SHADER_VERSION, args: 0, returns: true },
    get_tile_fid: { opcode: EngineOp.TS_TILE_PID, args: 1, returns: true },
    get_unspent_ap_bonus: { opcode: EngineOp.TS_GET_UNSPENT_AP_BONUS, args: 0, returns: true },
    get_unspent_ap_perk_bonus: { opcode: EngineOp.TS_GET_UNSPENT_AP_EBONUS, args: 0, returns: true },
    get_uptime: { opcode: EngineOp.TS_GET_UPTIME, args: 0, returns: true },
    get_viewport_x: { opcode: EngineOp.TS_GET_VIEWPORT_X, args: 0, returns: true },
    get_viewport_y: { opcode: EngineOp.TS_GET_VIEWPORT_Y, args: 0, returns: true },
    get_weapon_ammo_count: { opcode: EngineOp.TS_GET_WEAPON_AMMO_COUNT, args: 1, returns: true },
    get_weapon_ammo_pid: { opcode: EngineOp.TS_GET_WEAPON_AMMO_PID, args: 1, returns: true },
    get_window_under_mouse: { opcode: EngineOp.TS_GET_WINDOW_UNDER_MOUSE, args: 0, returns: true },
    get_world_map_x_pos: { opcode: EngineOp.TS_GET_WORLD_MAP_X_POS, args: 0, returns: true },
    get_world_map_y_pos: { opcode: EngineOp.TS_GET_WORLD_MAP_Y_POS, args: 0, returns: true },
    get_year: { opcode: EngineOp.TS_GET_YEAR, args: 0, returns: true },
    gfade_in: { opcode: EngineOp.GFADE_IN, args: 1 },
    gfade_out: { opcode: EngineOp.GFADE_OUT, args: 1 },
    giq_option: { opcode: EngineOp.GIQ_OPTION, args: 5, procArgs: 8 },
    give_exp_points: { opcode: EngineOp.GIVE_EXP_POINTS, args: 1 },
    global_var: { opcode: EngineOp.GLOBAL_VAR, args: 1, returns: true },
    gotoxy: { opcode: LibOp.GOTOXY, args: 2 },
    graphics_funcs_available: { opcode: EngineOp.TS_GRAPHICS_FUNCS_AVAILABLE, args: 0, returns: true },
    gsay_end: { opcode: EngineOp.GSAY_END, args: 0 },
    gsay_message: { opcode: EngineOp.GSAY_MESSAGE, args: 3 },
    gsay_option: { opcode: EngineOp.GSAY_OPTION, args: 4, returns: true, procArgs: 4 },
    gsay_reply: { opcode: EngineOp.GSAY_REPLY, args: 2, returns: true },
    gsay_start: { opcode: EngineOp.GSAY_START, args: 0 },
    has_fake_perk: { opcode: EngineOp.TS_HAS_FAKE_PERK, args: 1, returns: true },
    has_fake_trait: { opcode: EngineOp.TS_HAS_FAKE_TRAIT, args: 1, returns: true },
    has_skill: { opcode: EngineOp.HAS_SKILL, args: 2, returns: true, popsResult: true },
    has_trait: { opcode: EngineOp.HAS_TRAIT, args: 3, returns: true },
    hero_select_win: { opcode: EngineOp.TS_HERO_SELECT_WIN, args: 1 },
    hide_iface_tag: { opcode: EngineOp.TS_HIDE_IFACE_TAG, args: 1 },
    hide_real_perks: { opcode: EngineOp.TS_HIDE_REAL_PERKS, args: 0 },
    hidemouse: { opcode: LibOp.HIDEMOUSE, args: 0 },
    how_much: { opcode: EngineOp.HOW_MUCH, args: 1, returns: true },
    in_world_map: { opcode: EngineOp.TS_IN_WORLD_MAP, args: 0, returns: true },
    inc_npc_level: { opcode: EngineOp.TS_INC_NPC_LEVEL, args: 1 },
    init_hook: { opcode: EngineOp.TS_INIT_HOOK, args: 0, returns: true },
    input_funcs_available: { opcode: EngineOp.TS_INPUT_FUNCS_AVAILABLE, args: 0, returns: true },
    inven_cmds: { opcode: EngineOp.INVEN_CMDS, args: 3, returns: true },
    inven_unwield: { opcode: EngineOp.INVEN_UNWIELD, args: 0 },
    is_critical: { opcode: EngineOp.IS_CRITICAL, args: 1, returns: true },
    is_iface_tag_active: { opcode: EngineOp.TS_IS_IFACE_TAG_ACTIVE, args: 1, returns: true },
    is_success: { opcode: EngineOp.IS_SUCCESS, args: 1, returns: true },
    item_caps_adjust: { opcode: EngineOp.ITEM_CAPS_ADJUST, args: 2, returns: true, popsResult: true },
    item_caps_total: { opcode: EngineOp.ITEM_CAPS_TOTAL, args: 1, returns: true },
    jam_lock: { opcode: EngineOp.JAM_LOCK, args: 1, returns: true },
    key_pressed: { opcode: EngineOp.TS_KEY_PRESSED, args: 1, returns: true },
    kill_critter: { opcode: EngineOp.KILL_CRITTER, args: 2 },
    kill_critter_type: { opcode: EngineOp.KILL_CRITTER_TYPE, args: 2 },
    len_array: { opcode: EngineOp.TS_LEN_ARRAY, args: 1, returns: true },
    list_as_array: { opcode: EngineOp.TS_LIST_AS_ARRAY, args: 1, returns: true },
    list_begin: { opcode: EngineOp.TS_LIST_BEGIN, args: 1, returns: true },
    list_end: { opcode: EngineOp.TS_LIST_END, args: 1 },
    list_next: { opcode: EngineOp.TS_LIST_NEXT, args: 1, returns: true },
    load_array: { opcode: EngineOp.TS_LOAD_ARRAY, args: 1, returns: true },
    load_map: { opcode: EngineOp.LOAD_MAP, args: 2 },
    load_shader: { opcode: EngineOp.TS_LOAD_SHADER, args: 1, returns: true },
    loadpalettetable: { opcode: LibOp.LOADPALETTETABLE, args: 1 },
    local_var: { opcode: EngineOp.LOCAL_VAR, args: 1, returns: true },
    log: { opcode: EngineOp.TS_LOG, args: 1, returns: true },
    make_daytime: { opcode: EngineOp.MAKE_DAYTIME },
    map_var: { opcode: EngineOp.MAP_VAR, args: 1, returns: true },
    mark_area_known: { opcode: EngineOp.MARK_AREA_KNOWN, args: 3 },
    mark_movie_played: { opcode: EngineOp.TS_MARK_MOVIE_PLAYED, args: 1 },
    message_str: { opcode: EngineOp.MESSAGE_STR, args: 2, returns: true },
    message_str_game: { opcode: EngineOp.TS_MESSAGE_STR_GAME, args: 2, returns: true },
    metarule: { opcode: EngineOp.METARULE, args: 2, returns: true, popsResult: true },
    metarule2_explosions: { opcode: EngineOp.TS_EXPLOSIONS_METARULE, args: 3, returns: true, popsResult: true },
    metarule3: { opcode: EngineOp.METARULE3, args: 4, returns: true, popsResult: true },
    mod_kill_counter: { opcode: EngineOp.TS_MOD_KILL_COUNTER, args: 2 },
    mod_skill_points_per_level: { opcode: EngineOp.TS_MOD_SKILL_POINTS_PER_LEVEL, args: 1 },
    modified_ini: { opcode: EngineOp.TS_MODIFIED_INI, args: 0, returns: true },
    mouseshape: { opcode: LibOp.MOUSESHAPE, args: 3 },
    move_obj_inven_to_obj: { opcode: EngineOp.MOVE_OBJ_INVEN_TO_OBJ, args: 2, returns: true },
    move_to: { opcode: EngineOp.MOVE_TO, args: 3, returns: true, popsResult: true },
    movieflags: { opcode: LibOp.MOVIEFLAGS, args: 1 },
    nb_create_char: { opcode: EngineOp.TS_NB_CREATE_CHAR, args: 0, returns: true },
    obj_art_fid: { opcode: EngineOp.OBJ_ART_FID, args: 1, returns: true },
    obj_being_used_with: { opcode: EngineOp.OBJ_BEING_USED_WITH, args: 0, returns: true },
    obj_blocking_line: { opcode: EngineOp.TS_MAKE_STRAIGHT_PATH, args: 3, returns: true },
    obj_blocking_tile: { opcode: EngineOp.TS_OBJ_BLOCKING_AT, args: 3, returns: true },
    obj_can_hear_obj: { opcode: EngineOp.OBJ_CAN_HEAR_OBJ, args: 2, returns: true },
    obj_can_see_obj: { opcode: EngineOp.OBJ_CAN_SEE_OBJ, args: 2, returns: true },
    obj_carrying_pid_obj: { opcode: EngineOp.OBJ_CARRYING_PID_OBJ, args: 2, returns: true },
    obj_close: { opcode: EngineOp.OBJ_CLOSE, args: 1 },
    obj_is_carrying_obj: { opcode: EngineOp.TS_OBJ_IS_CARRYING_OBJ, args: 2, returns: true },
    obj_is_carrying_obj_pid: { opcode: EngineOp.OBJ_IS_CARRYING_OBJ_PID, args: 2, returns: true },
    obj_is_locked: { opcode: EngineOp.OBJ_IS_LOCKED, args: 1, returns: true },
    obj_is_open: { opcode: EngineOp.OBJ_IS_OPEN, args: 1, returns: true },
    obj_item_subtype: { opcode: EngineOp.OBJ_ITEM_SUBTYPE, args: 1, returns: true },
    obj_lock: { opcode: EngineOp.OBJ_LOCK, args: 1 },
    obj_name: { opcode: EngineOp.OBJ_NAME, args: 1, returns: true },
    obj_on_screen: { opcode: EngineOp.OBJ_ON_SCREEN, args: 1, returns: true },
    obj_open: { opcode: EngineOp.OBJ_OPEN, args: 1 },
    obj_pid: { opcode: EngineOp.OBJ_PID, args: 1, returns: true },
    obj_set_light_level: { opcode: EngineOp.OBJ_SET_LIGHT_LEVEL, args: 3 },
    obj_type: { opcode: EngineOp.OBJ_TYPE, args: 1, returns: true },
    obj_unlock: { opcode: EngineOp.OBJ_UNLOCK, args: 1 },
    override_map_start: { opcode: EngineOp.OVERRIDE_MAP_START, args: 4 },
    party_add: { opcode: EngineOp.PARTY_ADD, args: 1 },
    party_member_list: { opcode: EngineOp.TS_GET_PARTY_MEMBERS, args: 1, returns: true },
    party_member_obj: { opcode: EngineOp.PARTY_MEMBER_OBJ, args: 1, returns: true },
    party_remove: { opcode: EngineOp.PARTY_REMOVE, args: 1 },
    path_find_to: { opcode: EngineOp.TS_PATH_FIND, args: 3, returns: true },
    perk_add_mode: { opcode: EngineOp.TS_PERK_ADD_MODE, args: 1 },
    pickup_obj: { opcode: EngineOp.PICKUP_OBJ, args: 1 },
    play_gmovie: { opcode: EngineOp.PLAY_GMOVIE, args: 1 },
    play_sfall_sound: { opcode: EngineOp.TS_PLAY_SFALL_SOUND, args: 2, returns: true },
    play_sfx: { opcode: EngineOp.PLAY_SFX, args: 1, returns: true },
    playmovie: { opcode: LibOp.PLAYMOVIE, args: 1 },
    playmoviealpha: { opcode: LibOp.PLAYMOVIEALPHA },
    playmoviealpharect: { opcode: LibOp.PLAYMOVIEALPHARECT },
    playmovierect: { opcode: LibOp.PLAYMOVIERECT, args: 5 },
    poison: { opcode: EngineOp.POISON, args: 2 },
    print: { opcode: LibOp.PRINT, args: 1 },
    printrect: { opcode: LibOp.PRINTRECT, args: 3 },
    proto_data: { opcode: EngineOp.PROTO_DATA, args: 2, returns: true },
    radiation_dec: { opcode: EngineOp.RADIATION_DEC, args: 2 },
    radiation_inc: { opcode: EngineOp.RADIATION_INC, args: 2 },
    random: { opcode: EngineOp.RANDOM, args: 2, returns: true },
    reaction_influence: { opcode: EngineOp.REACTION_INFLUENCE, args: 3, returns: true },
    read_byte: { opcode: EngineOp.TS_READ_BYTE, args: 1, returns: true },
    read_int: { opcode: EngineOp.TS_READ_INT, args: 1, returns: true },
    read_short: { opcode: EngineOp.TS_READ_SHORT, args: 1, returns: true },
    read_string: { opcode: EngineOp.TS_READ_STRING, args: 1, returns: true },
    refresh_pc_art: { opcode: EngineOp.TS_REFRESH_PC_ART, args: 0 },
    refreshmouse: { opcode: LibOp.REFRESHMOUSE, args: 1, procArgs: 1 },
    reg_anim_animate: { opcode: EngineOp.REG_ANIM_ANIMATE, args: 3 },
    reg_anim_animate_and_hide: { opcode: EngineOp.TS_REG_ANIM_ANIMATE_AND_HIDE, args: 3 },
    reg_anim_animate_forever: { opcode: EngineOp.REG_ANIM_ANIMATE_FOREVER, args: 2 },
    reg_anim_animate_reverse: { opcode: EngineOp.REG_ANIM_ANIMATE_REVERSE, args: 3 },
    reg_anim_callback: { opcode: EngineOp.TS_REG_ANIM_CALLBACK, args: 1, procArgs: 1 },
    reg_anim_change_fid: { opcode: EngineOp.TS_REG_ANIM_CHANGE_FID, args: 3 },
    reg_anim_combat_check: { opcode: EngineOp.TS_REG_ANIM_COMBAT_CHECK, args: 1 },
    reg_anim_destroy: { opcode: EngineOp.TS_REG_ANIM_DESTROY, args: 1 },
    reg_anim_light: { opcode: EngineOp.TS_REG_ANIM_LIGHT, args: 3 },
    reg_anim_obj_move_to_obj: { opcode: EngineOp.REG_ANIM_OBJ_MOVE_TO_OBJ, args: 3 },
    reg_anim_obj_move_to_tile: { opcode: EngineOp.REG_ANIM_OBJ_MOVE_TO_TILE, args: 3 },
    reg_anim_obj_run_to_obj: { opcode: EngineOp.REG_ANIM_OBJ_RUN_TO_OBJ, args: 3 },
    reg_anim_obj_run_to_tile: { opcode: EngineOp.REG_ANIM_OBJ_RUN_TO_TILE, args: 3 },
    reg_anim_play_sfx: { opcode: EngineOp.REG_ANIM_PLAY_SFX, args: 3 },
    reg_anim_take_out: { opcode: EngineOp.TS_REG_ANIM_TAKE_OUT, args: 3 },
    reg_anim_turn_towards: { opcode: EngineOp.TS_REG_ANIM_TURN_TOWARDS, args: 3 },
    register_hook: { opcode: EngineOp.TS_REGISTER_HOOK, args: 1 },
    register_hook_proc: { opcode: EngineOp.TS_REGISTER_HOOK_PROC, args: 2, procArgs: 2 },
    register_hook_proc_spec: { opcode: EngineOp.TS_REGISTER_HOOK_PROC2, args: 2, procArgs: 2 },
    remove_attacker_knockback: { opcode: EngineOp.TS_REMOVE_ATTACKER_KNOCKBACK, args: 1 },
    remove_script: { opcode: EngineOp.TS_REMOVE_SCRIPT, args: 1 },
    remove_target_knockback: { opcode: EngineOp.TS_REMOVE_TARGET_KNOCKBACK, args: 1 },
    remove_trait: { opcode: EngineOp.TS_REMOVE_TRAIT, args: 1 },
    remove_weapon_knockback: { opcode: EngineOp.TS_REMOVE_WEAPON_KNOCKBACK, args: 1 },
    reset_critical_table: { opcode: EngineOp.TS_RESET_CRITICAL_TABLE, args: 4 },
    resize_array: { opcode: EngineOp.TS_RESIZE_ARRAY, args: 2 },
    resizewin: { opcode: LibOp.RESIZEWIN, args: 5 },
    resume_game: { opcode: EngineOp.TS_RESUME_GAME, args: 0 },
    rm_mult_objs_from_inven: { opcode: EngineOp.RM_MULT_OBJS_FROM_INVEN, args: 3, returns: true },
    rm_obj_from_inven: { opcode: EngineOp.RM_OBJ_FROM_INVEN, args: 2 },
    rm_timer_event: { opcode: EngineOp.RM_TIMER_EVENT, args: 1 },
    roll_dice: { opcode: EngineOp.ROLL_DICE, args: 2, returns: true, popsResult: true },
    roll_vs_skill: { opcode: EngineOp.ROLL_VS_SKILL, args: 3, returns: true, popsResult: true },
    rotation_to_tile: { opcode: EngineOp.ROTATION_TO_TILE, args: 2, returns: true },
    round: { opcode: EngineOp.TS_ROUND, args: 1, returns: true },
    running_burning_guy: { opcode: EngineOp.RUNNING_BURNING_GUY, args: 0, returns: true },
    save_array: { opcode: EngineOp.TS_SAVE_ARRAY, args: 2 },
    sayborder: { opcode: LibOp.SAYBORDER, args: 2 },
    sayend: { opcode: LibOp.SAYEND, args: 0 },
    saygetlastpos: { opcode: LibOp.SAYGETLASTPOS, args: 0, returns: true },
    saygotoreply: { opcode: LibOp.SAYGOTOREPLY, args: 1 },
    saymessage: { opcode: LibOp.SAYMESSAGE, args: 2 },
    saymessagetimeout: { opcode: LibOp.SAYMESSAGETIMEOUT, args: 1 },
    sayoption: { opcode: LibOp.SAYOPTION, args: 2, procArgs: 2 },
    sayoptioncolor: { opcode: LibOp.SAYOPTIONCOLOR, args: 3 },
    sayoptionflags: { opcode: LibOp.SAYOPTIONFLAGS, args: 1 },
    sayoptionwindow: { opcode: LibOp.SAYOPTIONWINDOW, args: 5 },
    sayquit: { opcode: LibOp.SAYQUIT, args: 0 },
    sayreply: { opcode: LibOp.SAYREPLY, args: 2 },
    sayreplycolor: { opcode: LibOp.SAYREPLYCOLOR, args: 3 },
    sayreplyflags: { opcode: LibOp.SAYREPLYFLAGS, args: 1 },
    sayreplytitle: { opcode: LibOp.SAYREPLYTITLE, args: 1 },
    sayreplywindow: { opcode: LibOp.SAYREPLYWINDOW, args: 5 },
    sayrestart: { opcode: LibOp.SAYRESTART, args: 0 },
    sayscrolldown: { opcode: LibOp.SAYSCROLLDOWN, args: 6 },
    sayscrollup: { opcode: LibOp.SAYSCROLLUP, args: 6 },
    saysetspacing: { opcode: LibOp.SAYSETSPACING, args: 1 },
    saystart: { opcode: LibOp.SAYSTART, args: 0 },
    saystartpos: { opcode: LibOp.SAYSTARTPOS, args: 1 },
    scalewin: { opcode: LibOp.SCALEWIN, args: 5 },
    scan_array: { opcode: EngineOp.TS_SCAN_ARRAY, args: 2, returns: true },
    scr_return: { opcode: EngineOp.SCR_RETURN, args: 1 },
    script_action: { opcode: EngineOp.SCRIPT_ACTION, args: 0, returns: true },
    script_overrides: { opcode: EngineOp.SCRIPT_OVERRIDES, args: 0 },
    selectfilelist: { opcode: LibOp.SELECTFILELIST, args: 2 },
    selectwin: { opcode: LibOp.SELECTWIN, args: 1 },
    self_obj: { opcode: EngineOp.SELF_OBJ, args: 0, returns: true },
    set_array: { opcode: EngineOp.TS_SET_ARRAY, args: 3 },
    set_attacker_knockback: { opcode: EngineOp.TS_SET_ATTACKER_KNOCKBACK, args: 3 },
    set_available_skill_points: { opcode: EngineOp.TS_SET_AVAILABLE_SKILL_POINTS, args: 1 },
    set_base_hit_chance_mod: { opcode: EngineOp.TS_SET_BASE_HIT_CHANCE_MOD, args: 2 },
    set_base_pickpocket_mod: { opcode: EngineOp.TS_SET_BASE_PICKPOCKET_MOD, args: 2 },
    set_base_skill_mod: { opcode: EngineOp.TS_SET_BASE_SKILL_MOD, args: 1 },
    set_bodypart_hit_modifier: { opcode: EngineOp.TS_SET_BODYPART_HIT_MODIFIER, args: 2 },
    set_car_current_town: { opcode: EngineOp.TS_SET_CAR_CURRENT_TOWN, args: 1 },
    set_critical_table: { opcode: EngineOp.TS_SET_CRITICAL_TABLE, args: 5 },
    set_critter_base_stat: { opcode: EngineOp.TS_SET_CRITTER_BASE_STAT, args: 3 },
    set_critter_burst_disable: { opcode: EngineOp.TS_SET_CRITTER_BURST_DISABLE, args: 2 },
    set_critter_current_ap: { opcode: EngineOp.TS_SET_CRITTER_AP, args: 2 },
    set_critter_extra_stat: { opcode: EngineOp.TS_SET_CRITTER_EXTRA_STAT, args: 3 },
    set_critter_hit_chance_mod: { opcode: EngineOp.TS_SET_CRITTER_HIT_CHANCE_MOD, args: 3 },
    set_critter_pickpocket_mod: { opcode: EngineOp.TS_SET_CRITTER_PICKPOCKET_MOD, args: 3 },
    set_critter_skill_mod: { opcode: EngineOp.TS_SET_CRITTER_SKILL_MOD, args: 2 },
    set_critter_skill_points: { opcode: EngineOp.TS_SET_CRITTER_SKILL_POINTS, args: 3 },
    set_critter_stat: { opcode: EngineOp.SET_CRITTER_STAT, args: 3, returns: true, popsResult: true },
    set_df_model: { opcode: EngineOp.TS_SET_DF_MODEL, args: 1 },
    set_dm_model: { opcode: EngineOp.TS_SET_DM_MODEL, args: 1 },
    set_eax_environment: { opcode: EngineOp.TS_SET_EAX_ENVIRONMENT, args: 1 },
    set_exit_grids: { opcode: EngineOp.SET_EXIT_GRIDS, args: 5 },
    set_fake_perk: { opcode: EngineOp.TS_SET_FAKE_PERK, args: 4 },
    set_fake_trait: { opcode: EngineOp.TS_SET_FAKE_TRAIT, args: 4 },
    set_global_script_repeat: { opcode: EngineOp.TS_SET_GLOBAL_SCRIPT_REPEAT, args: 1 },
    set_global_script_type: { opcode: EngineOp.TS_SET_GLOBAL_SCRIPT_TYPE, args: 1 },
    set_global_var: { opcode: EngineOp.SET_GLOBAL_VAR, args: 2 },
    set_hero_race: { opcode: EngineOp.TS_SET_HERO_RACE, args: 1 },
    set_hero_style: { opcode: EngineOp.TS_SET_HERO_STYLE, args: 1 },
    set_hit_chance_max: { opcode: EngineOp.TS_SET_HIT_CHANCE_MAX, args: 1 },
    set_hp_per_level_mod: { opcode: EngineOp.TS_SET_HP_LEVEL_MOD, args: 1 },
    set_inven_ap_cost: { opcode: EngineOp.TS_SET_INVEN_AP_COST, args: 1 },
    set_light_level: { opcode: EngineOp.SET_LIGHT_LEVEL, args: 1 },
    set_local_var: { opcode: EngineOp.SET_LOCAL_VAR, args: 2 },
    set_map_music: { opcode: EngineOp.SET_MAP_MUSIC, args: 2 },
    set_map_start: { opcode: EngineOp.SET_MAP_START, args: 4 },
    set_map_time_multi: { opcode: EngineOp.TS_SET_MAP_TIME_MULTI, args: 1 },
    set_map_var: { opcode: EngineOp.SET_MAP_VAR, args: 2 },
    set_movie_path: { opcode: EngineOp.TS_SET_MOVIE_PATH, args: 2 },
    set_npc_stat_max: { opcode: EngineOp.TS_SET_NPC_STAT_MAX, args: 2 },
    set_npc_stat_min: { opcode: EngineOp.TS_SET_NPC_STAT_MIN, args: 2 },
    set_obj_visibility: { opcode: EngineOp.SET_OBJ_VISIBILITY, args: 2 },
    set_palette: { opcode: EngineOp.TS_SET_PALETTE, args: 1 },
    set_pc_base_stat: { opcode: EngineOp.TS_SET_PC_BASE_STAT, args: 2 },
    set_pc_extra_stat: { opcode: EngineOp.TS_SET_PC_EXTRA_STAT, args: 2 },
    set_pc_stat_max: { opcode: EngineOp.TS_SET_PC_STAT_MAX, args: 2 },
    set_pc_stat_min: { opcode: EngineOp.TS_SET_PC_STAT_MIN, args: 2 },
    set_perk_agl: { opcode: EngineOp.TS_SET_PERK_AGL, args: 2 },
    set_perk_chr: { opcode: EngineOp.TS_SET_PERK_CHR, args: 2 },
    set_perk_desc: { opcode: EngineOp.TS_SET_PERK_DESC, args: 2 },
    set_perk_end: { opcode: EngineOp.TS_SET_PERK_END, args: 2 },
    set_perk_freq: { opcode: EngineOp.TS_SET_PERK_FREQ, args: 1 },
    set_perk_image: { opcode: EngineOp.TS_SET_PERK_IMAGE, args: 2 },
    set_perk_int: { opcode: EngineOp.TS_SET_PERK_INT, args: 2 },
    set_perk_lck: { opcode: EngineOp.TS_SET_PERK_LCK, args: 2 },
    set_perk_level: { opcode: EngineOp.TS_SET_PERK_LEVEL, args: 2 },
    set_perk_level_mod: { opcode: EngineOp.TS_SET_PERK_LEVEL_MOD, args: 1 },
    set_perk_name: { opcode: EngineOp.TS_SET_PERK_NAME, args: 2 },
    set_perk_owed: { opcode: EngineOp.TS_SET_PERK_OWED, args: 1 },
    set_perk_per: { opcode: EngineOp.TS_SET_PERK_PER, args: 2 },
    set_perk_ranks: { opcode: EngineOp.TS_SET_PERK_RANKS, args: 2 },
    set_perk_skill1: { opcode: EngineOp.TS_SET_PERK_SKILL1, args: 2 },
    set_perk_skill2: { opcode: EngineOp.TS_SET_PERK_SKILL2, args: 2 },
    set_perk_skill2_mag: { opcode: EngineOp.TS_SET_PERK_SKILL2_MAG, args: 2 },
    set_perk_stat: { opcode: EngineOp.TS_SET_PERK_STAT, args: 2 },
    set_perk_stat_mag: { opcode: EngineOp.TS_SET_PERK_STAT_MAG, args: 2 },
    set_perk_str: { opcode: EngineOp.TS_SET_PERK_STR, args: 2 },
    set_perk_type: { opcode: EngineOp.TS_SET_PERK_TYPE, args: 2 },
    set_perkbox_title: { opcode: EngineOp.TS_SET_PERKBOX_TITLE, args: 1 },
    set_pickpocket_max: { opcode: EngineOp.TS_SET_PICKPOCKET_MAX, args: 1 },
    set_pipboy_available: { opcode: EngineOp.TS_SET_PIPBOY_AVAILABLE, args: 1 },
    set_proto_data: { opcode: EngineOp.TS_SET_PROTO_DATA, args: 3 },
    set_pyromaniac_mod: { opcode: EngineOp.TS_SET_PYROMANIAC_MOD, args: 1 },
    set_script: { opcode: EngineOp.TS_SET_SCRIPT, args: 2 },
    set_selectable_perk: { opcode: EngineOp.TS_SET_SELECTABLE_PERK, args: 4 },
    set_self: { opcode: EngineOp.TS_SET_SELF, args: 1 },
    set_sfall_arg: { opcode: EngineOp.TS_SET_SFALL_ARG, args: 2 },
    set_sfall_global: { opcode: EngineOp.TS_SET_SFALL_GLOBAL, args: 2 },
    set_sfall_return: { opcode: EngineOp.TS_SET_SFALL_RETURN, args: 1 },
    set_shader_float: { opcode: EngineOp.TS_SET_SHADER_FLOAT, args: 3 },
    set_shader_int: { opcode: EngineOp.TS_SET_SHADER_INT, args: 3 },
    set_shader_mode: { opcode: EngineOp.TS_SET_SHADER_MODE, args: 2 },
    set_shader_texture: { opcode: EngineOp.TS_SET_SHADER_TEXTURE, args: 3 },
    set_shader_vector: { opcode: EngineOp.TS_SET_SHADER_VECTOR, args: 6 },
    set_skill_max: { opcode: EngineOp.TS_SET_SKILL_MAX, args: 1 },
    set_stat_max: { opcode: EngineOp.TS_SET_STAT_MAX, args: 2 },
    set_stat_min: { opcode: EngineOp.TS_SET_STAT_MIN, args: 2 },
    set_swiftlearner_mod: { opcode: EngineOp.TS_SET_SWIFTLEARNER_MOD, args: 1 },
    set_target_knockback: { opcode: EngineOp.TS_SET_TARGET_KNOCKBACK, args: 3 },
    set_unspent_ap_bonus: { opcode: EngineOp.TS_SET_UNSPENT_AP_BONUS, args: 1 },
    set_unspent_ap_perk_bonus: { opcode: EngineOp.TS_SET_UNSPENT_AP_EBONUS, args: 1 },
    set_viewport_x: { opcode: EngineOp.TS_SET_VIEWPORT_X, args: 1 },
    set_viewport_y: { opcode: EngineOp.TS_SET_VIEWPORT_Y, args: 1 },
    set_weapon_ammo_count: { opcode: EngineOp.TS_SET_WEAPON_AMMO_COUNT, args: 2 },
    set_weapon_ammo_pid: { opcode: EngineOp.TS_SET_WEAPON_AMMO_PID, args: 2 },
    set_weapon_knockback: { opcode: EngineOp.TS_SET_WEAPON_KNOCKBACK, args: 3 },
    set_world_map_pos: { opcode: EngineOp.TS_SET_WORLD_MAP_POS, args: 2 },
    set_xp_mod: { opcode: EngineOp.TS_SET_XP_MOD, args: 1 },
    setfont: { opcode: LibOp.SETFONT, args: 1 },
    setglobalmousefunc: { opcode: LibOp.SETGLOBALMOUSEFUNC, procArgs: 15 },
    sethighlightcolor: { opcode: LibOp.SETHIGHLIGHTCOLOR, args: 3 },
    setoneoptpause: { opcode: LibOp.SETONEOPTPAUSE, args: 1 },
    settextcolor: { opcode: LibOp.SETTEXTCOLOR, args: 3 },
    settextflags: { opcode: LibOp.SETTEXTFLAGS, args: 1 },
    sfall_func0: { opcode: EngineOp.TS_SFALL_METARULE0, args: 1, returns: true, popsResult: true },
    sfall_func1: { opcode: EngineOp.TS_SFALL_METARULE1, args: 2, returns: true, popsResult: true },
    sfall_func2: { opcode: EngineOp.TS_SFALL_METARULE2, args: 3, returns: true, popsResult: true },
    sfall_func3: { opcode: EngineOp.TS_SFALL_METARULE3, args: 4, returns: true, popsResult: true },
    sfall_func4: { opcode: EngineOp.TS_SFALL_METARULE4, args: 5, returns: true, popsResult: true },
    sfall_func5: { opcode: EngineOp.TS_SFALL_METARULE5, args: 6, returns: true, popsResult: true },
    sfall_func6: { opcode: EngineOp.TS_SFALL_METARULE6, args: 7, returns: true, popsResult: true },
    sfall_func7: { opcode: EngineOp.TS_SFALL_METARULE7, args: 8, returns: true, popsResult: true },
    sfall_func8: { opcode: EngineOp.TS_SFALL_METARULE8, args: 9, returns: true, popsResult: true },
    sfall_ver_build: { opcode: EngineOp.TS_SFALL_VER_BUILD, args: 0, returns: true },
    sfall_ver_major: { opcode: EngineOp.TS_SFALL_VER_MAJOR, args: 0, returns: true },
    sfall_ver_minor: { opcode: EngineOp.TS_SFALL_VER_MINOR, args: 0, returns: true },
    sfx_build_ambient_name: { opcode: EngineOp.SFX_BUILD_AMBIENT_NAME, args: 2, returns: true },
    sfx_build_char_name: { opcode: EngineOp.SFX_BUILD_CHAR_NAME, args: 3, returns: true },
    sfx_build_interface_name: { opcode: EngineOp.SFX_BUILD_INTERFACE_NAME, args: 2, returns: true },
    sfx_build_item_name: { opcode: EngineOp.SFX_BUILD_ITEM_NAME, args: 3, returns: true },
    sfx_build_open_name: { opcode: EngineOp.SFX_BUILD_OPEN_NAME, args: 2, returns: true },
    sfx_build_scenery_name: { opcode: EngineOp.SFX_BUILD_SCENERY_NAME, args: 3, returns: true },
    sfx_build_weapon_name: { opcode: EngineOp.SFX_BUILD_WEAPON_NAME, args: 4, returns: true },
    show_iface_tag: { opcode: EngineOp.TS_SHOW_IFACE_TAG, args: 1 },
    show_real_perks: { opcode: EngineOp.TS_SHOW_REAL_PERKS, args: 0 },
    showmouse: { opcode: LibOp.SHOWMOUSE, args: 0 },
    showwin: { opcode: LibOp.SHOWWIN, args: 0 },
    signalnamed: { opcode: LibOp.SIGNALNAMED, args: 1 },
    sin: { opcode: EngineOp.TS_SIN, args: 1, returns: true },
    skill_contest: { opcode: EngineOp.SKILL_CONTEST, args: 1, returns: true, popsResult: true },
    sneak_success: { opcode: EngineOp.TS_SNEAK_SUCCESS, args: 0, returns: true },
    sounddelete: { opcode: LibOp.SOUNDDELETE, args: 1 },
    soundpause: { opcode: LibOp.SOUNDPAUSE, args: 1 },
    soundplay: { opcode: LibOp.SOUNDPLAY, args: 2, returns: true },
    soundresume: { opcode: LibOp.SOUNDRESUME, args: 1 },
    soundrewind: { opcode: LibOp.SOUNDREWIND, args: 1 },
    soundstop: { opcode: LibOp.SOUNDSTOP, args: 1 },
    source_obj: { opcode: EngineOp.SOURCE_OBJ, args: 0, returns: true },
    sprintf: { opcode: EngineOp.TS_SPRINTF, args: 2, returns: true },
    sqrt: { opcode: EngineOp.TS_SQRT, args: 1, returns: true },
    start_gdialog: { opcode: EngineOp.START_GDIALOG, args: 5 },
    stop_game: { opcode: EngineOp.TS_STOP_GAME, args: 0 },
    stop_sfall_sound: { opcode: EngineOp.TS_STOP_SFALL_SOUND, args: 1 },
    stopmovie: { opcode: LibOp.STOPMOVIE, args: 0 },
    string_split: { opcode: EngineOp.TS_STRING_SPLIT, args: 2, returns: true },
    strlen: { opcode: EngineOp.TS_STRLEN, args: 1, returns: true },
    substr: { opcode: EngineOp.TS_SUBSTR, args: 3, returns: true },
    tan: { opcode: EngineOp.TS_TAN, args: 1, returns: true },
    tap_key: { opcode: EngineOp.TS_TAP_KEY, args: 1 },
    target_obj: { opcode: EngineOp.TARGET_OBJ, args: 0, returns: true },
    temp_array: { opcode: EngineOp.TS_TEMP_ARRAY, args: 2, returns: true },
    terminate_combat: { opcode: EngineOp.TERMINATE_COMBAT, args: 0 },
    tile_contains_obj_pid: { opcode: EngineOp.TILE_CONTAINS_OBJ_PID, args: 3, returns: true },
    tile_contains_pid_obj: { opcode: EngineOp.TILE_CONTAINS_PID_OBJ, args: 3, returns: true },
    tile_distance: { opcode: EngineOp.TILE_DISTANCE, args: 2, returns: true },
    tile_distance_objs: { opcode: EngineOp.TILE_DISTANCE_OBJS, args: 2, returns: true },
    tile_get_objs: { opcode: EngineOp.TS_TILE_GET_OBJECTS, args: 2, returns: true },
    tile_in_tile_rect: { opcode: EngineOp.TILE_IN_TILE_RECT, args: 5, returns: true },
    tile_is_visible: { opcode: EngineOp.TILE_IS_VISIBLE, args: 1, returns: true },
    tile_light: { opcode: EngineOp.TS_TILE_LIGHT, args: 2, returns: true },
    tile_num: { opcode: EngineOp.TILE_NUM, args: 1, returns: true },
    tile_num_in_direction: { opcode: EngineOp.TILE_NUM_IN_DIRECTION, args: 3, returns: true },
    tile_under_cursor: { opcode: EngineOp.TS_TILE_UNDER_CURSOR, args: 0, returns: true },
    toggle_active_hand: { opcode: EngineOp.TS_TOGGLE_ACTIVE_HAND, args: 0 },
    tokenize: { opcode: LibOp.TOKENIZE, args: 3 },
    typeof: { opcode: EngineOp.TS_TYPEOF, args: 1, returns: true },
    use_obj: { opcode: EngineOp.USE_OBJ, args: 1 },
    use_obj_on_obj: { opcode: EngineOp.USE_OBJ_ON_OBJ, args: 2, returns: true },
    using_skill: { opcode: EngineOp.USING_SKILL, args: 2, returns: true, popsResult: true },
    wield_obj_critter: { opcode: EngineOp.WIELD_OBJ_CRITTER, args: 2 },
    wm_area_set_pos: { opcode: EngineOp.WM_AREA_SET_POS, args: 3 },
    world_map: { opcode: EngineOp.WORLD_MAP, args: 0 },
    write_string: { opcode: EngineOp.TS_WRITE_STRING, args: 2 },
    write_byte: { opcode: EngineOp.TS_WRITE_BYTE, args: 2 },
    write_int: { opcode: EngineOp.TS_WRITE_INT, args: 2 },
    write_short: { opcode: EngineOp.TS_WRITE_SHORT, args: 2 },
};

/** Fallout 1 spellings for the reused opcode slots, resolved through the one ordered table. */
const FALLOUT1_ONLY: Readonly<Record<string, string>> = {
    animate_jump: "ANIMATE_JUMP",
    barter_asking: "BARTER_ASKING",
    barter_offer: "BARTER_OFFER",
    reaction: "REACTION",
    town_map: "TOWN_MAP",
    turn_off_objs_in_area: "TURN_OFF_OBJS_IN_AREA",
    turn_on_objs_in_area: "TURN_ON_OBJS_IN_AREA",
};

/** Looks up an engine function by its source spelling for the target game. */
export function engineFunction(name: string, game: 1 | 2 = 2): EngineFunction | undefined {
    if (game === 1) {
        const opcodeName = FALLOUT1_ONLY[name];
        const opcode = opcodeName === undefined ? undefined : FALLOUT1_OPCODES[opcodeName];
        if (opcode !== undefined) return { opcode };
    }
    return ENGINE_FUNCTIONS[name];
}

/** Named engine function per opcode, built once from the forward table so the two cannot disagree. */
const BY_OPCODE = new Map<number, { name: string } & EngineFunction>(
    Object.entries(ENGINE_FUNCTIONS).map(([name, entry]) => [entry.opcode, { name, ...entry }]),
);

/**
 * The engine function an opcode dispatches to, for decompiling.
 *
 * Fallout 1 spellings are deliberately not resolved here. They share opcode numbers with the Fallout 2
 * names, so a reverse lookup cannot tell the two apart from the number alone - the caller knows which
 * game a file targets, and picking one silently would put the wrong name in decompiled output.
 */
export function engineFunctionAt(opcode: number): ({ name: string } & EngineFunction) | undefined {
    return BY_OPCODE.get(opcode);
}
