/**
 * Baldur's Gate II animations - the table a classic Shadows of Amn, Throne of Bhaal or BGT install needs.
 *
 * The rows below the marker are derived from the declarations an Enhanced Edition install of this family
 * ships, by `animation/test/tools/generate-animation-tables.ts`. Every character row was then resolved
 * against a classic archive through the panel's own resolver, ARMOUR LEVEL BY ARMOUR LEVEL; the levels it
 * contradicts are covered by the two hand-authored blocks above.
 *
 * Regenerate with:
 *   pnpm exec tsx animation/test/tools/generate-animation-tables.ts --table bg2 --ee <dir> --classic <dir>
 */

import { EFFECT_ROWS } from "./effects";
import { animationTable, type AnimationTable, type TableRows } from "./table";

/**
 * Where the classic game draws something the Enhanced Edition does not.
 *
 * The Enhanced Editions added a dwarf FEMALE body; the classic archive ships none - zero `CDF*` BAMs against
 * 244 `CDM*` - and draws these sets under the male one, which resolves at every armour level they use. Applied
 * unconditionally because nothing reaches this table while an install declares its own animations: an EE
 * install answers from its INIs and never asks.
 */
/**
 * The thief bodies, which a classic archive splits across two prefixes.
 *
 * An Enhanced install ships all four armour levels under the class prefix and declares its base letter as
 * that same letter, so a row derived from one names files the classic archive does not have: it keeps only
 * the studded-leather level under the class prefix and the rest under the base body. Naming the base here is
 * what lets the per-file fallback reach them - without it three levels in four draw nothing.
 */
const CLASSIC_THIEF_BODIES: TableRows = [
    [0x5300, { prefixes: ["CHMT", "CHMT", "CHMT", "CHMT"], section: "character", base: "CHMB", paperdoll: "CHMT" }],
    [0x5301, { prefixes: ["CEMT", "CEMT", "CEMT", "CEMT"], section: "character", base: "CEMB", paperdoll: "CEMT" }],
    [0x5302, { prefixes: ["CDMT", "CDMT", "CDMT", "CDMT"], section: "character", base: "CDMB", paperdoll: "CDMT" }],
    [0x5303, { prefixes: ["CIMT", "CIMT", "CIMT", "CIMT"], section: "character", base: "CIMB", paperdoll: "CIMT" }],
    [0x5310, { prefixes: ["CHFT", "CHFT", "CHFT", "CHFT"], section: "character", base: "CHFB", paperdoll: "CHFT" }],
    [0x5311, { prefixes: ["CEFT", "CEFT", "CEFT", "CEFT"], section: "character", base: "CEFB", paperdoll: "CEFT" }],
    [0x5313, { prefixes: ["CIFT", "CIFT", "CIFT", "CIFT"], section: "character", base: "CIFB", paperdoll: "CIFT" }],
    [0x6300, { prefixes: ["CHMT", "CHMT", "CHMT", "CHMT"], section: "character", base: "CHMB", paperdoll: "CHMT" }],
    [0x6301, { prefixes: ["CEMT", "CEMT", "CEMT", "CEMT"], section: "character", base: "CEMB", paperdoll: "CEMT" }],
    [0x6302, { prefixes: ["CDMT", "CDMT", "CDMT", "CDMT"], section: "character", base: "CDMB", paperdoll: "CDMT" }],
    [0x6303, { prefixes: ["CIMT", "CIMT", "CIMT", "CIMT"], section: "character", base: "CIMB", paperdoll: "CIMT" }],
    [0x6304, { prefixes: ["CDMT", "CDMT", "CDMT", "CDMT"], section: "character", base: "CDMB", paperdoll: "CGMT" }],
    [0x6305, { prefixes: ["CHMT", "CHMT", "CHMT", "CHMT"], section: "character", base: "CHMB", paperdoll: "COMT" }],
    [0x6310, { prefixes: ["CHFT", "CHFT", "CHFT", "CHFT"], section: "character", base: "CHFB", paperdoll: "CHFT" }],
    [0x6311, { prefixes: ["CEFT", "CEFT", "CEFT", "CEFT"], section: "character", base: "CEFB", paperdoll: "CEFT" }],
    [0x6313, { prefixes: ["CIFT", "CIFT", "CIFT", "CIFT"], section: "character", base: "CIFB", paperdoll: "CIFT" }],
    [0x6314, { prefixes: ["CIFT", "CIFT", "CIFT", "CIFT"], section: "character", base: "CIFB", paperdoll: "CGFT" }],
    [0x6315, { prefixes: ["CHFT", "CHFT", "CHFT", "CHFT"], section: "character", base: "CHFB", paperdoll: "COFT" }],
];

const CLASSIC_DELTAS: TableRows = [
    [0x5012, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMC"], section: "character", paperdoll: "CDMC" }],
    [0x5112, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMF"], section: "character", paperdoll: "CDMF" }],
    [0x5212, { prefixes: ["CDMW", "CDMW", "CDMW", "CDMW"], section: "character", paperdoll: "CDMW" }],
    [0x5312, { prefixes: ["CDMT", "CDMT", "CDMT", "CDMT"], section: "character", base: "CDMB", paperdoll: "CDMT" }],
    [0x6012, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMC"], section: "character", paperdoll: "CDMC" }],
    [0x6112, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMF"], section: "character", paperdoll: "CDMF" }],
    [0x6212, { prefixes: ["CDMW", "CDMW", "CDMW", "CDMW"], section: "character", paperdoll: "CDMW" }],
    [0x6214, { prefixes: ["CDMW", "CDMW", "CDMW", "CDMW"], section: "character", paperdoll: "CDMW" }],
    [0x6312, { prefixes: ["CDMT", "CDMT", "CDMT", "CDMT"], section: "character", base: "CDMB", paperdoll: "CDMT" }],
];

const DERIVED: TableRows = [
    // BEGIN GENERATED ROWS
    [0x0101, { prefixes: ["BGLRYU"], section: "effect" }],
    [0x0102, { prefixes: ["SPCL236U"], section: "effect" }],
    [0x0410, { prefixes: ["SPGLYPHI"], section: "effect" }],
    [0x1000, { prefixes: ["MWYV"], section: "monster_quadrant" }],
    [0x1003, { prefixes: ["MWYV"], section: "monster_quadrant" }],
    [0x1004, { prefixes: ["MWYV"], section: "monster_quadrant" }],
    [0x1100, { prefixes: ["MTAN"], section: "monster_quadrant" }],
    [0x1101, { prefixes: ["MWDR"], section: "monster_quadrant" }],
    [0x1102, { prefixes: ["MTAN"], section: "monster_quadrant" }],
    [0x1103, { prefixes: ["MTAN"], section: "monster_quadrant" }],
    [0x1104, { prefixes: ["MTAN"], section: "monster_quadrant" }],
    [0x1105, { prefixes: ["MWDR"], section: "monster_quadrant" }],
    [0x1200, { prefixes: ["MDR1"], section: "multi_new" }],
    [0x1201, { prefixes: ["MDR2"], section: "multi_new" }],
    [0x1202, { prefixes: ["MDR3"], section: "multi_new" }],
    [0x1203, { prefixes: ["MDR1"], section: "multi_new" }],
    [0x1204, { prefixes: ["MDR1"], section: "multi_new" }],
    [0x1205, { prefixes: ["MDR1"], section: "multi_new" }],
    [0x1206, { prefixes: ["MDR1"], section: "multi_new" }],
    [0x1207, { prefixes: ["MDR1"], section: "multi_new" }],
    [0x1208, { prefixes: ["MDR1"], section: "multi_new" }],
    [0x1300, { prefixes: ["MDEM"], section: "multi_new" }],
    [0x2000, { prefixes: ["MSIR"], section: "monster_layered_spell", overlays: ["B"] }],
    [0x2100, { prefixes: ["UVOL"], section: "monster_layered_spell", overlays: ["M"] }],
    [0x2200, { prefixes: ["MOGM"], section: "monster_layered_spell", overlays: ["S"] }],
    [0x2300, { prefixes: ["MDKN"], section: "monster_layered_spell" }],
    [0x3000, { prefixes: ["MAKH"], section: "monster_ankheg" }],
    [0x4000, { prefixes: ["SNOMC"], section: "town_static" }],
    [0x4001, { prefixes: ["SNONE"], section: "town_static" }],
    [0x4002, { prefixes: ["SNOMM"], section: "town_static" }],
    [0x4010, { prefixes: ["SNOWC"], section: "town_static" }],
    [0x4012, { prefixes: ["SNOWM"], section: "town_static" }],
    [0x4100, { prefixes: ["SSIMC"], section: "town_static" }],
    [0x4101, { prefixes: ["SSIMS"], section: "town_static" }],
    [0x4102, { prefixes: ["SSIMM"], section: "town_static" }],
    [0x4110, { prefixes: ["SSIWC"], section: "town_static" }],
    [0x4112, { prefixes: ["SSIWM"], section: "town_static" }],
    [0x4200, { prefixes: ["SHMCM"], section: "town_static" }],
    [0x4300, { prefixes: ["MSPLG1"], section: "town_static" }],
    [0x4400, { prefixes: ["LHMC"], section: "town_static" }],
    [0x4410, { prefixes: ["LHFC"], section: "town_static" }],
    [0x4500, { prefixes: ["LFAM"], section: "town_static" }],
    [0x4600, { prefixes: ["LDMF"], section: "town_static" }],
    [0x4700, { prefixes: ["LEMF"], section: "town_static" }],
    [0x4710, { prefixes: ["LEFF"], section: "town_static" }],
    [0x4800, { prefixes: ["LIMC"], section: "town_static" }],
    [0x5000, { prefixes: ["CHMB", "CHMB", "CHMB", "CHMC"], section: "character", paperdoll: "CHMC" }],
    [0x5001, { prefixes: ["CEMB", "CEMB", "CEMB", "CEMC"], section: "character", paperdoll: "CEMC" }],
    [0x5002, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMC"], section: "character", paperdoll: "CDMC" }],
    [0x5003, { prefixes: ["CIMB", "CIMB", "CIMB", "CIMC"], section: "character", paperdoll: "CIMC" }],
    [0x5010, { prefixes: ["CHFB", "CHFB", "CHFB", "CHFC"], section: "character", paperdoll: "CHFC" }],
    [0x5011, { prefixes: ["CEFB", "CEFB", "CEFB", "CEFC"], section: "character", paperdoll: "CEFC" }],
    [0x5012, { prefixes: ["CDFB", "CDFB", "CDFB", "CDFC"], section: "character", paperdoll: "CDFC" }],
    [0x5013, { prefixes: ["CIFB", "CIFB", "CIFB", "CIFC"], section: "character", paperdoll: "CIFC" }],
    [0x5100, { prefixes: ["CHMB", "CHMB", "CHMB", "CHMF"], section: "character", paperdoll: "CHMF" }],
    [0x5101, { prefixes: ["CEMB", "CEMB", "CEMB", "CEMF"], section: "character", paperdoll: "CEMF" }],
    [0x5102, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMF"], section: "character", paperdoll: "CDMF" }],
    [0x5103, { prefixes: ["CIMB", "CIMB", "CIMB", "CIMF"], section: "character", paperdoll: "CIMF" }],
    [0x5110, { prefixes: ["CHFB", "CHFB", "CHFB", "CHFF"], section: "character", paperdoll: "CHFF" }],
    [0x5111, { prefixes: ["CEFB", "CEFB", "CEFB", "CEFF"], section: "character", paperdoll: "CEFF" }],
    [0x5112, { prefixes: ["CDFB", "CDFB", "CDFB", "CDFF"], section: "character", paperdoll: "CDFF" }],
    [0x5113, { prefixes: ["CIFB", "CIFB", "CIFB", "CIFF"], section: "character", paperdoll: "CIFF" }],
    [0x5200, { prefixes: ["CHMW", "CHMW", "CHMW", "CHMW"], section: "character", paperdoll: "CHMW" }],
    [0x5201, { prefixes: ["CEMW", "CEMW", "CEMW", "CEMW"], section: "character", paperdoll: "CEMW" }],
    [0x5202, { prefixes: ["CDMW", "CDMW", "CDMW", "CDMW"], section: "character", paperdoll: "CDMW" }],
    [0x5210, { prefixes: ["CHFW", "CHFW", "CHFW", "CHFW"], section: "character", paperdoll: "CHFW" }],
    [0x5211, { prefixes: ["CEFW", "CEFW", "CEFW", "CEFW"], section: "character", paperdoll: "CEFW" }],
    [0x5212, { prefixes: ["CDFW", "CDFW", "CDFW", "CDFW"], section: "character", paperdoll: "CDFW" }],
    [0x5300, { prefixes: ["CHMT", "CHMT", "CHMT", "CHMT"], section: "character", paperdoll: "CHMT" }],
    [0x5301, { prefixes: ["CEMT", "CEMT", "CEMT", "CEMT"], section: "character", paperdoll: "CEMT" }],
    [0x5302, { prefixes: ["CDMT", "CDMT", "CDMT", "CDMT"], section: "character", paperdoll: "CDMT" }],
    [0x5303, { prefixes: ["CIMT", "CIMT", "CIMT", "CIMT"], section: "character", paperdoll: "CIMT" }],
    [0x5310, { prefixes: ["CHFT", "CHFT", "CHFT", "CHFT"], section: "character", paperdoll: "CHFT" }],
    [0x5311, { prefixes: ["CEFT", "CEFT", "CEFT", "CEFT"], section: "character", paperdoll: "CEFT" }],
    [0x5312, { prefixes: ["CDFT", "CDFT", "CDFT", "CDFT"], section: "character", paperdoll: "CDFT" }],
    [0x5313, { prefixes: ["CIFT", "CIFT", "CIFT", "CIFT"], section: "character", paperdoll: "CIFT" }],
    [0x6000, { prefixes: ["CHMB", "CHMB", "CHMB", "CHMC"], section: "character", paperdoll: "CHMC" }],
    [0x6001, { prefixes: ["CEMB", "CEMB", "CEMB", "CEMC"], section: "character", paperdoll: "CEMC" }],
    [0x6002, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMC"], section: "character", paperdoll: "CDMC" }],
    [0x6003, { prefixes: ["CIMB", "CIMB", "CIMB", "CIMC"], section: "character", paperdoll: "CIMC" }],
    [0x6004, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMC"], section: "character", paperdoll: "CGMC" }],
    [0x6005, { prefixes: ["CHMB", "CHMB", "CHMB", "CHMC"], section: "character", paperdoll: "COMC" }],
    [0x6010, { prefixes: ["CHFB", "CHFB", "CHFB", "CHFC"], section: "character", paperdoll: "CHFC" }],
    [0x6011, { prefixes: ["CEFB", "CEFB", "CEFB", "CEFC"], section: "character", paperdoll: "CEFC" }],
    [0x6012, { prefixes: ["CDFB", "CDFB", "CDFB", "CDFC"], section: "character", paperdoll: "CDFC" }],
    [0x6013, { prefixes: ["CIFB", "CIFB", "CIFB", "CIFC"], section: "character", paperdoll: "CIFC" }],
    [0x6014, { prefixes: ["CIFB", "CIFB", "CIFB", "CIFC"], section: "character", paperdoll: "CGFC" }],
    [0x6015, { prefixes: ["CHFB", "CHFB", "CHFB", "CHFC"], section: "character", paperdoll: "COFC" }],
    [0x6100, { prefixes: ["CHMB", "CHMB", "CHMB", "CHMF"], section: "character", paperdoll: "CHMF" }],
    [0x6101, { prefixes: ["CEMB", "CEMB", "CEMB", "CEMF"], section: "character", paperdoll: "CEMF" }],
    [0x6102, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMF"], section: "character", paperdoll: "CDMF" }],
    [0x6103, { prefixes: ["CIMB", "CIMB", "CIMB", "CIMF"], section: "character", paperdoll: "CIMF" }],
    [0x6104, { prefixes: ["CDMB", "CDMB", "CDMB", "CDMF"], section: "character", paperdoll: "CGMF" }],
    [0x6105, { prefixes: ["CHMB", "CHMB", "CHMB", "CHMF"], section: "character", paperdoll: "COMF" }],
    [0x6110, { prefixes: ["CHFB", "CHFB", "CHFB", "CHFF"], section: "character", paperdoll: "CHFF" }],
    [0x6111, { prefixes: ["CEFB", "CEFB", "CEFB", "CEFF"], section: "character", paperdoll: "CEFF" }],
    [0x6112, { prefixes: ["CDFB", "CDFB", "CDFB", "CDFF"], section: "character", paperdoll: "CDFF" }],
    [0x6113, { prefixes: ["CIFB", "CIFB", "CIFB", "CIFF"], section: "character", paperdoll: "CIFF" }],
    [0x6114, { prefixes: ["CIFB", "CIFB", "CIFB", "CIFF"], section: "character", paperdoll: "CGFF" }],
    [0x6115, { prefixes: ["CHFB", "CHFB", "CHFB", "CHFF"], section: "character", paperdoll: "COFF" }],
    [0x6200, { prefixes: ["CHMW", "CHMW", "CHMW", "CHMW"], section: "character", paperdoll: "CHMW" }],
    [0x6201, { prefixes: ["CEMW", "CEMW", "CEMW", "CEMW"], section: "character", paperdoll: "CEMW" }],
    [0x6202, { prefixes: ["CDMW", "CDMW", "CDMW", "CDMW"], section: "character", paperdoll: "CDMW" }],
    [0x6204, { prefixes: ["CDMW", "CDMW", "CDMW", "CDMW"], section: "character", paperdoll: "CGMW" }],
    [0x6205, { prefixes: ["CHMW", "CHMW", "CHMW", "CHMW"], section: "character", paperdoll: "COMW" }],
    [0x6210, { prefixes: ["CHFW", "CHFW", "CHFW", "CHFW"], section: "character", paperdoll: "CHFW" }],
    [0x6211, { prefixes: ["CEFW", "CEFW", "CEFW", "CEFW"], section: "character", paperdoll: "CEFW" }],
    [0x6212, { prefixes: ["CDFW", "CDFW", "CDFW", "CDFW"], section: "character", paperdoll: "CDFW" }],
    [0x6214, { prefixes: ["CDFW", "CDFW", "CDFW", "CDFW"], section: "character", paperdoll: "CGFW" }],
    [0x6215, { prefixes: ["CHFW", "CHFW", "CHFW", "CHFW"], section: "character", paperdoll: "COFW" }],
    [0x6300, { prefixes: ["CHMT", "CHMT", "CHMT", "CHMT"], section: "character", paperdoll: "CHMT" }],
    [0x6301, { prefixes: ["CEMT", "CEMT", "CEMT", "CEMT"], section: "character", paperdoll: "CEMT" }],
    [0x6302, { prefixes: ["CDMT", "CDMT", "CDMT", "CDMT"], section: "character", paperdoll: "CDMT" }],
    [0x6303, { prefixes: ["CIMT", "CIMT", "CIMT", "CIMT"], section: "character", paperdoll: "CIMT" }],
    [0x6304, { prefixes: ["CDMT", "CDMT", "CDMT", "CDMT"], section: "character", paperdoll: "CGMT" }],
    [0x6305, { prefixes: ["CHMT", "CHMT", "CHMT", "CHMT"], section: "character", paperdoll: "COMT" }],
    [0x6310, { prefixes: ["CHFT", "CHFT", "CHFT", "CHFT"], section: "character", paperdoll: "CHFT" }],
    [0x6311, { prefixes: ["CEFT", "CEFT", "CEFT", "CEFT"], section: "character", paperdoll: "CEFT" }],
    [0x6312, { prefixes: ["CDFT", "CDFT", "CDFT", "CDFT"], section: "character", paperdoll: "CDFT" }],
    [0x6313, { prefixes: ["CIFT", "CIFT", "CIFT", "CIFT"], section: "character", paperdoll: "CIFT" }],
    [0x6314, { prefixes: ["CIFT", "CIFT", "CIFT", "CIFT"], section: "character", paperdoll: "CGFT" }],
    [0x6315, { prefixes: ["CHFT", "CHFT", "CHFT", "CHFT"], section: "character", paperdoll: "COFT" }],
    [0x6400, { prefixes: ["UDRZ"], section: "character_old" }],
    [0x6401, { prefixes: ["UELM"], section: "character_old" }],
    [0x6402, { prefixes: ["CMNK"], section: "character_old" }],
    [0x6403, { prefixes: ["MSKL"], section: "character_old" }],
    [0x6404, { prefixes: ["USAR"], section: "character_old" }],
    [0x6405, { prefixes: ["MDGU"], section: "character_old" }],
    [0x6406, { prefixes: ["MDGU"], section: "character_old" }],
    [0x6500, { prefixes: ["CHMM"], section: "character", paperdoll: "CHMM" }],
    [0x6510, { prefixes: ["CHFM"], section: "character", paperdoll: "CHFM" }],
    [0x6621, { prefixes: ["XHFF", "XHFF", "XHFF", "XHFF"], section: "character_old" }],
    [0x7000, { prefixes: ["MOGH"], section: "monster_old" }],
    [0x7001, { prefixes: ["MOGN"], section: "monster_old" }],
    [0x7100, { prefixes: ["MBAS"], section: "monster_old" }],
    [0x7101, { prefixes: ["MBAS"], section: "monster_old" }],
    [0x7200, { prefixes: ["MBER"], section: "monster_old" }],
    [0x7201, { prefixes: ["MBER"], section: "monster_old" }],
    [0x7202, { prefixes: ["MBER"], section: "monster_old" }],
    [0x7203, { prefixes: ["MBER"], section: "monster_old" }],
    [0x7300, { prefixes: ["MEAE"], section: "monster" }],
    [0x7301, { prefixes: ["MEAS"], section: "monster" }],
    [0x7302, { prefixes: ["MEAE"], section: "monster" }],
    [0x7310, { prefixes: ["MFIE"], section: "monster" }],
    [0x7311, { prefixes: ["MFIS"], section: "monster" }],
    [0x7312, { prefixes: ["MFIE"], section: "monster" }],
    [0x7313, { prefixes: ["MFIS"], section: "monster" }],
    [0x7314, { prefixes: ["MFIE"], section: "monster" }],
    [0x7320, { prefixes: ["MAIR"], section: "monster" }],
    [0x7321, { prefixes: ["MAIS"], section: "monster" }],
    [0x7400, { prefixes: ["MDOG"], section: "monster_old" }],
    [0x7401, { prefixes: ["MDOG"], section: "monster_old" }],
    [0x7402, { prefixes: ["MDOG"], section: "monster_old" }],
    [0x7500, { prefixes: ["MDOP"], section: "monster_old" }],
    [0x7501, { prefixes: ["MDOP"], section: "monster_old" }],
    [0x7600, { prefixes: ["METT"], section: "monster_old" }],
    [0x7601, { prefixes: ["MGHL"], section: "monster_old" }],
    [0x7602, { prefixes: ["MSPI"], section: "monster_old" }],
    [0x7603, { prefixes: ["MDOG"], section: "monster_old" }],
    [0x7604, { prefixes: ["MSPI"], section: "monster_old" }],
    [0x7700, { prefixes: ["MGHL"], section: "monster_old" }],
    [0x7701, { prefixes: ["MGHL"], section: "monster_old" }],
    [0x7702, { prefixes: ["MGHL"], section: "monster_old" }],
    [0x7703, { prefixes: ["MSHD"], section: "monster" }],
    [0x7800, { prefixes: ["MGIB"], section: "monster_old" }],
    [0x7801, { prefixes: ["MGIB"], section: "monster_old" }],
    [0x7802, { prefixes: ["MSLI"], section: "monster_old" }],
    [0x7900, { prefixes: ["MSLI"], section: "monster_old" }],
    [0x7901, { prefixes: ["MSLI"], section: "monster_old" }],
    [0x7902, { prefixes: ["MSLI"], section: "monster_old" }],
    [0x7903, { prefixes: ["MSLI"], section: "monster_old" }],
    [0x7904, { prefixes: ["MSLI"], section: "monster_old" }],
    [0x7a00, { prefixes: ["MSPI"], section: "monster_old" }],
    [0x7a01, { prefixes: ["MSPI"], section: "monster_old" }],
    [0x7a02, { prefixes: ["MSPI"], section: "monster_old" }],
    [0x7a03, { prefixes: ["MSPI"], section: "monster_old" }],
    [0x7a04, { prefixes: ["MSPI"], section: "monster_old" }],
    [0x7b00, { prefixes: ["MWLF"], section: "monster_old" }],
    [0x7b01, { prefixes: ["MWLF"], section: "monster_old" }],
    [0x7b02, { prefixes: ["MWLF"], section: "monster_old" }],
    [0x7b03, { prefixes: ["MWLF"], section: "monster_old" }],
    [0x7b04, { prefixes: ["MWLF"], section: "monster_old" }],
    [0x7b05, { prefixes: ["MWLF"], section: "monster_old" }],
    [0x7b06, { prefixes: ["MWLS"], section: "monster_old" }],
    [0x7c00, { prefixes: ["MXVT"], section: "monster_old" }],
    [0x7c01, { prefixes: ["MTAS"], section: "monster_old" }],
    [0x7d00, { prefixes: ["MZOM"], section: "monster_old" }],
    [0x7d01, { prefixes: ["NSLF"], section: "monster_old" }],
    [0x7d02, { prefixes: ["ACHB"], section: "monster_old" }],
    [0x7d03, { prefixes: ["ACHW"], section: "monster_old" }],
    [0x7d04, { prefixes: ["NPRF"], section: "monster_old" }],
    [0x7d05, { prefixes: ["NNMF"], section: "monster_old" }],
    [0x7d06, { prefixes: ["NNWF"], section: "monster_old" }],
    [0x7d07, { prefixes: ["NSMF"], section: "monster_old" }],
    [0x7d08, { prefixes: ["NSWF"], section: "monster_old" }],
    [0x7e00, { prefixes: ["MWER"], section: "monster_old" }],
    [0x7e01, { prefixes: ["MGWE"], section: "monster_old" }],
    [0x7f00, { prefixes: ["MTRO"], section: "monster" }],
    [0x7f01, { prefixes: ["MMIN"], section: "monster" }],
    [0x7f02, { prefixes: ["MBEH"], section: "monster" }],
    [0x7f03, { prefixes: ["MIMP"], section: "monster" }],
    [0x7f04, { prefixes: ["MIGO"], section: "monster" }],
    [0x7f05, { prefixes: ["MDJI"], section: "monster" }],
    [0x7f06, { prefixes: ["MDJL"], section: "monster" }],
    [0x7f07, { prefixes: ["MGLC"], section: "monster" }],
    [0x7f08, { prefixes: ["MOTY"], section: "monster" }],
    [0x7f09, { prefixes: ["MSAH"], section: "monster" }],
    [0x7f0a, { prefixes: ["MGCP"], section: "monster" }],
    [0x7f0b, { prefixes: ["MGCL"], section: "monster" }],
    [0x7f0c, { prefixes: ["MKUO"], section: "monster" }],
    [0x7f0d, { prefixes: ["MLIC"], section: "monster" }],
    [0x7f0e, { prefixes: ["MDLI"], section: "monster" }],
    [0x7f0f, { prefixes: ["MTRS"], section: "monster" }],
    [0x7f10, { prefixes: ["MRAK"], section: "monster" }],
    [0x7f11, { prefixes: ["MUMB"], section: "monster" }],
    [0x7f12, { prefixes: ["MVAM"], section: "monster" }],
    [0x7f13, { prefixes: ["MSNK"], section: "monster" }],
    [0x7f14, { prefixes: ["MGIT"], section: "monster" }],
    [0x7f15, { prefixes: ["MBES"], section: "monster" }],
    [0x7f16, { prefixes: ["AMOO"], section: "monster" }],
    [0x7f17, { prefixes: ["ARAB"], section: "monster" }],
    [0x7f18, { prefixes: ["ADER"], section: "monster" }],
    [0x7f19, { prefixes: ["MDSW"], section: "monster" }],
    [0x7f20, { prefixes: ["AGRO"], section: "monster" }],
    [0x7f21, { prefixes: ["APHE"], section: "monster" }],
    [0x7f22, { prefixes: ["MVAF"], section: "monster" }],
    [0x7f23, { prefixes: ["MSAT"], section: "monster" }],
    [0x7f24, { prefixes: ["NPIR"], section: "monster" }],
    [0x7f27, { prefixes: ["MDRO"], section: "monster" }],
    [0x7f28, { prefixes: ["MKUL"], section: "monster" }],
    [0x7f29, { prefixes: ["MFDR"], section: "monster" }],
    [0x7f2a, { prefixes: ["NSAI"], section: "monster" }],
    [0x7f2b, { prefixes: ["MMAX"], section: "monster" }],
    [0x7f2c, { prefixes: ["NSOL"], section: "monster" }],
    [0x7f2d, { prefixes: ["MWFM"], section: "monster" }],
    [0x7f2e, { prefixes: ["MRAV"], section: "monster" }],
    [0x7f2f, { prefixes: ["MSPS"], section: "monster" }],
    [0x7f30, { prefixes: ["NBOH"], section: "monster" }],
    [0x7f31, { prefixes: ["NELL"], section: "monster" }],
    [0x7f32, { prefixes: ["MSLY"], section: "monster" }],
    [0x7f33, { prefixes: ["MKUR"], section: "monster" }],
    [0x7f34, { prefixes: ["MDOC"], section: "monster" }],
    [0x7f35, { prefixes: ["MMIS"], section: "monster" }],
    [0x7f36, { prefixes: ["NSHD"], section: "monster" }],
    [0x7f37, { prefixes: ["NIRE"], section: "monster" }],
    [0x7f38, { prefixes: ["MEYE"], section: "monster" }],
    [0x7f39, { prefixes: ["MMST"], section: "monster" }],
    [0x7f3a, { prefixes: ["NIRO"], section: "monster" }],
    [0x7f3b, { prefixes: ["MSOG"], section: "monster" }],
    [0x7f3c, { prefixes: ["MASL"], section: "monster" }],
    [0x7f3d, { prefixes: ["MMEL"], section: "monster" }],
    [0x7f3e, { prefixes: ["MFIG"], section: "monster" }],
    [0x7f3f, { prefixes: ["MFIG"], section: "monster" }],
    [0x7f40, { prefixes: ["MGLM"], section: "monster" }],
    [0x7f41, { prefixes: ["MDJL"], section: "monster" }],
    [0x7f42, { prefixes: ["NIRO"], section: "monster" }],
    [0x7f43, { prefixes: ["MOTY"], section: "monster" }],
    [0x7f44, { prefixes: ["NELW"], section: "monster" }],
    [0x7f45, { prefixes: ["MSAI"], section: "monster" }],
    [0x7f46, { prefixes: ["MBEG"], section: "monster" }],
    [0x7f47, { prefixes: ["MFI2"], section: "monster" }],
    [0x7f48, { prefixes: ["MSOF"], section: "monster" }],
    [0x7f49, { prefixes: ["MDMF"], section: "monster" }],
    [0x7f4a, { prefixes: ["MDAS"], section: "monster" }],
    [0x7f4b, { prefixes: ["MDAF"], section: "monster" }],
    [0x7f4c, { prefixes: ["MPLN"], section: "monster" }],
    [0x7f4d, { prefixes: ["MPLF"], section: "monster" }],
    [0x7f4e, { prefixes: ["MDVM"], section: "monster" }],
    [0x7f4f, { prefixes: ["MDVF"], section: "monster" }],
    [0x7f50, { prefixes: ["MMST"], section: "monster" }],
    [0x7f51, { prefixes: ["MMST"], section: "monster" }],
    [0x7f52, { prefixes: ["NSAI"], section: "monster" }],
    [0x7f53, { prefixes: ["NSAI"], section: "monster" }],
    [0x7f54, { prefixes: ["NSAI"], section: "monster" }],
    [0x7f55, { prefixes: ["NSOL"], section: "monster" }],
    [0x7f56, { prefixes: ["MWIL"], section: "monster" }],
    [0x7f57, { prefixes: ["MWIS"], section: "monster" }],
    [0x7f58, { prefixes: ["MABB"], section: "monster" }],
    [0x7f59, { prefixes: ["MABG"], section: "monster" }],
    [0x7f5a, { prefixes: ["MABR"], section: "monster" }],
    [0x7f5b, { prefixes: ["MABR"], section: "monster" }],
    [0x7f5c, { prefixes: ["MHAG"], section: "monster" }],
    [0x7f5d, { prefixes: ["MHAG"], section: "monster" }],
    [0x7f5e, { prefixes: ["MHAG"], section: "monster" }],
    [0x7f5f, { prefixes: ["MHAN"], section: "monster" }],
    [0x7f60, { prefixes: ["MSNK"], section: "monster" }],
    [0x7f61, { prefixes: ["MDRJ"], section: "monster" }],
    [0x7f62, { prefixes: ["MDRJ"], section: "monster" }],
    [0x8000, { prefixes: ["MGNL"], section: "monster_layered", overlays: ["S", "H"] }],
    [0x8100, { prefixes: ["MHOB"], section: "monster_layered", overlays: ["S", "B"] }],
    [0x8200, { prefixes: ["MKOB"], section: "monster_layered", overlays: ["S", "B"] }],
    [0x9000, { prefixes: ["MOGR"], section: "monster_large" }],
    [0xa000, { prefixes: ["MWYV"], section: "monster_large16" }],
    [0xa100, { prefixes: ["MCAR"], section: "monster_large16" }],
    [0xa200, { prefixes: ["MWYV"], section: "monster_large16" }],
    [0xa201, { prefixes: ["MCEN"], section: "monster_large16" }],
    [0xa202, { prefixes: ["MTUN"], section: "monster_large16" }],
    [0xb000, { prefixes: ["ACOW"], section: "ambient_static" }],
    [0xb100, { prefixes: ["AHRS"], section: "ambient_static" }],
    [0xb200, { prefixes: ["NBEGL"], section: "ambient_static" }],
    [0xb210, { prefixes: ["NPROL"], section: "ambient_static" }],
    [0xb300, { prefixes: ["NBOYL"], section: "ambient_static" }],
    [0xb310, { prefixes: ["NGRLL"], section: "ambient_static" }],
    [0xb400, { prefixes: ["NFAML"], section: "ambient_static" }],
    [0xb410, { prefixes: ["NFAWL"], section: "ambient_static" }],
    [0xb500, { prefixes: ["NSIML"], section: "ambient_static" }],
    [0xb510, { prefixes: ["NSIWL"], section: "ambient_static" }],
    [0xb600, { prefixes: ["NNOML"], section: "ambient_static" }],
    [0xb610, { prefixes: ["NNOWL"], section: "ambient_static" }],
    [0xb700, { prefixes: ["NSLVL"], section: "ambient_static" }],
    [0xc000, { prefixes: ["ABAT"], section: "ambient" }],
    [0xc100, { prefixes: ["ACAT"], section: "ambient" }],
    [0xc200, { prefixes: ["ACHK"], section: "ambient" }],
    [0xc300, { prefixes: ["ARAT"], section: "ambient" }],
    [0xc400, { prefixes: ["ASQU"], section: "ambient" }],
    [0xc500, { prefixes: ["ABAT"], section: "ambient" }],
    [0xc600, { prefixes: ["NBEGH"], section: "ambient" }],
    [0xc610, { prefixes: ["NPROH"], section: "ambient" }],
    [0xc700, { prefixes: ["NBOYH"], section: "ambient" }],
    [0xc710, { prefixes: ["NGRLH"], section: "ambient" }],
    [0xc800, { prefixes: ["NFAMH"], section: "ambient" }],
    [0xc810, { prefixes: ["NFAWH"], section: "ambient" }],
    [0xc900, { prefixes: ["NSIMH"], section: "ambient" }],
    [0xc910, { prefixes: ["NSIWH"], section: "ambient" }],
    [0xca00, { prefixes: ["NNOMH"], section: "ambient" }],
    [0xca10, { prefixes: ["NNOWH"], section: "ambient" }],
    [0xcb00, { prefixes: ["NSLVH"], section: "ambient" }],
    [0xcc00, { prefixes: ["MKG1"], section: "ambient" }],
    [0xcc01, { prefixes: ["MKG2"], section: "ambient" }],
    [0xcc02, { prefixes: ["MKG3"], section: "ambient" }],
    [0xcc04, { prefixes: ["ARAT"], section: "ambient" }],
    [0xd000, { prefixes: ["AEAGG1"], section: "flying" }],
    [0xd100, { prefixes: ["AGULG1"], section: "flying" }],
    [0xd200, { prefixes: ["AVULG1"], section: "flying" }],
    [0xd300, { prefixes: ["ABIRG1"], section: "flying" }],
    [0xd400, { prefixes: ["ABIRG1"], section: "flying" }],
    [0xe000, { prefixes: ["MCYC"], section: "monster_icewind" }],
    [0xe010, { prefixes: ["METN"], section: "monster_icewind" }],
    [0xe020, { prefixes: ["MTAN"], section: "monster_icewind" }],
    [0xe040, { prefixes: ["MHIS"], section: "monster_icewind" }],
    [0xe050, { prefixes: ["MLER"], section: "monster_icewind" }],
    [0xe060, { prefixes: ["MLIC"], section: "monster_icewind" }],
    [0xe070, { prefixes: ["MMIN"], section: "monster_icewind" }],
    [0xe080, { prefixes: ["MMUM"], section: "monster_icewind" }],
    [0xe090, { prefixes: ["MTAN"], section: "monster_icewind" }],
    [0xe0a0, { prefixes: ["MTIC"], section: "monster_icewind" }],
    [0xe0b0, { prefixes: ["MTRO"], section: "monster_icewind" }],
    [0xe0c0, { prefixes: ["MTSN"], section: "monster_icewind" }],
    [0xe0d0, { prefixes: ["MUMB"], section: "monster_icewind" }],
    [0xe0e0, { prefixes: ["MCOR"], section: "monster_icewind" }],
    [0xe0f0, { prefixes: ["MGIC"], section: "monster_icewind" }],
    [0xe0f1, { prefixes: ["MGLA"], section: "monster_icewind" }],
    [0xe0f2, { prefixes: ["MWAV"], section: "monster_icewind" }],
    [0xe200, { prefixes: ["MBET"], section: "monster_icewind" }],
    [0xe210, { prefixes: ["MBFI"], section: "monster_icewind" }],
    [0xe220, { prefixes: ["MBBM"], section: "monster_icewind" }],
    [0xe230, { prefixes: ["MBRH"], section: "monster_icewind" }],
    [0xe240, { prefixes: ["MANI"], section: "monster_icewind" }],
    [0xe241, { prefixes: ["MAN2"], section: "monster_icewind" }],
    [0xe242, { prefixes: ["MAN3"], section: "monster_icewind" }],
    [0xe243, { prefixes: ["MARU"], section: "monster_icewind" }],
    [0xe244, { prefixes: ["MBA1"], section: "monster_icewind" }],
    [0xe245, { prefixes: ["MBA2"], section: "monster_icewind" }],
    [0xe246, { prefixes: ["MBA3"], section: "monster_icewind" }],
    [0xe247, { prefixes: ["MBA4"], section: "monster_icewind" }],
    [0xe248, { prefixes: ["MBA5"], section: "monster_icewind" }],
    [0xe249, { prefixes: ["MBA6"], section: "monster_icewind" }],
    [0xe24a, { prefixes: ["MBAI"], section: "monster_icewind" }],
    [0xe24b, { prefixes: ["MELE"], section: "monster_icewind" }],
    [0xe24c, { prefixes: ["MELF"], section: "monster_icewind" }],
    [0xe24d, { prefixes: ["MELW"], section: "monster_icewind" }],
    [0xe24e, { prefixes: ["MGFI"], section: "monster_icewind" }],
    [0xe24f, { prefixes: ["MGFR"], section: "monster_icewind" }],
    [0xe250, { prefixes: ["MGIR"], section: "monster_icewind" }],
    [0xe251, { prefixes: ["MGVE"], section: "monster_icewind" }],
    [0xe252, { prefixes: ["MHAR"], section: "monster_icewind" }],
    [0xe253, { prefixes: ["MREM"], section: "monster_icewind" }],
    [0xe254, { prefixes: ["MSCR"], section: "monster_icewind" }],
    [0xe255, { prefixes: ["MSEE"], section: "monster_icewind" }],
    [0xe259, { prefixes: ["MSVI"], section: "monster_icewind" }],
    [0xe25a, { prefixes: ["MSV2"], section: "monster_icewind" }],
    [0xe25b, { prefixes: ["MUM2"], section: "monster_icewind" }],
    [0xe25c, { prefixes: ["MTA2"], section: "monster_icewind" }],
    [0xe25d, { prefixes: ["MYET"], section: "monster_icewind" }],
    [0xe25e, { prefixes: ["MWI4"], section: "monster_icewind" }],
    [0xe25f, { prefixes: ["MDRD"], section: "monster_icewind" }],
    [0xe260, { prefixes: ["MCRD"], section: "monster_icewind" }],
    [0xe261, { prefixes: ["MSAH"], section: "monster_icewind" }],
    [0xe262, { prefixes: ["MSAT"], section: "monster_icewind" }],
    [0xe263, { prefixes: ["MSV3"], section: "monster_icewind" }],
    [0xe264, { prefixes: ["MSV4"], section: "monster_icewind" }],
    [0xe265, { prefixes: ["MBOA"], section: "monster_icewind" }],
    [0xe266, { prefixes: ["MBU2"], section: "monster_icewind" }],
    [0xe267, { prefixes: ["MBUG"], section: "monster_icewind" }],
    [0xe26a, { prefixes: ["MDH2"], section: "monster_icewind" }],
    [0xe26b, { prefixes: ["MDTR"], section: "monster_icewind" }],
    [0xe26d, { prefixes: ["MFE2"], section: "monster_icewind" }],
    [0xe26e, { prefixes: ["MFEY"], section: "monster_icewind" }],
    [0xe26f, { prefixes: ["MGFO"], section: "monster_icewind" }],
    [0xe270, { prefixes: ["MGO5"], section: "monster_icewind" }],
    [0xe271, { prefixes: ["MGOC"], section: "monster_icewind" }],
    [0xe272, { prefixes: ["MGWO"], section: "monster_icewind" }],
    [0xe273, { prefixes: ["MGW2"], section: "monster_icewind" }],
    [0xe274, { prefixes: ["MHOH"], section: "monster_icewind" }],
    [0xe276, { prefixes: ["MLEM"], section: "monster_icewind" }],
    [0xe279, { prefixes: ["MNOS"], section: "monster_icewind" }],
    [0xe27d, { prefixes: ["MWEB"], section: "monster_icewind" }],
    [0xe27e, { prefixes: ["MWRA"], section: "monster_icewind" }],
    [0xe27f, { prefixes: ["MBOA"], section: "monster_icewind" }],
    [0xe280, { prefixes: ["MWOR"], section: "monster_icewind" }],
    [0xe281, { prefixes: ["MYUH"], section: "monster_icewind" }],
    [0xe282, { prefixes: ["MDRF"], section: "monster_icewind" }],
    [0xe283, { prefixes: ["MDRM"], section: "monster_icewind" }],
    [0xe288, { prefixes: ["MGWO"], section: "monster_icewind" }],
    [0xe289, { prefixes: ["MGW2"], section: "monster_icewind" }],
    [0xe28a, { prefixes: ["MTRO"], section: "monster_icewind" }],
    [0xe28b, { prefixes: ["MABW"], section: "monster_icewind" }],
    [0xe28c, { prefixes: ["MWD2"], section: "monster_icewind" }],
    [0xe28d, { prefixes: ["MWD2"], section: "monster_icewind" }],
    [0xe28e, { prefixes: ["MWD2"], section: "monster_icewind" }],
    [0xe28f, { prefixes: ["MDRD"], section: "monster_icewind" }],
    [0xe290, { prefixes: ["MDH2"], section: "monster_icewind" }],
    [0xe291, { prefixes: ["MBU2"], section: "monster_icewind" }],
    [0xe292, { prefixes: ["METN"], section: "monster_icewind" }],
    [0xe293, { prefixes: ["MGVE"], section: "monster_icewind" }],
    [0xe294, { prefixes: ["MBON"], section: "monster_icewind" }],
    [0xe300, { prefixes: ["MGHO"], section: "monster_icewind" }],
    [0xe310, { prefixes: ["MGH2"], section: "monster_icewind" }],
    [0xe320, { prefixes: ["MGH3"], section: "monster_icewind" }],
    [0xe400, { prefixes: ["MGO1"], section: "monster_icewind" }],
    [0xe410, { prefixes: ["MGO2"], section: "monster_icewind" }],
    [0xe420, { prefixes: ["MGO3"], section: "monster_icewind" }],
    [0xe430, { prefixes: ["MGO4"], section: "monster_icewind" }],
    [0xe440, { prefixes: ["MGO6"], section: "monster_icewind" }],
    [0xe441, { prefixes: ["MGO7"], section: "monster_icewind" }],
    [0xe442, { prefixes: ["MGO8"], section: "monster_icewind" }],
    [0xe443, { prefixes: ["MGO9"], section: "monster_icewind" }],
    [0xe444, { prefixes: ["MGO10"], section: "monster_icewind" }],
    [0xe500, { prefixes: ["MLIZ"], section: "monster_icewind" }],
    [0xe510, { prefixes: ["MLI2"], section: "monster_icewind" }],
    [0xe520, { prefixes: ["MLI3"], section: "monster_icewind" }],
    [0xe600, { prefixes: ["MMYC"], section: "monster_icewind" }],
    [0xe610, { prefixes: ["MMY2"], section: "monster_icewind" }],
    [0xe700, { prefixes: ["MNO1"], section: "monster_icewind" }],
    [0xe710, { prefixes: ["MNO2"], section: "monster_icewind" }],
    [0xe720, { prefixes: ["MNO3"], section: "monster_icewind" }],
    [0xe800, { prefixes: ["MOR1"], section: "monster_icewind" }],
    [0xe810, { prefixes: ["MOR2"], section: "monster_icewind" }],
    [0xe820, { prefixes: ["MOR3"], section: "monster_icewind" }],
    [0xe830, { prefixes: ["MOR4"], section: "monster_icewind" }],
    [0xe840, { prefixes: ["MOR5"], section: "monster_icewind" }],
    [0xe900, { prefixes: ["MSAL"], section: "monster_icewind" }],
    [0xe910, { prefixes: ["MSA2"], section: "monster_icewind" }],
    [0xea00, { prefixes: ["MSHR"], section: "monster_icewind" }],
    [0xea10, { prefixes: ["MSH1"], section: "monster_icewind" }],
    [0xea20, { prefixes: ["MSH2"], section: "monster_icewind" }],
    [0xeb00, { prefixes: ["MSKT"], section: "monster_icewind" }],
    [0xeb10, { prefixes: ["MSKA"], section: "monster_icewind" }],
    [0xeb20, { prefixes: ["MSKB"], section: "monster_icewind" }],
    [0xec00, { prefixes: ["MWIG"], section: "monster_icewind" }],
    [0xec10, { prefixes: ["MWI2"], section: "monster_icewind" }],
    [0xec20, { prefixes: ["MWI3"], section: "monster_icewind" }],
    [0xed00, { prefixes: ["MYU1"], section: "monster_icewind" }],
    [0xed10, { prefixes: ["MYU2"], section: "monster_icewind" }],
    [0xed20, { prefixes: ["MYU3"], section: "monster_icewind" }],
    [0xee00, { prefixes: ["MZO2"], section: "monster_icewind" }],
    [0xee10, { prefixes: ["MZO3"], section: "monster_icewind" }],
    [0xef10, { prefixes: ["MWWE"], section: "monster_icewind" }],
    // END GENERATED ROWS
];

/**
 * Effects first, then the derived rows, then the deltas: a later entry wins the Map, so a row this game's
 * own INIs cover overrides the family-wide effect row, and the hand-authored block overrides both.
 */
export const BG2_TABLE: AnimationTable = animationTable([
    ...EFFECT_ROWS,
    ...DERIVED,
    ...CLASSIC_THIEF_BODIES,
    ...CLASSIC_DELTAS,
]);
