#!/bin/bash

# Package the extension into a VSIX.
# Uses --no-dependencies to skip vsce's npm list (fails with pnpm's layout).
#
# Flow:
# 1. Run prepublish build (needs full pnpm deps)
# 2. Replace server/node_modules with a flat prod closure (symlinks crash vsce's zip writer)
# 3. Package with SKIP_PREPUBLISH=1 to avoid rebuilding after strip
# 4. Inject TS plugins into VSIX (vsce's .vscodeignore re-include patterns don't
#    work for node_modules/ with --no-dependencies, so we add them post-packaging)
# 5. Restore server/node_modules via pnpm install

set -eu -o pipefail

# Workspace package symlinks under server/node_modules (e.g. @bgforge/format ->
# ../../../format) are captured here before the strip below removes them. pnpm
# install treats an existing node_modules as already satisfied and will NOT
# recreate a symlink we deleted by hand, so the restore recreates them itself.
# They are esbuild-bundled into server/out, so the VSIX does not need them - but
# the later `pnpm publish` of @bgforge/mls-server needs the link present to
# resolve its workspace:* dependency version.
workspace_links=()

restore_node_modules() {
    echo "Restoring node_modules..."
    # pnpm's install state still reads "up to date" after the symlink strip, so a plain
    # install no-ops and leaves server/ without its deps; remove the dir to force a rebuild.
    rm -rf server/node_modules
    pnpm install --frozen-lockfile
    local entry path target
    for entry in "${workspace_links[@]}"; do
        path="${entry%%=*}"
        target="${entry#*=}"
        if [ ! -e "$path" ] && [ ! -L "$path" ]; then
            mkdir -p "$(dirname "$path")"
            ln -s "$target" "$path"
        fi
    done
}

trap restore_node_modules EXIT

# Step 1: Build with full deps available, from a clean slate: the out dirs are
# packaged wholesale, so stale bundles from retired features would ship from a
# long-lived tree. client/out is fully regenerated by prepublish; server/out ALSO
# holds committed data JSONs (generate-data.sh outputs the TS plugins bundle),
# so only its gitignored build outputs are cleaned.
rm -rf client/out
git clean -fdX server/out
./scripts/prepublish.sh

# Record workspace package symlinks (target outside the pnpm store) before step 2 replaces the
# directory, so restore_node_modules can recreate them. Dev-dep symlinks (targets in .pnpm/) are left
# for pnpm install to handle and are not recorded.
for entry in server/node_modules/@*/*; do
    [ -L "$entry" ] || continue
    target=$(readlink "$entry")
    case "$target" in
        *.pnpm/*) ;;
        *) workspace_links+=("$entry=$target") ;;
    esac
done

# Step 2: Replace server/node_modules with a flat, symlink-free copy of the server's runtime closure.
# The staging script explains the shape and why pnpm's own `deploy` is not usable from in here.
stage_dir="tmp/pkg-server-deps"
node scripts/stage-server-runtime-deps.mjs "$stage_dir"
rm -rf server/node_modules
mv "$stage_dir" server/node_modules

# Step 3: Package without re-running prepublish.
mkdir -p dist
name=$(node -p "require('./package.json').name")
version=${ARTIFACT_VERSION:-$(node -p "require('./package.json').version")}
# This step prints `npm warn Unknown env config "manage-package-manager-versions"`, and that line is
# expected: vsce has no flag to skip the prepublish hook, so it shells out to `npm run` even though
# SKIP_PREPUBLISH makes that script a no-op here, and pnpm exports its own settings as npm_config_* to
# children. Unsetting the variable before this line does not work - pnpm re-injects it into whatever it
# runs (verified) - and the alternatives are worse: calling the vsce binary directly to escape pnpm's
# env, or lowering npm's loglevel, which would hide npm's real warnings too.
SKIP_PREPUBLISH=1 pnpm vsce package --no-dependencies --out "dist/${name}-${version}.vsix" "$@"

# Step 4: Inject TS plugins into VSIX.
# vsce excludes node_modules/ entirely with --no-dependencies; re-include
# patterns (!node_modules/pkg/) don't work. Inject the built plugin bundles
# into the VSIX post-packaging. tsserver requires plugins in node_modules/.
vsix_file="dist/${name}-${version}.vsix"

if [ ! -f "$vsix_file" ]; then
    echo "ERROR: expected $vsix_file not found after vsce package"
    exit 1
fi

echo "Injecting TS plugins into $vsix_file"

plugin_files=(
    "node_modules/bgforge-tssl-plugin/package.json"
    "node_modules/bgforge-tssl-plugin/index.js"
    "node_modules/bgforge-td-plugin/package.json"
    "node_modules/bgforge-td-plugin/index.js"
)

for f in "${plugin_files[@]}"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: $f not found, cannot inject into VSIX"
        exit 1
    fi
done

inject_dir=".pkg-inject"
rm -rf "$inject_dir"
mkdir -p "$inject_dir/extension/node_modules/bgforge-tssl-plugin"
mkdir -p "$inject_dir/extension/node_modules/bgforge-td-plugin"
cp node_modules/bgforge-tssl-plugin/package.json node_modules/bgforge-tssl-plugin/index.js \
    "$inject_dir/extension/node_modules/bgforge-tssl-plugin/"
cp node_modules/bgforge-td-plugin/package.json node_modules/bgforge-td-plugin/index.js \
    "$inject_dir/extension/node_modules/bgforge-td-plugin/"

(cd "$inject_dir" && zip -gX "../$vsix_file" \
    extension/node_modules/bgforge-tssl-plugin/package.json \
    extension/node_modules/bgforge-tssl-plugin/index.js \
    extension/node_modules/bgforge-td-plugin/package.json \
    extension/node_modules/bgforge-td-plugin/index.js)

rm -rf "$inject_dir"

# Fail closed if the packaged VSIX regressed in size or shipped unexpected content.
# The .vscodeignore denylist ships anything new by default, and no test opens the produced
# bundle - this is the gate that does (see .vscodeignore header).
./scripts/verify-package-contents.sh "$vsix_file"

echo "Done"
