// Auto-generated from IESDP _data/file_formats/eff_v2/body.yml. Do not hand-edit.

import { u16, u32, u8 } from "typed-binary";
import { arraySpec, charsSpec, type FieldSpec, type SpecData } from "../../spec/types";

export const effBodySpec = {
    signature2: charsSpec(4),
    version2: charsSpec(4),
    opcode: { codec: u32, description: "Opcode number" },
    target: { codec: u32, description: "Target type - 0 -> None - 1 -> Self - 2 -> Projectile target - 3 -> Party - 4 -> Everyone - 5 -> Everyone except party - 6 -> Caster group - 7 -> Target group - 8 -> Everyone except self - 9 -> ...", docUrl: "https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm" },
    power: { codec: u32, description: "Power" },
    parameter1: { codec: u32, description: "Parameter 1" },
    parameter2: { codec: u32, description: "Parameter 2" },
    timing: { codec: u16, description: "**Timing mode** - 0 -> Instant/Limited - 1 -> Instant/Permanent - 2 -> Instant/While equipped - 3 -> Delay/Limited - 4 -> Delay/Permanent - 5 -> Delay/While equipped - 6 -> Limited after duration - 7 ...", docUrl: "https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm" },
    unused1: { codec: u16 },
    duration: { codec: u32, description: "Duration - This field is measured in seconds or ticks ( 1 ⁄ 15 second), depending on Timing mode . If called via opcode #177 / opcode #183 / opcode #283 , this field is ignored." },
    probability1: { codec: u16, description: "Probability 1 If called via opcode #183 , this field is ignored." },
    probability2: { codec: u16, description: "Probability 2 See here for further details. If called via opcode #183 , this field is ignored." },
    resource: charsSpec(8),
    diceThrown: { codec: u32, description: "Dice Thrown" },
    diceSides: { codec: u32, description: "Dice Sides" },
    saveType: { codec: u32, description: "Saving throw type - bit 0 -> Spells - bit 1 -> Breath - bit 2 -> Paralyze / Poison / Death - bit 3 -> Wands - bit 4 -> Petrify / Polymorph - bit 5 -> Spells (EE only) - see opcode #322 - bit 6 -> ...", docUrl: "https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm" },
    saveBonus: { codec: u32, description: "Save bonus If called via opcode #183 , this field is ignored." },
    stackingIdTobex: { codec: u32, description: "Special (EE games) TobEx: Stacking ID.", docUrl: "https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm" },
    school: { codec: u32, description: "Primary Type (School) - See MSCHOOL.2DA ." },
    unused2: { codec: u32 },
    unused3: { codec: u32 },
    unused4: { codec: u32 },
    resistance: { codec: u32, description: "Dispel/Resistance The default behaviour is that effects cannot be dispelled and ignore resistance.", docUrl: "https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm" },
    parameter3: { codec: u32, description: "Parameter 3" },
    parameter4: { codec: u32, description: "Parameter 4" },
    parameter5: { codec: u32, description: "Parameter 5" },
    timeApplied: { codec: u32, description: "Time applied (ticks) - It stores the gametime (ticks) at which the effect was originally applied." },
    resource2: charsSpec(8),
    resource3: charsSpec(8),
    casterXCoord: { codec: u32, description: "Caster X coordinate" },
    casterYCoord: { codec: u32, description: "Caster Y coordinate" },
    targetXCoord: { codec: u32, description: "Target X coordinate" },
    targetYCoord: { codec: u32, description: "Target Y coordinate" },
    parentResourceType: { codec: u32, description: "Parent resource type - 0 -> None - 1 -> Spell - 2 -> Item" },
    parentResource: charsSpec(8),
    parentResourceFlags: { codec: u32, description: "Parent resource flags - bit 10 -> Hostile - bit 11 -> No LOS required - bit 12 -> Allow spotting - bit 13 -> Outdoors only - bit 14 -> Non-magical ability - bit 15 -> Ignore Wild Surge - bit 16 -> ...", docUrl: "https://gibberlings3.github.io/iesdp/file_formats/ie_formats/eff_v2.htm" },
    projectile: { codec: u32, description: "Projectile" },
    unused5: { codec: u32 },
    variableName: arraySpec({ element: { codec: u8 }, count: 32 }),
    casterLevel: { codec: u32, description: "Caster level" },
    unused6: { codec: u32 },
    sectype: { codec: u32, description: "Secondary Type - See MSECTYPE.2DA ." },
    unused7: arraySpec({ element: { codec: u32 }, count: 15 }),
} satisfies Record<string, FieldSpec>;

export type EffBodyData = SpecData<typeof effBodySpec>;
